
USE recipe_analysis;
DROP TABLE IF EXISTS steps;
CREATE TABLE contains(
id INT NOT NULL AUTO_INCREMENT,
descrizione VARCHAR(500),
numero_step INT,
PRIMARY KEY (id),
FOREIGN KEY (actionID) REFERENCES actions(id)
);
INSERT INTO steps (descrizione, numero_step) VALUES ('Place chipped beef on bottom of baking dish.',1, 0);
INSERT INTO steps (descrizione, numero_step) VALUES ('Place chicken on top of beef.',2, 0);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix soup and cream together',3, 1);
INSERT INTO steps (descrizione, numero_step) VALUES (' pour over chicken.',4, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake, uncovered, at 275° for 3 hours.',5, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('In a slow cooker, combine all ingredients.',1, 4);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cover and cook on low for 4 hours or until heated through and cheese is melted.',2, 5);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir well before serving.',3, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Yields 6 servings.',4, 7);
INSERT INTO steps (descrizione, numero_step) VALUES ('Boil and debone chicken.',1, 8);
INSERT INTO steps (descrizione, numero_step) VALUES ('Put bite size pieces in average size square casserole dish.',2, 9);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour gravy and cream of mushroom soup over chicken',3, 2);
INSERT INTO steps (descrizione, numero_step) VALUES (' level.',4, 10);
INSERT INTO steps (descrizione, numero_step) VALUES ('Make stuffing according to instructions on box (do not make too moist).',5, 11);
INSERT INTO steps (descrizione, numero_step) VALUES ('Put stuffing on top of chicken and gravy',6, 9);
INSERT INTO steps (descrizione, numero_step) VALUES (' level.',7, 10);
INSERT INTO steps (descrizione, numero_step) VALUES ('Sprinkle shredded cheese on top and bake at 350° for approximately 20 minutes or until golden and bubbly.',8, 12);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine first four ingredients and press in 13 x 9-inch ungreased pan.',1, 4);
INSERT INTO steps (descrizione, numero_step) VALUES ('Melt chocolate chips and spread over mixture.',2, 13);
INSERT INTO steps (descrizione, numero_step) VALUES ('Refrigerate for about 20 minutes and cut into pieces before chocolate gets hard.',3, 14);
INSERT INTO steps (descrizione, numero_step) VALUES ('Keep in refrigerator.',4, 15);
INSERT INTO steps (descrizione, numero_step) VALUES ('Wash potatoes',1, 16);
INSERT INTO steps (descrizione, numero_step) VALUES (' prick several times with a fork.',2, 17);
INSERT INTO steps (descrizione, numero_step) VALUES ('Microwave them with a wet paper towel covering the potatoes on high for 6-8 minutes.',3, 18);
INSERT INTO steps (descrizione, numero_step) VALUES ('The potatoes should be soft, ready to eat.',4, 19);
INSERT INTO steps (descrizione, numero_step) VALUES ('Let them cool enough to handle.',5, 20);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cut in half lengthwise',6, 21);
INSERT INTO steps (descrizione, numero_step) VALUES (' scoop out pulp and reserve.',7, 22);
INSERT INTO steps (descrizione, numero_step) VALUES ('Discard shells.',8, 23);
INSERT INTO steps (descrizione, numero_step) VALUES ('Brown ground beef until done.',9, 24);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drain any grease from the meat.',10, 25);
INSERT INTO steps (descrizione, numero_step) VALUES ('Set aside when done.',11, 26);
INSERT INTO steps (descrizione, numero_step) VALUES ('Melt butter in a large kettle over low heat',12, 27);
INSERT INTO steps (descrizione, numero_step) VALUES (' add flour, stirring until smooth.',13, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cook 1 minute, stirring constantly.',14, 29);
INSERT INTO steps (descrizione, numero_step) VALUES ('Gradually add milk',15, 28);
INSERT INTO steps (descrizione, numero_step) VALUES (' cook over medium heat, stirring constantly, until thickened and bubbly.',16, 29);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir in potato, ground beef, salt, pepper, 1 cup of cheese, 2 tablespoons of green onion and 1/2 cup of bacon.',17, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cook until heated (do not boil).',18, 29);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir in sour cream if desired',19, 6);
INSERT INTO steps (descrizione, numero_step) VALUES (' cook until heated (do not boil).',20, 29);
INSERT INTO steps (descrizione, numero_step) VALUES ('Sprinkle with remaining cheese, bacon and green onions.',21, 12);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cream sugar and butter.',1, 30);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add egg and beat well.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('To creamed butter, sugar and egg, add alternately buttermilk with mixture of flour, salt and soda.',3, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix well.',4, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add rhubarb and vanilla.',5, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour into greased 9 x 13-inch pan and add Topping.',6, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix together both cans of corn, crackers, egg, 2 teaspoons of melted butter and pepper and place in a buttered baking dish.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Dot with remaining 4 teaspoons of butter.',2, 31);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 350° for 1 hour.',3, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Roll steak strips in flour.',1, 32);
INSERT INTO steps (descrizione, numero_step) VALUES ('Brown in skillet.',2, 24);
INSERT INTO steps (descrizione, numero_step) VALUES ('Salt and pepper.',3, 33);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine tomato liquid, water, onions and browned steak.',4, 4);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cover and simmer for one and a quarter hours.',5, 5);
INSERT INTO steps (descrizione, numero_step) VALUES ('Uncover and stir in Worcestershire sauce.',6, 34);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add tomatoes, green peppers and simmer for 5 minutes.',7, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Serve over hot cooked rice.',8, 35);
INSERT INTO steps (descrizione, numero_step) VALUES ('Empty Cool Whip into a bowl.',1, 36);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drain juice from pineapple.',2, 25);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix Cool Whip and pineapple.',3, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add condensed milk.',4, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Squeeze lemons, remove seeds and add to Cool Whip and pineapple.',5, 37);
INSERT INTO steps (descrizione, numero_step) VALUES ('Chop nuts into small pieces and add to mixture.',6, 38);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir all ingredients together and mix well.',7, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour into a graham cracker crust.',8, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Use top from crust to cover top of pie.',9, 39);
INSERT INTO steps (descrizione, numero_step) VALUES ('Chill overnight.',10, 40);
INSERT INTO steps (descrizione, numero_step) VALUES ('Makes 2 pies.',11, 41);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drain cherries, measuring syrup.',1, 25);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cut cherries in half.',2, 21);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add ginger ale and enough water to syrup to make 1 1/2 cups.',3, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Dissolve gelatin in boiling water.',4, 42);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add measured liquid and almond extract.',5, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Chill until very thick.',6, 40);
INSERT INTO steps (descrizione, numero_step) VALUES ('Fold in marshmallows and the cherries.',7, 43);
INSERT INTO steps (descrizione, numero_step) VALUES ('Spoon into 6-cup mold.',8, 44);
INSERT INTO steps (descrizione, numero_step) VALUES ('Chill until firm, at least 4 hours or overnight.',9, 40);
INSERT INTO steps (descrizione, numero_step) VALUES ('Makes about 5 1/3 cups.',10, 41);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix sugar, butter and peanut butter.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Roll into balls and place on cookie sheet.',2, 32);
INSERT INTO steps (descrizione, numero_step) VALUES ('Set in freezer for at least 30 minutes.',3, 26);
INSERT INTO steps (descrizione, numero_step) VALUES ('Melt chocolate chips and paraffin in double boiler.',4, 45);
INSERT INTO steps (descrizione, numero_step) VALUES ('Using a toothpick, dip balls 3/4 of way into chocolate chip and paraffin mixture to make them look like buckeyes.',5, 11);
INSERT INTO steps (descrizione, numero_step) VALUES ('Clean wings.',1, 46);
INSERT INTO steps (descrizione, numero_step) VALUES ('Flour and fry until done.',2, 47);
INSERT INTO steps (descrizione, numero_step) VALUES ('Place fried chicken wings in microwave bowl.',3, 0);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir in barbecue sauce.',4, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Microwave on High (stir once) for 4 minutes.',5, 18);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix taco sauce, sour cream and cream cheese.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Spread on pizza pan.',2, 13);
INSERT INTO steps (descrizione, numero_step) VALUES ('Brown meat.',3, 24);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drain off fat and add taco seasoning.',4, 48);
INSERT INTO steps (descrizione, numero_step) VALUES ('Spread over cream mixture.',5, 13);
INSERT INTO steps (descrizione, numero_step) VALUES ('Layer with raw vegetables.',6, 49);
INSERT INTO steps (descrizione, numero_step) VALUES ('Top with cheese.',7, 50);
INSERT INTO steps (descrizione, numero_step) VALUES ('Serve with chips.',8, 51);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix all ingredients together.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour into a 9 x 13-inch pan.',2, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Freeze until firm.',3, 52);
INSERT INTO steps (descrizione, numero_step) VALUES ('Allow to set out approximately 15 minutes before serving.',4, 53);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix water, cornstarch, sugar and salt in saucepan.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir constantly and boil until thick and clear.',2, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Remove from heat and stir in jello.',3, 54);
INSERT INTO steps (descrizione, numero_step) VALUES ('Set aside to cool.',4, 26);
INSERT INTO steps (descrizione, numero_step) VALUES ('But don't allow it to set.',5, 53);
INSERT INTO steps (descrizione, numero_step) VALUES ('Layer strawberries in baked crust.',6, 49);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour cooled glaze over.',7, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Continue layering berries and glaze.',8, 55);
INSERT INTO steps (descrizione, numero_step) VALUES ('Refrigerate.',9, 14);
INSERT INTO steps (descrizione, numero_step) VALUES ('Serve with whipped cream.',10, 51);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix according to directions and add oil.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake in 9 x 13-inch pan.',2, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Trim off large leaves of broccoli and remove the tough ends of lower stalks.',1, 56);
INSERT INTO steps (descrizione, numero_step) VALUES ('Wash the broccoli thoroughly.',2, 16);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cut the florets and stems into bite-size pieces.',3, 21);
INSERT INTO steps (descrizione, numero_step) VALUES ('Place in a large bowl.',4, 0);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add bacon, onions and raisins.',5, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine remaining ingredients, stirring well.',6, 4);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add dressing to broccoli mixture and toss gently.',7, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cover and refrigerate 2 to 3 hours.',8, 5);
INSERT INTO steps (descrizione, numero_step) VALUES ('Makes about 6 servings.',9, 41);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix Jell-O in boiling water.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add strawberries, pineapple, crushed bananas and nuts.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Spread 1/2 mixture in 13 x 6 1/2-inch pan.',3, 13);
INSERT INTO steps (descrizione, numero_step) VALUES ('Allow to gel in freezer 30 minutes.',4, 53);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add layer of sour cream, then remaining mixture on top.',5, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Gel and serve.',6, 51);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix Crisco with applesauce, nuts and raisins.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Sift dry ingredients and add.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix well.',3, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Put in a greased and floured loaf pan or tube pan.',4, 57);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake in loaf pan at 350° to 375° for 45 to 60 minutes, layer pan at 375° for 20 minutes or tube pan at 325° for 1 hour.',5, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cream sugar and shortening.',1, 30);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add eggs, salt and soda, then bananas and flour.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add nuts.',3, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix well.',4, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake in loaf pan at 350° for 1 hour.',5, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix ingredients together for 5 minutes.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Scrape bowl often.',2, 58);
INSERT INTO steps (descrizione, numero_step) VALUES ('Last fold in chocolate chip mints.',3, 59);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 350° for 35 to 40 minutes or until done (cake mix directions).',4, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Buy whole turkey breast',1, 60);
INSERT INTO steps (descrizione, numero_step) VALUES (' remove all skin and bones.',2, 54);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cut into pieces about the size of your hand.',3, 21);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour marinade over turkey and refrigerate for at least 8 hours (up to 48 hours).',4, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('The longer it marinates, the less cooking time it takes.',5, 61);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cook ground or chopped peppers and onions in oil for 1/2 hour.',1, 29);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cook tomatoes and garlic as for juice.',2, 29);
INSERT INTO steps (descrizione, numero_step) VALUES ('Put through the mill.',3, 9);
INSERT INTO steps (descrizione, numero_step) VALUES ('(I use a food processor and do my tomatoes uncooked.',4, 39);
INSERT INTO steps (descrizione, numero_step) VALUES ('I then add the garlic right to the juice.)',5, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add peppers and onions to juice and remainder of ingredients.',6, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cook approximately 1 hour.',7, 29);
INSERT INTO steps (descrizione, numero_step) VALUES ('Put in jars and seal.',8, 9);
INSERT INTO steps (descrizione, numero_step) VALUES ('Yields 7 quarts.',9, 7);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix well.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Press firmly into an 8 1/2 x 4 1/2 x 2 1/2-inch loaf pan.',2, 62);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake in preheated moderate oven.',3, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 350° for 1 hour.',4, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Let stand 5 minutes before slicing.',5, 20);
INSERT INTO steps (descrizione, numero_step) VALUES ('Makes 8 servings.',6, 41);
INSERT INTO steps (descrizione, numero_step) VALUES ('Alex Patout says, "Smothering is a multipurpose Cajun technique that works wonders with everything from game to snap beans.',1, 63);
INSERT INTO steps (descrizione, numero_step) VALUES ('It's similar to what the rest of the world knows as braising.',2, 64);
INSERT INTO steps (descrizione, numero_step) VALUES ('The ingredients are briefly browned or sauteed, then cooked with a little liquid over a low heat for a long time."',3, 65);
INSERT INTO steps (descrizione, numero_step) VALUES ('Brown strips in cooking oil.',1, 24);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour off drippings.',2, 66);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine tomato sauce, water, brown sugar, mustard and Worcestershire sauce.',3, 4);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add sauce and onion to meat slices.',4, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cover and cook slowly, stirring occasionally 30 minutes or until meat is tender.',5, 5);
INSERT INTO steps (descrizione, numero_step) VALUES ('Serve over rice or buttered noodles.',6, 51);
INSERT INTO steps (descrizione, numero_step) VALUES ('Yields 6 to 8 servings.',7, 7);
INSERT INTO steps (descrizione, numero_step) VALUES ('Butter a square pan, 8 x 8 x 2-inches.',1, 67);
INSERT INTO steps (descrizione, numero_step) VALUES ('Heat milk, chocolate chips and unsweetened chocolate over low heat, stirring constantly, until chocolate is melted and mixture is smooth.',2, 68);
INSERT INTO steps (descrizione, numero_step) VALUES ('Remove from heat.',3, 54);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir in nuts and vanilla.',4, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Spread in pan.',5, 13);
INSERT INTO steps (descrizione, numero_step) VALUES ('In a large skillet, brown the ground beef.',1, 24);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drain, stir in taco mix, kidney beans, and salsa.',2, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bring to a boil.',3, 8);
INSERT INTO steps (descrizione, numero_step) VALUES ('Reduce heat, and let simmer for about 5 minutes.',4, 69);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cut peppers in half and clean it.',5, 21);
INSERT INTO steps (descrizione, numero_step) VALUES ('Put peppers in boiling water for 3 minutes- drain- spoon the meat mixture into the green pepper.',6, 9);
INSERT INTO steps (descrizione, numero_step) VALUES ('Put pepper in an ungreased pan.',7, 9);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cover, and bake at 350 degrees for 15 to 20 minutes or until peppers are crispy and filling is heated through.',8, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Top with tomatoes, cheese, and sour cream.',9, 50);
INSERT INTO steps (descrizione, numero_step) VALUES ('Put flour into a large mixing bowl.',1, 9);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine sugar, milk, salt and oil in a saucepan and heat to boiling',2, 4);
INSERT INTO steps (descrizione, numero_step) VALUES (' remove from heat and let cool to lukewarm.',3, 54);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add yeast and mix well.',4, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour into flour and stir.',5, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Batter will be sticky.',6, 70);
INSERT INTO steps (descrizione, numero_step) VALUES ('Roll out batter on a floured board and cut with biscuit cutter.',7, 71);
INSERT INTO steps (descrizione, numero_step) VALUES ('Lightly brush tops with melted oleo and fold over.',8, 72);
INSERT INTO steps (descrizione, numero_step) VALUES ('Place rolls on a cookie sheet, put in a warm place and let rise for 1 hour.',9, 73);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 350° for about 20 minutes.',10, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Yield: 2 1/2 dozen.',11, 74);
INSERT INTO steps (descrizione, numero_step) VALUES ('In a 6-quart punch bowl mix all of the cans of fruit, juice and all.',1, 75);
INSERT INTO steps (descrizione, numero_step) VALUES ('Clean and slice berries.',2, 76);
INSERT INTO steps (descrizione, numero_step) VALUES ('Wash and slice apples',3, 16);
INSERT INTO steps (descrizione, numero_step) VALUES (' leave peeling on apples.',4, 77);
INSERT INTO steps (descrizione, numero_step) VALUES ('Dice apples.',5, 78);
INSERT INTO steps (descrizione, numero_step) VALUES ('Slice bananas.',6, 76);
INSERT INTO steps (descrizione, numero_step) VALUES ('Wash and cut grapes in half.',7, 16);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix all together.',8, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Nuts or other fruit may be added.',9, 79);
INSERT INTO steps (descrizione, numero_step) VALUES ('Double recipe for more chicken.',1, 80);
INSERT INTO steps (descrizione, numero_step) VALUES ('Grease a 9 x 12-inch cake pan.',1, 81);
INSERT INTO steps (descrizione, numero_step) VALUES ('Spread cherry pie mix.',2, 13);
INSERT INTO steps (descrizione, numero_step) VALUES ('Sift cake mix and spread it dry over the cherries.',3, 13);
INSERT INTO steps (descrizione, numero_step) VALUES ('Top with ground nuts.',4, 50);
INSERT INTO steps (descrizione, numero_step) VALUES ('Melt butter and pour over top.',5, 82);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake 45 minutes in a 350° oven.',6, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Beat eggs, salt and pepper until well blended.',1, 83);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir in half and half, potatoes and onions.',2, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour into well-greased 8-inch baking dish.',3, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake in a 400° oven for 35 to 40 minutes, or until knife inserted in center comes out clean and potatoes are tender.',4, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cool on rack 5 minutes',5, 84);
INSERT INTO steps (descrizione, numero_step) VALUES (' cut into squares.',6, 21);
INSERT INTO steps (descrizione, numero_step) VALUES ('Makes 4 large servings.',7, 41);
INSERT INTO steps (descrizione, numero_step) VALUES ('Prepare macaroni and cheese as directed.',1, 85);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add drained tuna, pimento and onion.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix.',3, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Serve hot or cold.',4, 51);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drain artichokes and chop.',1, 25);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix with mayonnaise and Parmesan cheese.',2, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('After well mixed, bake, uncovered, for 20 to 30 minutes at 350°.',3, 86);
INSERT INTO steps (descrizione, numero_step) VALUES ('Serve with crackers.',4, 51);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix together sour cream, soup mix, broccoli and half of cheese.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Sprinkle remaining cheese on top.',2, 12);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 350° for 30 minutes, uncovered.',3, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Serve hot with vegetable crackers.',4, 51);
INSERT INTO steps (descrizione, numero_step) VALUES ('Prepare spaghetti per package.',1, 85);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drain.',2, 25);
INSERT INTO steps (descrizione, numero_step) VALUES ('Melt a little butter through it.',3, 27);
INSERT INTO steps (descrizione, numero_step) VALUES ('Marinate overnight in Salad Supreme and Zesty Italian dressing.',4, 87);
INSERT INTO steps (descrizione, numero_step) VALUES ('Just before serving, add cucumbers, tomatoes, green peppers, mushrooms, olives or whatever your taste may want.',5, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drain pears, reserving juice.',1, 25);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bring juice to a boil, stirring constantly.',2, 8);
INSERT INTO steps (descrizione, numero_step) VALUES ('Remove from heat.',3, 54);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add gelatin, stirring until dissolved.',4, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Let cool slightly.',5, 20);
INSERT INTO steps (descrizione, numero_step) VALUES ('Coarsely chop pear halves.',6, 38);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine cream cheese and yogurt',7, 4);
INSERT INTO steps (descrizione, numero_step) VALUES (' beat at medium speed of electric mixer until smooth.',8, 83);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add gelatin and beat well.',9, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir in pears.',10, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour into an oiled 4-cup mold or Pyrex dish.',11, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Chill.',12, 40);
INSERT INTO steps (descrizione, numero_step) VALUES ('Trim off green and pink parts of watermelon rind',1, 56);
INSERT INTO steps (descrizione, numero_step) VALUES (' cut to 1-inch cubes.',2, 21);
INSERT INTO steps (descrizione, numero_step) VALUES ('Parboil until tender, but not soft.',3, 88);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drain.',4, 25);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine sugar, vinegar, oil of cloves and oil of cinnamon',5, 4);
INSERT INTO steps (descrizione, numero_step) VALUES (' bring to boiling and pour over rind.',6, 82);
INSERT INTO steps (descrizione, numero_step) VALUES ('Let stand overnight.',7, 20);
INSERT INTO steps (descrizione, numero_step) VALUES ('In the morning, drain off syrup.',8, 48);
INSERT INTO steps (descrizione, numero_step) VALUES ('Heat and put over rind.',9, 68);
INSERT INTO steps (descrizione, numero_step) VALUES ('The third morning, heat rind and syrup',10, 68);
INSERT INTO steps (descrizione, numero_step) VALUES (' seal in hot, sterilized jars.',11, 89);
INSERT INTO steps (descrizione, numero_step) VALUES ('Makes 8 pints.',12, 41);
INSERT INTO steps (descrizione, numero_step) VALUES ('(Oil of cinnamon and clove keeps rind clear and transparent.)',13, 90);
INSERT INTO steps (descrizione, numero_step) VALUES ('Remove chicken from bone.',1, 54);
INSERT INTO steps (descrizione, numero_step) VALUES ('Use the broth.',2, 39);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix the vegetables and macaroni.',3, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add sugar, salt and black pepper.',4, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cook until all vegetables are tender over medium heat.',5, 29);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix 3 tablespoons fat with granulated sugar.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add egg and beat until creamy.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix flour, baking powder and salt thoroughly.',3, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add to sugar mixture alternately with milk.',4, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add vanilla.',5, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Spread batter evenly in a greased 8-inch square baking pan.',6, 13);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix brown sugar and cinnamon and sprinkle over batter.',7, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Dot with 2 tablespoons fat.',8, 31);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 350° (moderate oven) for 25 to 30 minutes.',9, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix flour, sugar, baking powder, soda and salt together.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cut in margarine, dissolve yeast in warm water.',2, 21);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir into buttermilk and add to dry mixture.',3, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cover and chill.',4, 40);
INSERT INTO steps (descrizione, numero_step) VALUES ('Dip marshmallows in melted margarine',1, 91);
INSERT INTO steps (descrizione, numero_step) VALUES (' roll in candy.',2, 32);
INSERT INTO steps (descrizione, numero_step) VALUES ('Wrap a crescent triangle around each marshmallow, completely covering the marshmallow and square edges of dough tightly to seal.',3, 92);
INSERT INTO steps (descrizione, numero_step) VALUES ('Dip in margarine and place in a greased muffin tin.',4, 91);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 375° for 10 to 15 minutes',5, 3);
INSERT INTO steps (descrizione, numero_step) VALUES (' remove from pan.',6, 54);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix ingredients and spread into 2 greased pizza pans.',1, 13);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 350° for 15-20 minutes.',2, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix together and bake in 9 x 13-inch pan at 350° for 25 to 30 minutes.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Top should spring back when touched lightly',2, 19);
INSERT INTO steps (descrizione, numero_step) VALUES (' do not overbake.',3, 93);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cool completely, then spread with mint layer.',4, 84);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir the ingredients together and put in a greased and floured loaf pan.',1, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 425 degrees for 50 minutes.',2, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drizzle melted butter on top.',3, 94);
INSERT INTO steps (descrizione, numero_step) VALUES ('Melt margarine in skillet',1, 27);
INSERT INTO steps (descrizione, numero_step) VALUES (' saute onions and celery.',2, 95);
INSERT INTO steps (descrizione, numero_step) VALUES ('Remove from heat.',3, 54);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir in flour and curry powder.',4, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drain mushrooms and keep juice.',5, 15);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add water to juice to make 1/2 cup liquid.',6, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir liquid and soup into flour mixture',7, 6);
INSERT INTO steps (descrizione, numero_step) VALUES (' add mushrooms.',8, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cook until thick.',9, 29);
INSERT INTO steps (descrizione, numero_step) VALUES ('Arrange broccoli and cubed chicken in a large baking dish.',10, 96);
INSERT INTO steps (descrizione, numero_step) VALUES ('Spoon sauce over chicken.',11, 44);
INSERT INTO steps (descrizione, numero_step) VALUES ('Top with grated cheese.',12, 50);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake in a 350° oven for about 20 minutes or in microwave until cheese is melted.',13, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Sift flour, baking powder and salt together.',1, 97);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cream together butter and sugar.',2, 30);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add egg yolks and vanilla.',3, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Beat until light and fluffy.',4, 83);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix in sifted dry ingredients.',5, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Shape into 1-inch balls.',6, 98);
INSERT INTO steps (descrizione, numero_step) VALUES ('Push wooden spoon handle through center (twist).',7, 99);
INSERT INTO steps (descrizione, numero_step) VALUES ('Shape into rings.',8, 98);
INSERT INTO steps (descrizione, numero_step) VALUES ('Dip each cookie into candies.',9, 91);
INSERT INTO steps (descrizione, numero_step) VALUES ('Place on lightly greased baking sheets.',10, 0);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake in 375° oven for 10 to 12 minutes or until golden brown.',11, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cool on racks.',12, 84);
INSERT INTO steps (descrizione, numero_step) VALUES ('Serves 2 dozen.',13, 100);
INSERT INTO steps (descrizione, numero_step) VALUES ('Lightly brown beef in soup pot.',1, 24);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drain off excess fat.',2, 48);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir in tomatoes, tomato sauce, water, frozen vegetables, soup mix and sugar.',3, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bring to a boil.',4, 8);
INSERT INTO steps (descrizione, numero_step) VALUES ('Reduce heat and simmer for 20 minutes.',5, 69);
INSERT INTO steps (descrizione, numero_step) VALUES ('Serve.',6, 51);
INSERT INTO steps (descrizione, numero_step) VALUES ('Dice chicken.',1, 78);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix all ingredients together.',2, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Let sit overnight.',3, 20);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake 1 1/2 hours at 375°.',4, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('In a large bowl, combine cabbage, carrot, green pepper and onion or can use package of slaw mix purchased from store.',1, 4);
INSERT INTO steps (descrizione, numero_step) VALUES ('Heat oven to 500°.',1, 101);
INSERT INTO steps (descrizione, numero_step) VALUES ('Place fillets in single layer in baking dish, 13 1/2 x 9 x 2-inch.',2, 0);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir together remaining ingredients except pepper rings.',3, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Spoon over fillets.',4, 44);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake 5 to 8 minutes or until fish flakes easily with fork.',5, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Remove fillets to warm platter.',6, 54);
INSERT INTO steps (descrizione, numero_step) VALUES ('Garnish with green pepper rings.',7, 102);
INSERT INTO steps (descrizione, numero_step) VALUES ('Makes 4 to 6 servings.',8, 41);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix together all of sugar, salad oil, vinegar and water until sugar is dissolved.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour over beans and let stand overnight.',2, 82);
INSERT INTO steps (descrizione, numero_step) VALUES ('In a bowl, mix corns, sour cream, corn bread mix and melted margarine.',1, 103);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour into a greased 8 x 8 x 2-inch pan.',2, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 350° for 50 minutes.',3, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Brown beef with onion and seasonings and combine in a 1 1/2-quart casserole with soup, water and noodles.',1, 4);
INSERT INTO steps (descrizione, numero_step) VALUES ('Place cheese around edges.',2, 0);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 350° for 30 minutes.',3, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine all ingredients and cook uncovered over low heat until cabbage is crisp-tender, about 20 minutes.',1, 4);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix together and carefully add 1 pound lump crab meat.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix ahead of time and refrigerate so they will hold together better.',2, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix together cream cheese and mayonnaise.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Spread on to a large platter or two dinner plates.',2, 104);
INSERT INTO steps (descrizione, numero_step) VALUES ('Freeze for 15 minutes.',3, 52);
INSERT INTO steps (descrizione, numero_step) VALUES ('Spread taco sauce evenly on top.',4, 13);
INSERT INTO steps (descrizione, numero_step) VALUES ('Layer remaining ingredients in the written order.',5, 49);
INSERT INTO steps (descrizione, numero_step) VALUES ('Serve with tortilla chips.',6, 51);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cream together the butter and peanut butter.',1, 30);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add the remaining ingredients.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix and form into balls (best to mix with your hands) and chill several hours, even a day.',3, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix together.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Spread in a buttered pan.',2, 13);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake for 30 minutes at 275°.',3, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('While still hot, sift 1 box of powdered sugar into it.',4, 105);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drop by teaspoons on waxed paper.',5, 106);
INSERT INTO steps (descrizione, numero_step) VALUES ('Let dry.',6, 20);
INSERT INTO steps (descrizione, numero_step) VALUES ('If it seems set on bottom, turn over and let it continue to dry.',7, 107);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix together cake mix, 2 eggs and melted oleo.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Put in greased 9 x 13-inch pan.',2, 57);
INSERT INTO steps (descrizione, numero_step) VALUES ('Put chopped nuts on top of mixture.',3, 9);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix together 2 eggs, cream cheese and powdered sugar.',4, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add on top of first mixture.',5, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake 15 minutes at 325°, then bake 20 minutes at 350°.',6, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drain pineapple and reserve juice.',1, 25);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cut bananas in chunks like pineapple.',2, 21);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix all ingredients together in baking dish.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cover and bake at 350° for 2 1/2 hours.',2, 5);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake the last 45 minutes, uncovered, to brown top of chicken.',3, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cream the cream cheese',1, 30);
INSERT INTO steps (descrizione, numero_step) VALUES (' add the milk and beat smooth.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add lemon juice, pineapple and nuts.',3, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Beat well.',4, 83);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour into graham cracker crust and chill.',5, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Slice in small servings (very rich) and top with dollop of Cool Whip.',6, 76);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix all ingredients, form in small balls and roll in chopped peanuts.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Keep refrigerated.',2, 15);
INSERT INTO steps (descrizione, numero_step) VALUES ('Puree peaches in a blender.',1, 108);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add remaining ingredients.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Blend and pour in container and freeze.',3, 109);
INSERT INTO steps (descrizione, numero_step) VALUES ('*Can also use blueberries or cherries.',1, 110);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix ingredients and press 2/3 mixture in bottom of square baking dish.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('(A bowl that has the same diameter top and bottom may be used, 1 1/2 to 2-quart size.)',2, 79);
INSERT INTO steps (descrizione, numero_step) VALUES ('Sift together the flour, soda and salt',1, 97);
INSERT INTO steps (descrizione, numero_step) VALUES (' set aside.',2, 26);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine shortening and sugar in a bowl.',3, 4);
INSERT INTO steps (descrizione, numero_step) VALUES ('Beat until creamy.',4, 83);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add egg yolks',5, 28);
INSERT INTO steps (descrizione, numero_step) VALUES (' beat well.',6, 83);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine cocoa, water and vanilla to make 1 cup',7, 4);
INSERT INTO steps (descrizione, numero_step) VALUES (' mix well.',8, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add to batter.',9, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add flour mixture alternately with milk.',10, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Beat well after each addition',11, 83);
INSERT INTO steps (descrizione, numero_step) VALUES (' set aside.',12, 26);
INSERT INTO steps (descrizione, numero_step) VALUES ('Beat egg whites until stiff peaks form when beater is lifted.',13, 83);
INSERT INTO steps (descrizione, numero_step) VALUES ('Fold into batter.',14, 43);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake in two 9-inch greased cake pans at 375° for 30 minutes.',15, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine and cook first 6 ingredients.',1, 4);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bring to boil and boil 5 minutes',2, 8);
INSERT INTO steps (descrizione, numero_step) VALUES (' cool.',3, 84);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add sifted, dry ingredients to apple mixture.',4, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir and blend only.',5, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add nuts.',6, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour into greased and floured tube pan.',7, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake 1 hour at 350°.',8, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Serves 16.',9, 100);
INSERT INTO steps (descrizione, numero_step) VALUES ('Peel and dice potatoes',1, 111);
INSERT INTO steps (descrizione, numero_step) VALUES (' place in bowl of cold, salted water.',2, 0);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drain potatoes and dry on paper towels.',3, 112);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix 1/2 cup butter, onions, soup, sour cream and cheese',4, 1);
INSERT INTO steps (descrizione, numero_step) VALUES (' stir well.',5, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add potatoes to mixture and pour into a 2 1/2-quart casserole dish.',6, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Crush cornflakes, mix with remaining butter.',7, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Sprinkle cornflakes and butter on top of potato mixture.',8, 12);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 350° for 50 minutes.',9, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix vanilla wafer crumbs with butter.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir well together the sugar, syrup and water.',1, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Allow to boil without stirring until it forms a hard ball in cold water.',2, 53);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour this over stiffly beaten egg whites, beating constantly.',3, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cool',4, 84);
INSERT INTO steps (descrizione, numero_step) VALUES (' add vanilla and nuts.',5, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Beat until cool and thick enough to set.',6, 83);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour into a buttered platter or drop by teaspoons on waxed paper.',7, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix 1/2 cup of sugar and cinnamon.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Spread on apples.',2, 13);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix 1/4 cup sugar, flour, salt, cornflake crumbs and oleo.',3, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Spread mixture on apples.',4, 13);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix sausage and cheese together.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add Bisquick and mix thoroughly.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Roll into medium size balls.',3, 32);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 350° for 15 minutes or until golden brown.',4, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add enough liquid to chicken soup and consomme to make 4 cups of water.',1, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Season with salt and pepper.',2, 113);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cook at 350° for 1 hour.',3, 29);
INSERT INTO steps (descrizione, numero_step) VALUES ('Brown celery, onions and ground beef in butter.',1, 24);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add vinegar, lemon juice, brown sugar, mustard, salt, pepper catsup and water.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Simmer for 30 minutes.',3, 114);
INSERT INTO steps (descrizione, numero_step) VALUES ('In saucepan slowly stir the chicken broth into cornstarch.',1, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cook, stirring constantly, until slightly thickened.',2, 29);
INSERT INTO steps (descrizione, numero_step) VALUES ('Slowly pour in the well beaten egg',3, 2);
INSERT INTO steps (descrizione, numero_step) VALUES (' stir once gently.',4, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Remove from heat.',5, 54);
INSERT INTO steps (descrizione, numero_step) VALUES ('Garnish with sliced green onion.',6, 102);
INSERT INTO steps (descrizione, numero_step) VALUES ('Makes 4 servings.',7, 41);
INSERT INTO steps (descrizione, numero_step) VALUES ('Simmer all of the ingredients.',1, 114);
INSERT INTO steps (descrizione, numero_step) VALUES ('Strain into warmed mugs and top with a dash of nutmeg.',2, 115);
INSERT INTO steps (descrizione, numero_step) VALUES ('This recipe can be doubled many times, according to the number of guests present.',3, 110);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine first 4 ingredients in a small bowl, stir well and set aside.',1, 4);
INSERT INTO steps (descrizione, numero_step) VALUES ('Place chicken between 2 sheets of waxed paper or heavy duty plastic wrap, and flatten to 1/4-inch thickness, using meat mallet or rolling pin.',2, 116);
INSERT INTO steps (descrizione, numero_step) VALUES ('Coat grill rack with cooking spray',3, 117);
INSERT INTO steps (descrizione, numero_step) VALUES (' place on grill over coals.',4, 0);
INSERT INTO steps (descrizione, numero_step) VALUES ('Place chicken on rack and cook 4 minutes on each side, basting frequently with soy sauce mixture.',5, 29);
INSERT INTO steps (descrizione, numero_step) VALUES ('Transfer chicken to a serving platter and garnish with green onion, if desired.',6, 118);
INSERT INTO steps (descrizione, numero_step) VALUES ('Yields 4 servings, about 200 calories.',7, 7);
INSERT INTO steps (descrizione, numero_step) VALUES ('Saute together first 5	ingredients.',1, 95);
INSERT INTO steps (descrizione, numero_step) VALUES ('In a separate 9 x 12-inch pan, mix bread, eggs and milk.',2, 119);
INSERT INTO steps (descrizione, numero_step) VALUES ('Put pieces of bread into pan',3, 9);
INSERT INTO steps (descrizione, numero_step) VALUES (' add your vegetables, then your eggs.',4, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Place	in refrigerator overnight (at least 8 hours).',5, 0);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add Cheddar cheese before cooking.',6, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 350° for 1 hour.',7, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('In food processor or blender, grind cranberries, apple and orange.',1, 120);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix with sugar and set aside.',2, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Prepare gelatin according to package directions, using 1/4 cup less of cold water.',3, 85);
INSERT INTO steps (descrizione, numero_step) VALUES ('Chill until it begins to thicken.',4, 40);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add cranberry mixture and nuts.',5, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix well.',6, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour into a mold, if desired, or leave in a bowl and stir before serving.',7, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Chill until set.',8, 40);
INSERT INTO steps (descrizione, numero_step) VALUES ('Can even be made a day ahead.',9, 110);
INSERT INTO steps (descrizione, numero_step) VALUES ('Keeps well in refrigerator for a few days.',10, 90);
INSERT INTO steps (descrizione, numero_step) VALUES ('Put in a covered 1 1/2-quart dish.',1, 57);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake 1 hour at 350°.',2, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix cream cheese, margarine and sugar.',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add fruit and walnuts.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Whip cream and fold into fruit and cream cheese mixture.',3, 43);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour into round mold.',4, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Freeze 6 hours.',5, 52);
INSERT INTO steps (descrizione, numero_step) VALUES ('Remove from mold shortly before serving.',6, 54);
INSERT INTO steps (descrizione, numero_step) VALUES ('Makes 12 servings.',7, 41);
INSERT INTO steps (descrizione, numero_step) VALUES ('Dice tomatoes and peppers.',1, 78);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine all ingredients in top of double boiler for 30 minutes.',2, 4);
INSERT INTO steps (descrizione, numero_step) VALUES ('Serve hot over corn chips.',3, 51);
INSERT INTO steps (descrizione, numero_step) VALUES ('Sift first 5 ingredients together in a bowl.',1, 97);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix egg and milk together',2, 1);
INSERT INTO steps (descrizione, numero_step) VALUES (' add to dry ingredients.',3, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Beat until smooth.',4, 83);
INSERT INTO steps (descrizione, numero_step) VALUES ('Hold finger over bottom of a funnel',5, 121);
INSERT INTO steps (descrizione, numero_step) VALUES (' pour in some batter.',6, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Remove finger to let batter drop.',7, 54);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drop batter in a spiral motion into pan filled with 1 inch of hot oil (375°).',8, 106);
INSERT INTO steps (descrizione, numero_step) VALUES ('Fry until golden brown, turning once.',9, 47);
INSERT INTO steps (descrizione, numero_step) VALUES ('Remove from pan',10, 54);
INSERT INTO steps (descrizione, numero_step) VALUES (' drain on a paper towel.',11, 25);
INSERT INTO steps (descrizione, numero_step) VALUES ('Sprinkle with powdered sugar and serve hot.',12, 12);
INSERT INTO steps (descrizione, numero_step) VALUES ('In large bowl, put confectioners sugar, cocoa and chopped nuts.',1, 9);
INSERT INTO steps (descrizione, numero_step) VALUES ('In saucepan, put margarine and Velveeta.',2, 9);
INSERT INTO steps (descrizione, numero_step) VALUES ('Melt and add vanilla.',3, 27);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour hot mixture over sugar mixture.',4, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix quickly and pour into buttered cookie sheet.',5, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cool and cut into squares.',6, 84);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cook squash, onions and carrots until tender.',1, 29);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mash.',2, 122);
INSERT INTO steps (descrizione, numero_step) VALUES ('Melt butter in pan',3, 27);
INSERT INTO steps (descrizione, numero_step) VALUES (' stir in stuffing until all is coated.',4, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Drain all water from squash.',5, 25);
INSERT INTO steps (descrizione, numero_step) VALUES ('Stir in sour cream and soup.',6, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Place in a greased baking dish a layer of squash and a layer of stuffing.',7, 0);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 350° for 35 minutes.',8, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine softened cream and Cheddar cheeses.',1, 4);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add chopped up items.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix and add liquids last.',3, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix well.',4, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Roll into ball and cover with chopped nuts.',5, 32);
INSERT INTO steps (descrizione, numero_step) VALUES ('Dissolve jello in boiling water',1, 42);
INSERT INTO steps (descrizione, numero_step) VALUES (' add sugar.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Blend in the cream cheese with a fork.',3, 109);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add can of crushed pineapple and apricot baby food.',4, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Refrigerate.',5, 14);
INSERT INTO steps (descrizione, numero_step) VALUES ('Chill can of milk.',6, 110);
INSERT INTO steps (descrizione, numero_step) VALUES ('When jello starts to set, take milk out of the refrigerator and beat until stiff.',7, 123);
INSERT INTO steps (descrizione, numero_step) VALUES ('Fold partially set jello into cream.',8, 43);
INSERT INTO steps (descrizione, numero_step) VALUES ('Chopped nuts can be used for garnish.',9, 110);
INSERT INTO steps (descrizione, numero_step) VALUES ('This is a large salad',10, 124);
INSERT INTO steps (descrizione, numero_step) VALUES (' could fill a 2-quart mold or 2 (1-quart) molds.',11, 125);
INSERT INTO steps (descrizione, numero_step) VALUES ('Serves about 12.',12, 100);
INSERT INTO steps (descrizione, numero_step) VALUES ('Have all ingredients at room temperature.',1, 126);
INSERT INTO steps (descrizione, numero_step) VALUES ('Hand stir all dry ingredients together.',2, 6);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add eggs and stir.',3, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add butter and Crisco and stir.',4, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add milk and stir.',5, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Put batter in mixer and beat at high speed until well blended.',6, 9);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add 1 to 2 teaspoons of your favorite flavoring and mix well.',7, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour batter into greased and floured tube pan.',8, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Place in cold oven.',9, 0);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 325° for 1 hour and 20 to 30 minutes.',10, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Use greased 9 x 13-inch pan or Bundt pan.',1, 39);
INSERT INTO steps (descrizione, numero_step) VALUES ('Melt butter',2, 27);
INSERT INTO steps (descrizione, numero_step) VALUES (' add brown sugar, pudding, milk and cinnamon.',3, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Break up 1 loaf into round balls',4, 127);
INSERT INTO steps (descrizione, numero_step) VALUES (' place in pan.',5, 0);
INSERT INTO steps (descrizione, numero_step) VALUES ('Pour mixture over and break second loaf over this.',6, 2);
INSERT INTO steps (descrizione, numero_step) VALUES ('Rise 2 1/2 to 3 hours.',7, 128);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake 30 minutes at 350°',8, 3);
INSERT INTO steps (descrizione, numero_step) VALUES (' turn out immediately to cool.',9, 129);
INSERT INTO steps (descrizione, numero_step) VALUES ('Unroll crescent rolls',1, 73);
INSERT INTO steps (descrizione, numero_step) VALUES (' add cooked chicken and grated cheese.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Wrap roll over chicken and cheese',3, 92);
INSERT INTO steps (descrizione, numero_step) VALUES (' pinch sides together.',4, 130);
INSERT INTO steps (descrizione, numero_step) VALUES ('Spray a 1-quart casserole dish with Pam.',1, 131);
INSERT INTO steps (descrizione, numero_step) VALUES ('Layer rice and meat, diced onion and grated cheese.',2, 49);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake at 350° for 25 to 30 minutes.',3, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cook onions and bell pepper in oil until onions are transparent.',1, 29);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add beef and cook until brown.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix all ingredients together.',3, 1);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake in 350° oven for 45 minutes, or after mixing together, pour in crock-pot and cook 6 to 10 hours on low.',4, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Saute onion in 2 tablespoons shortening.',1, 95);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add carrots, water and bouillon cubes.',2, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Simmer 5 minutes.',3, 114);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine next 6 ingredients.',4, 4);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add to vegetable mixture and cook until clear.',5, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Add pepper, pineapple and chicken.',6, 28);
INSERT INTO steps (descrizione, numero_step) VALUES ('Cover and simmer 5 minutes or until heated through.',7, 5);
INSERT INTO steps (descrizione, numero_step) VALUES ('Serve with rice or angel hair noodles.',8, 51);
INSERT INTO steps (descrizione, numero_step) VALUES ('Serves 6 people.',9, 100);
INSERT INTO steps (descrizione, numero_step) VALUES ('Combine all ingredients.',1, 4);
INSERT INTO steps (descrizione, numero_step) VALUES ('Chill overnight.',2, 40);
INSERT INTO steps (descrizione, numero_step) VALUES ('Yields 4 to 6 servings.',3, 7);
INSERT INTO steps (descrizione, numero_step) VALUES ('Mix together and roll into balls',1, 1);
INSERT INTO steps (descrizione, numero_step) VALUES (' flatten with fork.',2, 116);
INSERT INTO steps (descrizione, numero_step) VALUES ('Bake on ungreased cookie sheet.',3, 3);
INSERT INTO steps (descrizione, numero_step) VALUES ('Makes 2 dozen.',4, 41);
