
DROP TABLE IF EXISTS instruments;
CREATE TABLE instruments(
id SERIAL PRIMARY KEY,
name VARCHAR NOT NULL
);
INSERT INTO instruments VALUES (0,'clusters');
INSERT INTO instruments VALUES (1,'paper');
INSERT INTO instruments VALUES (2,'bottom');
INSERT INTO instruments VALUES (3,'casserole');
INSERT INTO instruments VALUES (4,'box');
INSERT INTO instruments VALUES (5,'inch');
INSERT INTO instruments VALUES (6,'refrigerator');
INSERT INTO instruments VALUES (7,'fork');
INSERT INTO instruments VALUES (8,'paper towel');
INSERT INTO instruments VALUES (9,'kettle');
INSERT INTO instruments VALUES (10,'skillet');
INSERT INTO instruments VALUES (11,'mold');
INSERT INTO instruments VALUES (12,'sheet');
INSERT INTO instruments VALUES (13,'freezer');
INSERT INTO instruments VALUES (14,'boiler');
INSERT INTO instruments VALUES (15,'way');
INSERT INTO instruments VALUES (16,'microwave');
INSERT INTO instruments VALUES (17,'saucepan');
INSERT INTO instruments VALUES (18,'hand');
INSERT INTO instruments VALUES (19,'processor');
INSERT INTO instruments VALUES (20,'ingredients');
INSERT INTO instruments VALUES (21,'oven');
INSERT INTO instruments VALUES (22,'game');
INSERT INTO instruments VALUES (23,'world');
INSERT INTO instruments VALUES (24,'board');
INSERT INTO instruments VALUES (25,'cutter');
INSERT INTO instruments VALUES (26,'center');
INSERT INTO instruments VALUES (27,'rack');
INSERT INTO instruments VALUES (28,'squares');
INSERT INTO instruments VALUES (29,'tablespoons');
INSERT INTO instruments VALUES (30,'place');
INSERT INTO instruments VALUES (31,'tin');
INSERT INTO instruments VALUES (32,'pans');
INSERT INTO instruments VALUES (33,'layer');
INSERT INTO instruments VALUES (34,'racks');
INSERT INTO instruments VALUES (35,'pot');
INSERT INTO instruments VALUES (36,'store');
INSERT INTO instruments VALUES (37,'time');
INSERT INTO instruments VALUES (38,'order');
INSERT INTO instruments VALUES (39,'hands');
INSERT INTO instruments VALUES (40,'chill');
INSERT INTO instruments VALUES (41,'servings');
INSERT INTO instruments VALUES (42,'dollop');
INSERT INTO instruments VALUES (43,'blender');
INSERT INTO instruments VALUES (44,'container');
INSERT INTO instruments VALUES (45,'inch pans');
INSERT INTO instruments VALUES (46,'paper towels');
INSERT INTO instruments VALUES (47,'platter');
INSERT INTO instruments VALUES (48,'mugs');
INSERT INTO instruments VALUES (49,'guests');
INSERT INTO instruments VALUES (50,'mallet');
INSERT INTO instruments VALUES (51,'grill');
INSERT INTO instruments VALUES (52,'side');
INSERT INTO instruments VALUES (53,'funnel');
INSERT INTO instruments VALUES (54,'motion');
INSERT INTO instruments VALUES (55,'ball');
INSERT INTO instruments VALUES (56,'baby');
INSERT INTO instruments VALUES (57,'hair');
INSERT INTO instruments VALUES (58,'towel');
INSERT INTO instruments VALUES (59,'cutters');
INSERT INTO instruments VALUES (60,'pitcher');
INSERT INTO instruments VALUES (61,'spoon');
INSERT INTO instruments VALUES (62,'% power');
INSERT INTO instruments VALUES (63,'fork blend');
INSERT INTO instruments VALUES (64,'kind');
INSERT INTO instruments VALUES (65,'star tip');
INSERT INTO instruments VALUES (66,'fry');
INSERT INTO instruments VALUES (67,'sides');
INSERT INTO instruments VALUES (68,'inch casserole');
INSERT INTO instruments VALUES (69,'shelf');
INSERT INTO instruments VALUES (70,'beater');
INSERT INTO instruments VALUES (71,'meringue');
INSERT INTO instruments VALUES (72,'tsp');
INSERT INTO instruments VALUES (73,'heat');
INSERT INTO instruments VALUES (74,'glass');
INSERT INTO instruments VALUES (75,'spatula');
INSERT INTO instruments VALUES (76,'tins');
INSERT INTO instruments VALUES (77,'sherbert');
INSERT INTO instruments VALUES (78,'cornflake');
INSERT INTO instruments VALUES (79,'shape');
INSERT INTO instruments VALUES (80,'knife');
INSERT INTO instruments VALUES (81,'plate');
INSERT INTO instruments VALUES (82,'cook');
INSERT INTO instruments VALUES (83,'baking sheet');
INSERT INTO instruments VALUES (84,'brownies');
INSERT INTO instruments VALUES (85,'inch squares');
INSERT INTO instruments VALUES (86,'mein');
INSERT INTO instruments VALUES (87,'thermometer');
INSERT INTO instruments VALUES (88,'cooking vessel');
INSERT INTO instruments VALUES (89,'tube');
INSERT INTO instruments VALUES (90,'surface');
INSERT INTO instruments VALUES (91,'freezer bags');
INSERT INTO instruments VALUES (92,'whisk');
INSERT INTO instruments VALUES (93,'cheesecloth');
INSERT INTO instruments VALUES (94,'rubber spatula');
INSERT INTO instruments VALUES (95,'dishes');
INSERT INTO instruments VALUES (96,'marinade');
INSERT INTO instruments VALUES (97,'favorite');
INSERT INTO instruments VALUES (98,'diameter');
INSERT INTO instruments VALUES (99,'menu');
INSERT INTO instruments VALUES (100,'restaurant');
INSERT INTO instruments VALUES (101,'steam');
INSERT INTO instruments VALUES (102,'inch tube');
INSERT INTO instruments VALUES (103,'tartar');
INSERT INTO instruments VALUES (104,'sifter');
INSERT INTO instruments VALUES (105,'quart');
INSERT INTO instruments VALUES (106,'minute');
INSERT INTO instruments VALUES (107,'accordance');
INSERT INTO instruments VALUES (108,'directions');
INSERT INTO instruments VALUES (109,'quarters');
INSERT INTO instruments VALUES (110,'inch plate');
INSERT INTO instruments VALUES (111,'wire rack');
INSERT INTO instruments VALUES (112,'mug');
INSERT INTO instruments VALUES (113,'lid');
INSERT INTO instruments VALUES (114,'strands');
INSERT INTO instruments VALUES (115,'quart casserole');
INSERT INTO instruments VALUES (116,'o');
INSERT INTO instruments VALUES (117,'confectioners');
INSERT INTO instruments VALUES (118,'block');
INSERT INTO instruments VALUES (119,'fruits');
INSERT INTO instruments VALUES (120,'degree oven');
INSERT INTO instruments VALUES (121,'fridge');
INSERT INTO instruments VALUES (122,'meatballs');
INSERT INTO instruments VALUES (123,'preference');
INSERT INTO instruments VALUES (124,'part');
INSERT INTO instruments VALUES (125,'burgers');
INSERT INTO instruments VALUES (126,'foil');
INSERT INTO instruments VALUES (127,'stem');
INSERT INTO instruments VALUES (128,'fingernail');
INSERT INTO instruments VALUES (129,'counter');
INSERT INTO instruments VALUES (130,'metal box');
INSERT INTO instruments VALUES (131,'metal');
INSERT INTO instruments VALUES (132,'nonstick frypan');
INSERT INTO instruments VALUES (133,'bulk');
INSERT INTO instruments VALUES (134,'glass casserole');
INSERT INTO instruments VALUES (135,'weather');
INSERT INTO instruments VALUES (136,'hole');
INSERT INTO instruments VALUES (137,'nonstick skillet');
INSERT INTO instruments VALUES (138,'hour');
INSERT INTO instruments VALUES (139,'canning jars');
INSERT INTO instruments VALUES (140,'minutes');
INSERT INTO instruments VALUES (141,'nonstick');
INSERT INTO instruments VALUES (142,'row');
INSERT INTO instruments VALUES (143,'depression');
INSERT INTO instruments VALUES (144,'oblong');
INSERT INTO instruments VALUES (145,'circle');
INSERT INTO instruments VALUES (146,'cooker');
INSERT INTO instruments VALUES (147,'middle');
INSERT INTO instruments VALUES (148,'jars');
INSERT INTO instruments VALUES (149,'mush');
INSERT INTO instruments VALUES (150,'parchment paper');
INSERT INTO instruments VALUES (151,'fingers');
INSERT INTO instruments VALUES (152,'fingertips');
INSERT INTO instruments VALUES (153,'inch fingers');
INSERT INTO instruments VALUES (154,'layers');
INSERT INTO instruments VALUES (155,'stove');
INSERT INTO instruments VALUES (156,'range');
INSERT INTO instruments VALUES (157,'press');
INSERT INTO instruments VALUES (158,'shapes');
INSERT INTO instruments VALUES (159,'cutlet');
INSERT INTO instruments VALUES (160,'edges');
INSERT INTO instruments VALUES (161,'crescent');
INSERT INTO instruments VALUES (162,'custard');
INSERT INTO instruments VALUES (163,'log cabin');
INSERT INTO instruments VALUES (164,'glass measure');
INSERT INTO instruments VALUES (165,'saute');
INSERT INTO instruments VALUES (166,'position');
INSERT INTO instruments VALUES (167,'cast iron skillet');
INSERT INTO instruments VALUES (168,'batches');
INSERT INTO instruments VALUES (169,'cottage');
INSERT INTO instruments VALUES (170,'texture');
INSERT INTO instruments VALUES (171,'colander');
INSERT INTO instruments VALUES (172,'wire whisk');
INSERT INTO instruments VALUES (173,'cob');
INSERT INTO instruments VALUES (174,'bitterness');
INSERT INTO instruments VALUES (175,'knives');
INSERT INTO instruments VALUES (176,'tray');
INSERT INTO instruments VALUES (177,'bottoms');
INSERT INTO instruments VALUES (178,'remainder');
INSERT INTO instruments VALUES (179,'angel');
INSERT INTO instruments VALUES (180,'drugstore wrap');
INSERT INTO instruments VALUES (181,'paper liners');
INSERT INTO instruments VALUES (182,'centers');
INSERT INTO instruments VALUES (183,'thumb');
INSERT INTO instruments VALUES (184,'square');
INSERT INTO instruments VALUES (185,'stone');
INSERT INTO instruments VALUES (186,'cheeses');
INSERT INTO instruments VALUES (187,'fondant');
INSERT INTO instruments VALUES (188,'refrigerate');
INSERT INTO instruments VALUES (189,'day');
INSERT INTO instruments VALUES (190,'party hotdogs');
INSERT INTO instruments VALUES (191,'rows');
INSERT INTO instruments VALUES (192,'recipe');
INSERT INTO instruments VALUES (193,'coal');
INSERT INTO instruments VALUES (194,'dredge');
INSERT INTO instruments VALUES (195,'outside');
INSERT INTO instruments VALUES (196,'crockpot');
INSERT INTO instruments VALUES (197,'hours');
INSERT INTO instruments VALUES (198,'bath');
INSERT INTO instruments VALUES (199,'blender container');
INSERT INTO instruments VALUES (200,'ounces');
INSERT INTO instruments VALUES (201,'dome');
INSERT INTO instruments VALUES (202,'chair');
INSERT INTO instruments VALUES (203,'wire racks');
INSERT INTO instruments VALUES (204,'exception');
INSERT INTO instruments VALUES (205,'wok');
INSERT INTO instruments VALUES (206,'toothpick');
INSERT INTO instruments VALUES (207,'breads');
INSERT INTO instruments VALUES (208,'pyrex');
INSERT INTO instruments VALUES (209,'aluminum foil');
INSERT INTO instruments VALUES (210,'plastic wrap');
INSERT INTO instruments VALUES (211,'inch rectangle');
INSERT INTO instruments VALUES (212,'quarts');
INSERT INTO instruments VALUES (213,'diamond');
INSERT INTO instruments VALUES (214,'advance');
INSERT INTO instruments VALUES (215,'vegies');
INSERT INTO instruments VALUES (216,'hand beater');
INSERT INTO instruments VALUES (217,'juices');
INSERT INTO instruments VALUES (218,'burner');
INSERT INTO instruments VALUES (219,'inch skillet');
INSERT INTO instruments VALUES (220,'saucepot');
INSERT INTO instruments VALUES (221,'drain');
INSERT INTO instruments VALUES (222,'crosswise');
INSERT INTO instruments VALUES (223,'choice');
INSERT INTO instruments VALUES (224,'floured board');
INSERT INTO instruments VALUES (225,'baking pans');
INSERT INTO instruments VALUES (226,'crepe');
INSERT INTO instruments VALUES (227,'wrap');
INSERT INTO instruments VALUES (228,'type');
INSERT INTO instruments VALUES (229,'pin');
INSERT INTO instruments VALUES (230,'leg');
INSERT INTO instruments VALUES (231,'triangle');
INSERT INTO instruments VALUES (232,'cereals');
INSERT INTO instruments VALUES (233,'rest');
INSERT INTO instruments VALUES (234,'cover');
INSERT INTO instruments VALUES (235,'logs');
INSERT INTO instruments VALUES (236,'soups');
INSERT INTO instruments VALUES (237,'awareness');
INSERT INTO instruments VALUES (238,'life');
INSERT INTO instruments VALUES (239,'grudges');
INSERT INTO instruments VALUES (240,'cheerfulness');
INSERT INTO instruments VALUES (241,'tears');
INSERT INTO instruments VALUES (242,'helpings');
INSERT INTO instruments VALUES (243,'bags');
INSERT INTO instruments VALUES (244,'countertop');
INSERT INTO instruments VALUES (245,'consistency');
INSERT INTO instruments VALUES (246,'stir');
INSERT INTO instruments VALUES (247,'mixes');
INSERT INTO instruments VALUES (248,'stand');
INSERT INTO instruments VALUES (249,'solids');
INSERT INTO instruments VALUES (250,'crystal');
INSERT INTO instruments VALUES (251,'griddle');
INSERT INTO instruments VALUES (252,'combination');
INSERT INTO instruments VALUES (253,'inch circles');
INSERT INTO instruments VALUES (254,'brush');
INSERT INTO instruments VALUES (255,'triangles');
INSERT INTO instruments VALUES (256,'flower pot');
INSERT INTO instruments VALUES (257,'brown');
INSERT INTO instruments VALUES (258,'plates');
INSERT INTO instruments VALUES (259,'forms');
INSERT INTO instruments VALUES (260,'toppings');
INSERT INTO instruments VALUES (261,'toaster');
INSERT INTO instruments VALUES (262,'sesame');
INSERT INTO instruments VALUES (263,'containers');
INSERT INTO instruments VALUES (264,'metal lids');
INSERT INTO instruments VALUES (265,'bands');
INSERT INTO instruments VALUES (266,'penne');
INSERT INTO instruments VALUES (267,'age');
INSERT INTO instruments VALUES (268,'cooking time');
INSERT INTO instruments VALUES (269,'power level');
INSERT INTO instruments VALUES (270,'level');
INSERT INTO instruments VALUES (271,'door');
INSERT INTO instruments VALUES (272,'seafood');
INSERT INTO instruments VALUES (273,'inch cutter');
INSERT INTO instruments VALUES (274,'finger');
INSERT INTO instruments VALUES (275,'rinses');
INSERT INTO instruments VALUES (276,'quart saucepan');
INSERT INTO instruments VALUES (277,'steel');
INSERT INTO instruments VALUES (278,'dessert');
INSERT INTO instruments VALUES (279,'broiler rack');
INSERT INTO instruments VALUES (280,'roaster');
INSERT INTO instruments VALUES (281,'dust');
INSERT INTO instruments VALUES (282,'tops');
INSERT INTO instruments VALUES (283,'cracks');
INSERT INTO instruments VALUES (284,'sections');
INSERT INTO instruments VALUES (285,'glass plate');
INSERT INTO instruments VALUES (286,'trays');
INSERT INTO instruments VALUES (287,'beverages');
INSERT INTO instruments VALUES (288,'decoration');
INSERT INTO instruments VALUES (289,'turns');
INSERT INTO instruments VALUES (290,'spring form');
INSERT INTO instruments VALUES (291,'angle');
INSERT INTO instruments VALUES (292,'chickpea');
INSERT INTO instruments VALUES (293,'pumpernickel');
INSERT INTO instruments VALUES (294,'sandwiches');
INSERT INTO instruments VALUES (295,'circles');
INSERT INTO instruments VALUES (296,'iron skillet');
INSERT INTO instruments VALUES (297,'back');
INSERT INTO instruments VALUES (298,'freeze');
INSERT INTO instruments VALUES (299,'pyrex dishes');
INSERT INTO instruments VALUES (300,'toothpicks');
INSERT INTO instruments VALUES (301,'slivers');
INSERT INTO instruments VALUES (302,'stream');
INSERT INTO instruments VALUES (303,'inch circle');
INSERT INTO instruments VALUES (304,'stocks');
INSERT INTO instruments VALUES (305,'leftover');
INSERT INTO instruments VALUES (306,'baking time');
INSERT INTO instruments VALUES (307,'color');
INSERT INTO instruments VALUES (308,'thirds');
INSERT INTO instruments VALUES (309,'pan(s');
INSERT INTO instruments VALUES (310,'tube pans');
INSERT INTO instruments VALUES (311,'pressure cooker');
INSERT INTO instruments VALUES (312,'party');
INSERT INTO instruments VALUES (313,'nut');
INSERT INTO instruments VALUES (314,'piles');
INSERT INTO instruments VALUES (315,'bowls');
INSERT INTO instruments VALUES (316,'ovenproof skillet');
INSERT INTO instruments VALUES (317,'wire');
INSERT INTO instruments VALUES (318,'strainer');
INSERT INTO instruments VALUES (319,'handle');
INSERT INTO instruments VALUES (320,'volume');
INSERT INTO instruments VALUES (321,'jackets');
INSERT INTO instruments VALUES (322,'fist');
INSERT INTO instruments VALUES (323,'inches foil');
INSERT INTO instruments VALUES (324,'blueberry');
INSERT INTO instruments VALUES (325,'saltwater');
INSERT INTO instruments VALUES (326,'peaks');
INSERT INTO instruments VALUES (327,'quart mold');
INSERT INTO instruments VALUES (328,'inch sheet');
INSERT INTO instruments VALUES (329,'items');
INSERT INTO instruments VALUES (330,'dice');
INSERT INTO instruments VALUES (331,'%');
INSERT INTO instruments VALUES (332,'bamboo skewer');
INSERT INTO instruments VALUES (333,'little');
INSERT INTO instruments VALUES (334,'inches');
INSERT INTO instruments VALUES (335,'room');
INSERT INTO instruments VALUES (336,'quart stockpot');
INSERT INTO instruments VALUES (337,'tenderizer');
INSERT INTO instruments VALUES (338,'drop');
INSERT INTO instruments VALUES (339,'packet');
INSERT INTO instruments VALUES (340,'curves');
INSERT INTO instruments VALUES (341,'sunflower');
INSERT INTO instruments VALUES (342,'label');
INSERT INTO instruments VALUES (343,'rectangle');
INSERT INTO instruments VALUES (344,'casserole pans');
INSERT INTO instruments VALUES (345,'fourths');
INSERT INTO instruments VALUES (346,'scissors');
INSERT INTO instruments VALUES (347,'instant');
INSERT INTO instruments VALUES (348,'tub');
INSERT INTO instruments VALUES (349,'inch tins');
INSERT INTO instruments VALUES (350,'line bottom');
INSERT INTO instruments VALUES (351,'lids');
INSERT INTO instruments VALUES (352,'thaw');
INSERT INTO instruments VALUES (353,'pear');
INSERT INTO instruments VALUES (354,'oval');
INSERT INTO instruments VALUES (355,'sack');
INSERT INTO instruments VALUES (356,'microwave oven');
INSERT INTO instruments VALUES (357,'x');
INSERT INTO instruments VALUES (358,'dessert dishes');
INSERT INTO instruments VALUES (359,'eye dropper');
INSERT INTO instruments VALUES (360,'purpose');
INSERT INTO instruments VALUES (361,'end');
INSERT INTO instruments VALUES (362,'up');
INSERT INTO instruments VALUES (363,'baking skillet');
INSERT INTO instruments VALUES (364,'caps');
INSERT INTO instruments VALUES (365,'simmer');
INSERT INTO instruments VALUES (366,'sugars');
INSERT INTO instruments VALUES (367,'disc');
INSERT INTO instruments VALUES (368,'process');
INSERT INTO instruments VALUES (369,'mini pans');
INSERT INTO instruments VALUES (370,'beaters');
INSERT INTO instruments VALUES (371,'press ingredients');
INSERT INTO instruments VALUES (372,'boil');
INSERT INTO instruments VALUES (373,'eggbeater');
INSERT INTO instruments VALUES (374,'sprinkles');
INSERT INTO instruments VALUES (375,'button');
INSERT INTO instruments VALUES (376,'touch');
INSERT INTO instruments VALUES (377,'grinder');
INSERT INTO instruments VALUES (378,'seal');
INSERT INTO instruments VALUES (379,'number');
INSERT INTO instruments VALUES (380,'fries');
INSERT INTO instruments VALUES (381,'summer');
INSERT INTO instruments VALUES (382,'winter');
INSERT INTO instruments VALUES (383,'skewers');
INSERT INTO instruments VALUES (384,'ramekin dishes');
INSERT INTO instruments VALUES (385,'days');
INSERT INTO instruments VALUES (386,'baker');
INSERT INTO instruments VALUES (387,'peeler');
INSERT INTO instruments VALUES (388,'rubber gloves');
INSERT INTO instruments VALUES (389,'linen towel');
INSERT INTO instruments VALUES (390,'log');
INSERT INTO instruments VALUES (391,'recipes');
INSERT INTO instruments VALUES (392,'basket');
INSERT INTO instruments VALUES (393,'ziploc bags');
INSERT INTO instruments VALUES (394,'plastic');
INSERT INTO instruments VALUES (395,'enamel');
INSERT INTO instruments VALUES (396,'bother');
INSERT INTO instruments VALUES (397,'mini');
INSERT INTO instruments VALUES (398,'decorations');
INSERT INTO instruments VALUES (399,'9x13 inch');
INSERT INTO instruments VALUES (400,'brand');
INSERT INTO instruments VALUES (401,'chopper');
INSERT INTO instruments VALUES (402,'flavorings');
INSERT INTO instruments VALUES (403,'air popper');
INSERT INTO instruments VALUES (404,'grocery');
INSERT INTO instruments VALUES (405,'glass container');
INSERT INTO instruments VALUES (406,'toy shovel');
INSERT INTO instruments VALUES (407,'sun');
INSERT INTO instruments VALUES (408,'bathtub');
INSERT INTO instruments VALUES (409,'waffle pizzelle maker');
INSERT INTO instruments VALUES (410,'cupcake tins');
INSERT INTO instruments VALUES (411,'coat');
INSERT INTO instruments VALUES (412,'utility');
INSERT INTO instruments VALUES (413,'tennis');
INSERT INTO instruments VALUES (414,'shalloww');
INSERT INTO instruments VALUES (415,'souffle');
INSERT INTO instruments VALUES (416,'kernel');
INSERT INTO instruments VALUES (417,'9x13');
INSERT INTO instruments VALUES (418,'milligrams sodium');
