
DROP TABLE IF EXISTS actions;
CREATE TABLE actions(
id SERIAL PRIMARY KEY,
name VARCHAR NOT NULL
);
INSERT INTO actions VALUES (0,'place');
INSERT INTO actions VALUES (1,'mix');
INSERT INTO actions VALUES (2,'pour');
INSERT INTO actions VALUES (3,'bake');
INSERT INTO actions VALUES (4,'combine');
INSERT INTO actions VALUES (5,'cover');
INSERT INTO actions VALUES (6,'stir');
INSERT INTO actions VALUES (7,'yields');
INSERT INTO actions VALUES (8,'boil');
INSERT INTO actions VALUES (9,'put');
INSERT INTO actions VALUES (10,'level');
INSERT INTO actions VALUES (11,'make');
INSERT INTO actions VALUES (12,'sprinkle');
INSERT INTO actions VALUES (13,'spread');
INSERT INTO actions VALUES (14,'refrigerate');
INSERT INTO actions VALUES (15,'keep');
INSERT INTO actions VALUES (16,'wash');
INSERT INTO actions VALUES (17,'prick');
INSERT INTO actions VALUES (18,'microwave');
INSERT INTO actions VALUES (19,'should');
INSERT INTO actions VALUES (20,'let');
INSERT INTO actions VALUES (21,'cut');
INSERT INTO actions VALUES (22,'scoop out');
INSERT INTO actions VALUES (23,'discard');
INSERT INTO actions VALUES (24,'brown');
INSERT INTO actions VALUES (25,'drain');
INSERT INTO actions VALUES (26,'set');
INSERT INTO actions VALUES (27,'melt');
INSERT INTO actions VALUES (28,'add');
INSERT INTO actions VALUES (29,'cook');
INSERT INTO actions VALUES (30,'cream');
INSERT INTO actions VALUES (31,'dot');
INSERT INTO actions VALUES (32,'roll');
INSERT INTO actions VALUES (33,'salt');
INSERT INTO actions VALUES (34,'uncover');
INSERT INTO actions VALUES (35,'serve over');
INSERT INTO actions VALUES (36,'empty');
INSERT INTO actions VALUES (37,'squeeze');
INSERT INTO actions VALUES (38,'chop');
INSERT INTO actions VALUES (39,'use');
INSERT INTO actions VALUES (40,'chill');
INSERT INTO actions VALUES (41,'makes');
INSERT INTO actions VALUES (42,'dissolve');
INSERT INTO actions VALUES (43,'fold');
INSERT INTO actions VALUES (44,'spoon');
INSERT INTO actions VALUES (45,'paraffin');
INSERT INTO actions VALUES (46,'clean');
INSERT INTO actions VALUES (47,'fry');
INSERT INTO actions VALUES (48,'drain off');
INSERT INTO actions VALUES (49,'layer');
INSERT INTO actions VALUES (50,'top');
INSERT INTO actions VALUES (51,'serve');
INSERT INTO actions VALUES (52,'freeze');
INSERT INTO actions VALUES (53,'allow');
INSERT INTO actions VALUES (54,'remove');
INSERT INTO actions VALUES (55,'continue');
INSERT INTO actions VALUES (56,'trim off');
INSERT INTO actions VALUES (57,'put in');
INSERT INTO actions VALUES (58,'scrape');
INSERT INTO actions VALUES (59,'last');
INSERT INTO actions VALUES (60,'buy');
INSERT INTO actions VALUES (61,'marinates');
INSERT INTO actions VALUES (62,'press');
INSERT INTO actions VALUES (63,'says');
INSERT INTO actions VALUES (64,'knows');
INSERT INTO actions VALUES (65,'are');
INSERT INTO actions VALUES (66,'pour off');
INSERT INTO actions VALUES (67,'butter');
INSERT INTO actions VALUES (68,'heat');
INSERT INTO actions VALUES (69,'reduce');
INSERT INTO actions VALUES (70,'batter');
INSERT INTO actions VALUES (71,'roll out');
INSERT INTO actions VALUES (72,'brush');
INSERT INTO actions VALUES (73,'rolls');
INSERT INTO actions VALUES (74,'yield');
INSERT INTO actions VALUES (75,'punch');
INSERT INTO actions VALUES (76,'slice');
INSERT INTO actions VALUES (77,'leave');
INSERT INTO actions VALUES (78,'dice');
INSERT INTO actions VALUES (79,'may');
INSERT INTO actions VALUES (80,'double');
INSERT INTO actions VALUES (81,'grease');
INSERT INTO actions VALUES (82,'pour over');
INSERT INTO actions VALUES (83,'beat');
INSERT INTO actions VALUES (84,'cool');
INSERT INTO actions VALUES (85,'prepare');
INSERT INTO actions VALUES (86,'well');
INSERT INTO actions VALUES (87,'marinate');
INSERT INTO actions VALUES (88,'parboil');
INSERT INTO actions VALUES (89,'seal');
INSERT INTO actions VALUES (90,'keeps');
INSERT INTO actions VALUES (91,'dip');
INSERT INTO actions VALUES (92,'wrap');
INSERT INTO actions VALUES (93,'overbake');
INSERT INTO actions VALUES (94,'drizzle');
INSERT INTO actions VALUES (95,'saute');
INSERT INTO actions VALUES (96,'arrange');
INSERT INTO actions VALUES (97,'sift');
INSERT INTO actions VALUES (98,'shape');
INSERT INTO actions VALUES (99,'push');
INSERT INTO actions VALUES (100,'serves');
INSERT INTO actions VALUES (101,'oven heat');
INSERT INTO actions VALUES (102,'garnish');
INSERT INTO actions VALUES (103,'bowl');
INSERT INTO actions VALUES (104,'spread on');
INSERT INTO actions VALUES (105,'still');
INSERT INTO actions VALUES (106,'drop');
INSERT INTO actions VALUES (107,'seems');
INSERT INTO actions VALUES (108,'puree');
INSERT INTO actions VALUES (109,'blend');
INSERT INTO actions VALUES (110,'can');
INSERT INTO actions VALUES (111,'peel');
INSERT INTO actions VALUES (112,'dry');
INSERT INTO actions VALUES (113,'season');
INSERT INTO actions VALUES (114,'simmer');
INSERT INTO actions VALUES (115,'strain');
INSERT INTO actions VALUES (116,'flatten');
INSERT INTO actions VALUES (117,'coat');
INSERT INTO actions VALUES (118,'transfer');
INSERT INTO actions VALUES (119,'separate');
INSERT INTO actions VALUES (120,'grind');
INSERT INTO actions VALUES (121,'hold');
INSERT INTO actions VALUES (122,'mash');
INSERT INTO actions VALUES (123,'starts');
INSERT INTO actions VALUES (124,'is');
INSERT INTO actions VALUES (125,'could');
INSERT INTO actions VALUES (126,'have');
INSERT INTO actions VALUES (127,'break up');
INSERT INTO actions VALUES (128,'rise');
INSERT INTO actions VALUES (129,'turn out');
INSERT INTO actions VALUES (130,'pinch');
INSERT INTO actions VALUES (131,'spray');
