
USE recipe_analysis;
DROP TABLE IF EXISTS ingredients;
CREATE TABLE ingredients(
id INT PRIMARY KEY,
name VARCHAR(100) NOT NULL
);
INSERT INTO ingredients VALUES (0,"beef ");
INSERT INTO ingredients VALUES (1,"chicken breasts");
INSERT INTO ingredients VALUES (2,"mushroom soup cream");
INSERT INTO ingredients VALUES (3,"sour cream");
INSERT INTO ingredients VALUES (4,"corn");
INSERT INTO ingredients VALUES (5,"cream cheese");
INSERT INTO ingredients VALUES (6,"butter");
INSERT INTO ingredients VALUES (7,"garlic powder");
INSERT INTO ingredients VALUES (8,"salt");
INSERT INTO ingredients VALUES (9,"pepper");
INSERT INTO ingredients VALUES (10,"chicken");
INSERT INTO ingredients VALUES (11,"chicken gravy cans");
INSERT INTO ingredients VALUES (12,"stuffing");
INSERT INTO ingredients VALUES (13,"cheese");
INSERT INTO ingredients VALUES (14,"peanut butter");
INSERT INTO ingredients VALUES (15,"graham cracker crumbs");
INSERT INTO ingredients VALUES (16,"butter ");
INSERT INTO ingredients VALUES (17,"sugar cup");
INSERT INTO ingredients VALUES (18,"chocolate chips");
INSERT INTO ingredients VALUES (19,"potatoes");
INSERT INTO ingredients VALUES (20,"beef pound");
INSERT INTO ingredients VALUES (21,"milk");
INSERT INTO ingredients VALUES (22,"cheddar cheese");
INSERT INTO ingredients VALUES (23,"bacon");
INSERT INTO ingredients VALUES (24,"green onion");
INSERT INTO ingredients VALUES (25,"ounce");
INSERT INTO ingredients VALUES (26,"sugar");
INSERT INTO ingredients VALUES (27,"egg");
INSERT INTO ingredients VALUES (28,"buttermilk");
INSERT INTO ingredients VALUES (29,"flour");
INSERT INTO ingredients VALUES (30,"soda");
INSERT INTO ingredients VALUES (31,"rhubarb");
INSERT INTO ingredients VALUES (32,"vanilla");
INSERT INTO ingredients VALUES (33,"cream corn");
INSERT INTO ingredients VALUES (34,"saltine crackers");
INSERT INTO ingredients VALUES (35,"");
INSERT INTO ingredients VALUES (36,"cut tomatoes ");
INSERT INTO ingredients VALUES (37,"water");
INSERT INTO ingredients VALUES (38,"onions");
INSERT INTO ingredients VALUES (39,"worcestershire sauce");
INSERT INTO ingredients VALUES (40,"green peppers");
INSERT INTO ingredients VALUES (41,"oil");
INSERT INTO ingredients VALUES (42,"whip");
INSERT INTO ingredients VALUES (43,"pineapple ");
INSERT INTO ingredients VALUES (44,"milk ");
INSERT INTO ingredients VALUES (45,"lemons");
INSERT INTO ingredients VALUES (46,"pecans");
INSERT INTO ingredients VALUES (47,"graham ");
INSERT INTO ingredients VALUES (48,"sweet cherries ");
INSERT INTO ingredients VALUES (49,"ginger ale");
INSERT INTO ingredients VALUES (50,"cherry gelatin");
INSERT INTO ingredients VALUES (51,"almond extract");
INSERT INTO ingredients VALUES (52,"marshmallows");
INSERT INTO ingredients VALUES (53,"paraffin");
INSERT INTO ingredients VALUES (54,"chicken dinner wingsas");
INSERT INTO ingredients VALUES (55,"choice");
INSERT INTO ingredients VALUES (56,"taco sauce");
INSERT INTO ingredients VALUES (57,"beef");
INSERT INTO ingredients VALUES (58,"taco seasoning");
INSERT INTO ingredients VALUES (59,"lettuce");
INSERT INTO ingredients VALUES (60,"tomato");
INSERT INTO ingredients VALUES (61,"onion");
INSERT INTO ingredients VALUES (62,"green pepper");
INSERT INTO ingredients VALUES (63,"cheddar colby");
INSERT INTO ingredients VALUES (64,"pie fillingcherry");
INSERT INTO ingredients VALUES (65,"topping");
INSERT INTO ingredients VALUES (66,"lemon juice");
INSERT INTO ingredients VALUES (67,"pie shell");
INSERT INTO ingredients VALUES (68,"strawberries");
INSERT INTO ingredients VALUES (69,"cornstarch");
INSERT INTO ingredients VALUES (70,"strawberry jello");
INSERT INTO ingredients VALUES (71,"chocolate fudge cake pudding mix");
INSERT INTO ingredients VALUES (72,"white cake pudding mix");
INSERT INTO ingredients VALUES (73,"broccoliabout");
INSERT INTO ingredients VALUES (74,"green onion ");
INSERT INTO ingredients VALUES (75,"raisins");
INSERT INTO ingredients VALUES (76,"mayonnaise");
INSERT INTO ingredients VALUES (77,"vinegar");
INSERT INTO ingredients VALUES (78,"juice strawberries");
INSERT INTO ingredients VALUES (79,"bananas");
INSERT INTO ingredients VALUES (80,"pecans ");
INSERT INTO ingredients VALUES (81,"strawberry o.");
INSERT INTO ingredients VALUES (82,"applesauce");
INSERT INTO ingredients VALUES (83,"cinnamon teaspoon");
INSERT INTO ingredients VALUES (84,"cup");
INSERT INTO ingredients VALUES (85,"nuts");
INSERT INTO ingredients VALUES (86,"bananaschopped");
INSERT INTO ingredients VALUES (87,"food cake mix");
INSERT INTO ingredients VALUES (88,"chocolate fudge pudding mixinstant");
INSERT INTO ingredients VALUES (89,"eggs");
INSERT INTO ingredients VALUES (90,"mints");
INSERT INTO ingredients VALUES (91,"vegetable oil");
INSERT INTO ingredients VALUES (92,"soy sauce");
INSERT INTO ingredients VALUES (93,"garlic salt");
INSERT INTO ingredients VALUES (94,"tomatoes");
INSERT INTO ingredients VALUES (95,"tomato paste ");
INSERT INTO ingredients VALUES (96,"sweet 3");
INSERT INTO ingredients VALUES (97,"sweet basil");
INSERT INTO ingredients VALUES (98,"seasoning tablespoon");
INSERT INTO ingredients VALUES (99,"tomato juice");
INSERT INTO ingredients VALUES (100,"onion ");
INSERT INTO ingredients VALUES (101,"round steak");
INSERT INTO ingredients VALUES (102,"white pepper");
INSERT INTO ingredients VALUES (103,"beef stock");
INSERT INTO ingredients VALUES (104,"flourdredging");
INSERT INTO ingredients VALUES (105,"celery ");
INSERT INTO ingredients VALUES (106,"round thinner");
INSERT INTO ingredients VALUES (107,"tomato sauce");
INSERT INTO ingredients VALUES (108,"mustard");
INSERT INTO ingredients VALUES (109,"sweet chocolate chips");
INSERT INTO ingredients VALUES (110,"beans");
INSERT INTO ingredients VALUES (111,"salsa");
INSERT INTO ingredients VALUES (112,"yeast");
INSERT INTO ingredients VALUES (113,"peaches ");
INSERT INTO ingredients VALUES (114,"cocktail");
INSERT INTO ingredients VALUES (115,"apples");
INSERT INTO ingredients VALUES (116,"white grapes");
INSERT INTO ingredients VALUES (117,"grapes");
INSERT INTO ingredients VALUES (118,"chicken cutlets");
INSERT INTO ingredients VALUES (119,"garlic salt tablespoon");
INSERT INTO ingredients VALUES (120,"pie mix ");
INSERT INTO ingredients VALUES (121,"white cake mix");
INSERT INTO ingredients VALUES (122,"stick butter");
INSERT INTO ingredients VALUES (123,"green onions");
INSERT INTO ingredients VALUES (124,"macaroni");
INSERT INTO ingredients VALUES (125,"pimentos");
INSERT INTO ingredients VALUES (126,"artichoke cans");
INSERT INTO ingredients VALUES (127,"parmesan cheese");
INSERT INTO ingredients VALUES (128,"vegetable soup mix");
INSERT INTO ingredients VALUES (129,"broccoli");
INSERT INTO ingredients VALUES (130,"spaghetti");
INSERT INTO ingredients VALUES (131,"salad supremeseasoning");
INSERT INTO ingredients VALUES (132,"dressing");
INSERT INTO ingredients VALUES (133,"lime gelatin");
INSERT INTO ingredients VALUES (134,"cream ");
INSERT INTO ingredients VALUES (135,"lemon yogurt");
INSERT INTO ingredients VALUES (136,"watermelon rind");
INSERT INTO ingredients VALUES (137,"apple vinegar");
INSERT INTO ingredients VALUES (138,"cloves oil");
INSERT INTO ingredients VALUES (139,"cinnamon oil");
INSERT INTO ingredients VALUES (140,"corn ");
INSERT INTO ingredients VALUES (141,"can");
INSERT INTO ingredients VALUES (142,"peas ");
INSERT INTO ingredients VALUES (143,"beans ");
INSERT INTO ingredients VALUES (144,"tomato can");
INSERT INTO ingredients VALUES (145,"powder");
INSERT INTO ingredients VALUES (146,"cinnamon");
INSERT INTO ingredients VALUES (147,"sticks margarine");
INSERT INTO ingredients VALUES (148,"peppermint candy ");
INSERT INTO ingredients VALUES (149,"cake mix");
INSERT INTO ingredients VALUES (150,"chocolate syrup");
INSERT INTO ingredients VALUES (151,"margarine");
INSERT INTO ingredients VALUES (152,"curry powder");
INSERT INTO ingredients VALUES (153,"juice ");
INSERT INTO ingredients VALUES (154,"celery soup cream");
INSERT INTO ingredients VALUES (155,"chicken cubed");
INSERT INTO ingredients VALUES (156,"jack cheese ");
INSERT INTO ingredients VALUES (157,"egg yolks");
INSERT INTO ingredients VALUES (158,"candies");
INSERT INTO ingredients VALUES (159,"soup onion soup cup");
INSERT INTO ingredients VALUES (160,"tomatoes ");
INSERT INTO ingredients VALUES (161,"vegetables");
INSERT INTO ingredients VALUES (162,"chicken soup cream");
INSERT INTO ingredients VALUES (163,"green chili salsa can");
INSERT INTO ingredients VALUES (164,"green can");
INSERT INTO ingredients VALUES (165,"corn pieces tortilla");
INSERT INTO ingredients VALUES (166,"cabbage");
INSERT INTO ingredients VALUES (167,"carrots cup");
INSERT INTO ingredients VALUES (168,"celery seed");
INSERT INTO ingredients VALUES (169,"pollack flounder");
INSERT INTO ingredients VALUES (170,"green pepper ");
INSERT INTO ingredients VALUES (171,"salad oil");
INSERT INTO ingredients VALUES (172,"basil leaves");
INSERT INTO ingredients VALUES (173,"pepper sauce ");
INSERT INTO ingredients VALUES (174,"green pepper rings");
INSERT INTO ingredients VALUES (175,"corn bread mix");
INSERT INTO ingredients VALUES (176,"stick margarine");
INSERT INTO ingredients VALUES (177,"tomato soup");
INSERT INTO ingredients VALUES (178,"noodles cup");
INSERT INTO ingredients VALUES (179,"salad mayonnaise");
INSERT INTO ingredients VALUES (180,"green ");
INSERT INTO ingredients VALUES (181,"mozzarella cheese");
INSERT INTO ingredients VALUES (182,"olivesoptional");
INSERT INTO ingredients VALUES (183,"tortilla chips");
INSERT INTO ingredients VALUES (184,"coconut");
INSERT INTO ingredients VALUES (185,"meatsoptional");
INSERT INTO ingredients VALUES (186,"vanilla dash");
INSERT INTO ingredients VALUES (187,"orange ");
INSERT INTO ingredients VALUES (188,"coconut cans");
INSERT INTO ingredients VALUES (189,"orange flavoring");
INSERT INTO ingredients VALUES (190,"stick ");
INSERT INTO ingredients VALUES (191,"chicken ");
INSERT INTO ingredients VALUES (192,"rice");
INSERT INTO ingredients VALUES (193,"pineapple cup");
INSERT INTO ingredients VALUES (194,"peaches");
INSERT INTO ingredients VALUES (195,"sour light");
INSERT INTO ingredients VALUES (196,"vanilla 3/4");
INSERT INTO ingredients VALUES (197,"pie crusts");
INSERT INTO ingredients VALUES (198,"cocoa");
INSERT INTO ingredients VALUES (199,"shortening");
INSERT INTO ingredients VALUES (200,"nutmeg");
INSERT INTO ingredients VALUES (201,"cloves");
INSERT INTO ingredients VALUES (202,"cheddar cheese ");
INSERT INTO ingredients VALUES (203,"vanilla wafers");
INSERT INTO ingredients VALUES (204,"white corn syrupkaro");
INSERT INTO ingredients VALUES (205,"egg whites");
INSERT INTO ingredients VALUES (206,"salt dash");
INSERT INTO ingredients VALUES (207,"corn crumbs");
INSERT INTO ingredients VALUES (208,"stick oleo");
INSERT INTO ingredients VALUES (209,"bisquick");
INSERT INTO ingredients VALUES (210,"sausage");
INSERT INTO ingredients VALUES (211,"chicken parts");
INSERT INTO ingredients VALUES (212,"consomme");
INSERT INTO ingredients VALUES (213,"celery");
INSERT INTO ingredients VALUES (214,"catsup");
INSERT INTO ingredients VALUES (215,"chicken broth cans");
INSERT INTO ingredients VALUES (216,"apple juice");
INSERT INTO ingredients VALUES (217,"allspice");
INSERT INTO ingredients VALUES (218,"cinnamon stick");
INSERT INTO ingredients VALUES (219,"seed");
INSERT INTO ingredients VALUES (220,"ginger");
INSERT INTO ingredients VALUES (221,"honey");
INSERT INTO ingredients VALUES (222,"chicken breast halves");
INSERT INTO ingredients VALUES (223,"vegetable spray");
INSERT INTO ingredients VALUES (224,"green onion strips");
INSERT INTO ingredients VALUES (225,"mushrooms");
INSERT INTO ingredients VALUES (226,"clove olive oil garlicup");
INSERT INTO ingredients VALUES (227,"eggs ");
INSERT INTO ingredients VALUES (228,"wedges ");
INSERT INTO ingredients VALUES (229,"wedges orange");
INSERT INTO ingredients VALUES (230,"orange gelatin");
INSERT INTO ingredients VALUES (231,"nutsoptional");
INSERT INTO ingredients VALUES (232,"consomme ");
INSERT INTO ingredients VALUES (233,"onion soup");
INSERT INTO ingredients VALUES (234,"cream cheese ");
INSERT INTO ingredients VALUES (235,"berry cranberry sauce");
INSERT INTO ingredients VALUES (236,"walnuts ");
INSERT INTO ingredients VALUES (237,"cream cup");
INSERT INTO ingredients VALUES (238,"velveeta cheese");
INSERT INTO ingredients VALUES (239,"green chili peppers cans");
INSERT INTO ingredients VALUES (240,"salt ");
INSERT INTO ingredients VALUES (241,"milkmore");
INSERT INTO ingredients VALUES (242,"frying");
INSERT INTO ingredients VALUES (243,"margarinenot");
INSERT INTO ingredients VALUES (244,"velveeta");
INSERT INTO ingredients VALUES (245,"squash");
INSERT INTO ingredients VALUES (246,"carrots");
INSERT INTO ingredients VALUES (247,"soup cans");
INSERT INTO ingredients VALUES (248,"stuffing mix");
INSERT INTO ingredients VALUES (249,"cheddar ounce");
INSERT INTO ingredients VALUES (250,"pimento ");
INSERT INTO ingredients VALUES (251,"tabasco sauce dash");
INSERT INTO ingredients VALUES (252,"apricot ounce");
INSERT INTO ingredients VALUES (253,"food apricots");
INSERT INTO ingredients VALUES (254,"number");
INSERT INTO ingredients VALUES (255,"flour ");
INSERT INTO ingredients VALUES (256,"salt dashes");
INSERT INTO ingredients VALUES (257,"butter crisco");
INSERT INTO ingredients VALUES (258,"sweet milk");
INSERT INTO ingredients VALUES (259,"flavoringlemon");
INSERT INTO ingredients VALUES (260,"bread ");
INSERT INTO ingredients VALUES (261,"instant");
INSERT INTO ingredients VALUES (262,"rolls");
INSERT INTO ingredients VALUES (263,"cheese cup");
INSERT INTO ingredients VALUES (264,"hen");
INSERT INTO ingredients VALUES (265,"pork");
INSERT INTO ingredients VALUES (266,"chicken cup");
INSERT INTO ingredients VALUES (267,"chunks");
INSERT INTO ingredients VALUES (268,"carrot chunks");
INSERT INTO ingredients VALUES (269,"chicken bouillon cubes");
INSERT INTO ingredients VALUES (270,"green chunks");
INSERT INTO ingredients VALUES (271,"pineapple chunks");
INSERT INTO ingredients VALUES (272,"oranges");
INSERT INTO ingredients VALUES (273,"cherries");
INSERT INTO ingredients VALUES (274,"orange juice");
INSERT INTO ingredients VALUES (275,"peanut butter cup");
