
DROP TABLE IF EXISTS recipes;
CREATE TABLE recipes(
id SERIAL PRIMARY KEY,
titolo VARCHAR NOT NULL,
preparazione_nstr VARCHAR,
ingredienti_nstr VARCHAR
);
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (0,'Jewell Ball''S Chicken','1 small jar chipped beef, cut up. 4 boned chicken breasts. 1 can cream of mushroom soup. 1 carton sour cream','Place chipped beef on bottom of baking dish. Place chicken on top of beef. Mix soup and cream together; pour over chicken. Bake, uncovered, at 275° for 3 hours.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (1,'Creamy Corn','16 ounce package frozen corn. 8 ounce package cream cheese, cubed. 1/3 cup butter, cubed. 1/2 teaspoon garlic powder. 1/2 teaspoon salt. 1/4 teaspoon pepper','In a slow cooker, combine all ingredients. Cover and cook on low for 4 hours or until heated through and cheese is melted. Stir well before serving. Yields 6 servings.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (2,'Chicken Funny','1 large whole chicken. 10 1/2 ounce cans chicken gravy. 10 1/2 ounce can cream of mushroom soup. 6 ounce box stove top stuffing. 4 ounce shredded cheese','Boil and debone chicken. Put bite size pieces in average size square casserole dish. Pour gravy and cream of mushroom soup over chicken; level. Make stuffing according to instructions on box (do not make too moist). Put stuffing on top of chicken and gravy; level. Sprinkle shredded cheese on top and bake at 350° for approximately 20 minutes or until golden and bubbly.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (3,'Reeses Cups(Candy)  ','1 cup peanut butter. 3/4 cup graham cracker crumbs. 1 cup melted butter. 1 pound3 1/2 cup powdered sugar. 1 large package chocolate chips','Combine first four ingredients and press in 13 x 9-inch ungreased pan. Melt chocolate chips and spread over mixture. Refrigerate for about 20 minutes and cut into pieces before chocolate gets hard. Keep in refrigerator.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (4,'Cheeseburger Potato Soup','6 baking potatoes. 1 pound of extra lean ground beef. 2/3 cup butter or margarine. 6 cup milk. 3/4 teaspoon salt. 1/2 teaspoon pepper. 1 1/2 c6 ounce shredded cheddar cheese, divided. 12 sliced bacon, cooked, crumbled and divided. 4 green onion, chopped and divided. 8 ounce','Wash potatoes; prick several times with a fork. Microwave them with a wet paper towel covering the potatoes on high for 6-8 minutes. The potatoes should be soft, ready to eat. Let them cool enough to handle. Cut in half lengthwise; scoop out pulp and reserve. Discard shells. Brown ground beef until done. Drain any grease from the meat. Set aside when done. Meat will be added later. Melt butter in a large kettle over low heat; add flour, stirring until smooth. Cook 1 minute, stirring constantly. Gradually add milk; cook over medium heat, stirring constantly, until thickened and bubbly. Stir in potato, ground beef, salt, pepper, 1 cup of cheese, 2 tablespoons of green onion and 1/2 cup of bacon. Cook until heated (do not boil). Stir in sour cream if desired; cook until heated (do not boil). Sprinkle with remaining cheese, bacon and green onions.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (5,'Rhubarb Coffee Cake','1 1/2 cup sugar. 1/2 cup butter. 1 egg. 1 cup buttermilk. 2 cup flour. 1/2 teaspoon salt. 1 teaspoon soda. 1 cup buttermilk. 2 cup rhubarb, finely cut. 1 teaspoon vanilla','Cream sugar and butter. Add egg and beat well. To creamed butter, sugar and egg, add alternately buttermilk with mixture of flour, salt and soda. Mix well. Add rhubarb and vanilla. Pour into greased 9 x 13-inch pan and add Topping.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (6,'Scalloped Corn','1 can cream-style corn. 1 can whole kernel corn. 1/2 packageapproximately 20 saltine crackers, crushed. 1 egg, beaten. 6 teaspoon butter, divided. pepper to taste','Mix together both cans of corn, crackers, egg, 2 teaspoons of melted butter and pepper and place in a buttered baking dish. Dot with remaining 4 teaspoons of butter. Bake at 350° for 1 hour.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (7,'Nolan''S Pepper Steak','1 1/2 pound round steak1-inch thick, cut into strips. 1 can drained tomatoes, cut upsave liquid. 1 3/4 cup water. 1/2 cup onions. 1 1/2 tablespoon worcestershire sauce. 2 green peppers, diced. 1/4 cup oil','Roll steak strips in flour. Brown in skillet. Salt and pepper. Combine tomato liquid, water, onions and browned steak. Cover and simmer for one and a quarter hours. Uncover and stir in Worcestershire sauce. Add tomatoes, green peppers and simmer for 5 minutes. Serve over hot cooked rice.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (8,'Millionaire Pie','1 large container cool whip. 1 large can crushed pineapple. 1 can condensed milk. 3 lemons. 1 cup pecans. 2 graham cracker crusts','Empty Cool Whip into a bowl. Drain juice from pineapple. Mix Cool Whip and pineapple. Add condensed milk. Squeeze lemons, remove seeds and add to Cool Whip and pineapple. Chop nuts into small pieces and add to mixture. Stir all ingredients together and mix well. Pour into a graham cracker crust. Use top from crust to cover top of pie. Chill overnight. Makes 2 pies.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (9,'Double Cherry Delight','17 ounce can dark sweet pitted cherries. 1/2 cup ginger ale. 6 ounce package jell-o cherry flavor gelatin. 2 cup boiling water. 1/8 teaspoon almond extract. 1 cup miniature marshmallows','Drain cherries, measuring syrup. Cut cherries in half. Add ginger ale and enough water to syrup to make 1 1/2 cups. Dissolve gelatin in boiling water. Add measured liquid and almond extract. Chill until very thick. Fold in marshmallows and the cherries. Spoon into 6-cup mold. Chill until firm, at least 4 hours or overnight. Unmold. Makes about 5 1/3 cups.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (10,'Buckeye Candy','1 box powdered sugar. 8 ounce soft butter. 8 ounce peanut butter. paraffin. 12 ounce chocolate chips','Mix sugar, butter and peanut butter. Roll into balls and place on cookie sheet. Set in freezer for at least 30 minutes. Melt chocolate chips and paraffin in double boiler. Using a toothpick, dip balls 3/4 of way into chocolate chip and paraffin mixture to make them look like buckeyes.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (11,'Quick Barbecue Wings','chicken wingsas many as you need for dinner. flour. barbecue sauceyour choice','Clean wings. Flour and fry until done. Place fried chicken wings in microwave bowl. Stir in barbecue sauce. Microwave on High (stir once) for 4 minutes.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (12,'Taco Salad Chip Dip','8 ounce ortega taco sauce. 8 ounce sour cream. 8 ounce cream cheese. 1 pound ground beef. 1 package taco seasoning. shredded lettuce. 1 large diced tomato. 1 medium diced onion. 1 large diced green pepper. shredded colby or cheddar cheese','Mix taco sauce, sour cream and cream cheese. Spread on pizza pan. Brown meat. Drain off fat and add taco seasoning. Spread over cream mixture. Layer with raw vegetables. Top with cheese. Serve with chips.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (13,'Pink Stuff(Frozen Dessert)  ','1 can pie fillingcherry or strawberry. 1 can crushed pineapple, drained. 1 can sweetened condensed milk. 8 ounce container thawed whipped topping. 2 tablespoon lemon juice','Mix all ingredients together. Pour into a 9 x 13-inch pan. Freeze until firm. Allow to set out approximately 15 minutes before serving.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (14,'Fresh Strawberry Pie','1 baked pie shell. 1 quart cleaned strawberries. 1 1/2 cup water. 4 tablespoon cornstarch. 1 cup sugar. 1/8 teaspoon salt. 4 tablespoon strawberry jello','Mix water, cornstarch, sugar and salt in saucepan. Stir constantly and boil until thick and clear. Remove from heat and stir in jello. Set aside to cool. But don''t allow it to set. Layer strawberries in baked crust. Pour cooled glaze over. Continue layering berries and glaze. Refrigerate. Serve with whipped cream.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (15,'Easy German Chocolate Cake','1/2 package chocolate fudge cake mix without pudding or 1 jiffy mix. 1/2 package white cake mix without pudding or 1 jiffy mix. 1/4 cup wesson oil','Mix according to directions and add oil. Bake in 9 x 13-inch pan.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (16,'Broccoli Salad','1 large head broccoliabout 1 1/2 pound. 10 slices bacon, cooked and crumbled. 5 green onions, sliced or 1/4 cup chopped red onion. 1/2 cup raisins. 1 cup mayonnaise. 2 tablespoon vinegar. 1/4 cup sugar','Trim off large leaves of broccoli and remove the tough ends of lower stalks. Wash the broccoli thoroughly. Cut the florets and stems into bite-size pieces. Place in a large bowl. Add bacon, onions and raisins. Combine remaining ingredients, stirring well. Add dressing to broccoli mixture and toss gently. Cover and refrigerate 2 to 3 hours. Makes about 6 servings.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (17,'Strawberry Whatever','1 pound frozen strawberries in juice. 1 small can crushed pineapple. 3 ripe bananas. 1 cup chopped pecans. 1 large package strawberry jell-o. 1 1/2 cup boiling water. 1 pint sour cream','Mix Jell-O in boiling water. Add strawberries, pineapple, crushed bananas and nuts. Spread 1/2 mixture in 13 x 6 1/2-inch pan. Allow to gel in freezer 30 minutes. Add layer of sour cream, then remaining mixture on top. Gel and serve.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (18,'Eggless Milkless Applesauce Cake','3/4 cup sugar. 1/2 cup shortening. 1 1/2 cup applesauce. 3 level teaspoon soda. 1 teaspoon each: cinnamon, cloves and nutmeg. 2 cup sifted flour. 1 cup raisins. 1 cup nuts','Mix Crisco with applesauce, nuts and raisins. Sift dry ingredients and add. Mix well. Put in a greased and floured loaf pan or tube pan. Bake in loaf pan at 350° to 375° for 45 to 60 minutes, layer pan at 375° for 20 minutes or tube pan at 325° for 1 hour.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (19,'Grandma Hanrath''S Banana Breadfort Collins, Colorado  ','1 cup sugar. 1/2 cup shortening. 2 eggsadd one at a time. 1 teaspoon salt. 2 teaspoon soda. 2 cup flour. 1/4 cup nuts. 2 over-ripe bananaschopped','Cream sugar and shortening. Add eggs, salt and soda, then bananas and flour. Add nuts. Mix well. Bake in loaf pan at 350° for 1 hour.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (20,'Chocolate Frango Mints','1 package devil''s food cake mix. 1 package chocolate fudge pudding mixinstant. 8 ounce sour cream. 3/4 cup water. 1/2 cup wesson oil. 4 eggs. 6 ounce chopped frango mints','Mix ingredients together for 5 minutes. Scrape bowl often. Last fold in chocolate chip mints. Bake at 350° for 35 to 40 minutes or until done (cake mix directions).');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (21,'Cuddy Farms Marinated Turkey','2 cup 7-up or sprite. 1 cup vegetable oil. 1 cup kikkoman soy sauce. garlic salt','Buy whole turkey breast; remove all skin and bones. Cut into pieces about the size of your hand. Pour marinade over turkey and refrigerate for at least 8 hours (up to 48 hours). The longer it marinates, the less cooking time it takes.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (22,'Spaghetti Sauce To Can','1/2 bushel tomatoes. 1 cup oil. 1/4 cup minced garlicup
6 cans tomato paste. 3 peppers2 sweet and 1 hot. 1 1/2 cup sugar. 1/2 cup salt. 1 tablespoon sweet basil. 2 tablespoon oreganumber
1 teaspoon italian seasoning','Cook ground or chopped peppers and onions in oil for 1/2 hour. Cook tomatoes and garlic as for juice. Put through the mill. (I use a food processor and do my tomatoes uncooked. I then add the garlic right to the juice.) Add peppers and onions to juice and remainder of ingredients. Cook approximately 1 hour. Put in jars and seal. Yields 7 quarts.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (23,'Prize-Winning Meat Loaf','1 1/2 pound ground beef. 1 cup tomato juice. 3/4 cup oatsuncooked. 1 egg, beaten. 1/4 cup chopped onion. 1/4 teaspoon pepper. 1 1/2 teaspoon salt','Mix well. Press firmly into an 8 1/2 x 4 1/2 x 2 1/2-inch loaf pan. Bake in preheated moderate oven. Bake at 350° for 1 hour. Let stand 5 minutes before slicing. Makes 8 servings.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (24,'Smothered Round Steak(Servings: 4)  ','2 pound round steak. 1/2 teaspoon ground black pepper. 1 teaspoon ground white pepper. 1/2 cup vegetable oil. 2 bell peppers, chopped. 1 cup beef stock or water. 2 teaspoon salt. 1 teaspoon ground red pepper. all-purpose flourdredging. 3 medium onions, chopped. 1 celery rib, chopped','Alex Patout says, "Smothering is a multipurpose Cajun technique that works wonders with everything from game to snap beans. It''s similar to what the rest of the world knows as braising. The ingredients are briefly browned or sauteed, then cooked with a little liquid over a low heat for a long time."');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (25,'Corral Barbecued Beef Steak Strips','2 pound round steak 1/2 to 3/4-inch thick, sliced in strips 1/8-inch thickor thinner. 2 tablespoon cooking oil. 1 can15 ounce tomato sauce. 1/3 cup water. 2 tablespoon brown sugar. 1 tablespoon prepared mustard. 1 tablespoon worcestershire sauce. 1 medium sized onion, thinly sliced','Brown strips in cooking oil. Pour off drippings. Combine tomato sauce, water, brown sugar, mustard and Worcestershire sauce. Add sauce and onion to meat slices. Cover and cook slowly, stirring occasionally 30 minutes or until meat is tender. Serve over rice or buttered noodles. Yields 6 to 8 servings.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (26,'Easy Fudge','14 ounce can sweetened condensed milk. 12 ounce package semi-sweet chocolate chips. 1 ounce. 1 1/2 cup chopped nutsif desired. 1 teaspoon vanilla','Butter a square pan, 8 x 8 x 2-inches. Heat milk, chocolate chips and unsweetened chocolate over low heat, stirring constantly, until chocolate is melted and mixture is smooth. Remove from heat. Stir in nuts and vanilla. Spread in pan.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (27,'Taco-Filled Green Pepper','1 pound ground beef. 1 package taco seasoning. 1 san kidney beans. 1 onion, chopped. 1 c salsa. 4 green peppers. 1 medium tomato, chopped. 1/2 c cheddar cheese, shredded. 1/2 c sour cream','In a large skillet, brown the ground beef. Drain, stir in taco mix, kidney beans, and salsa. Bring to a boil. Reduce heat, and let simmer for about 5 minutes. Cut peppers in half and clean it. Put peppers in boiling water for 3 minutes- drain- spoon the meat mixture into the green pepper. Put pepper in an ungreased pan. Cover, and bake at 350 degrees for 15 to 20 minutes or until peppers are crispy and filling is heated through. Top with tomatoes, cheese, and sour cream.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (28,'One Hour Rolls','1 cup milk. 2 tablespoon sugar. 1 package dry yeast. 1 tablespoon salt. 3 tablespoon crisco oil. 2 cup plain flour','Put flour into a large mixing bowl. Combine sugar, milk, salt and oil in a saucepan and heat to boiling; remove from heat and let cool to lukewarm. Add yeast and mix well. Pour into flour and stir. Batter will be sticky. Roll out batter on a floured board and cut with biscuit cutter. Lightly brush tops with melted oleo and fold over. Place rolls on a cookie sheet, put in a warm place and let rise for 1 hour. Bake at 350° for about 20 minutes. Yield: 2 1/2 dozen.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (29,'Punch Bowl Fruit Salad','2 large cans sliced peaches. 2 large cans fruit cocktail. 1 large can diced pineapple. 1 quart fresh strawberries. 2 red apples. 2 yellow apples. 4 large ripe bananas. 1 pound white grapes. 1 pound purple grapes','In a 6-quart punch bowl mix all of the cans of fruit, juice and all. Clean and slice berries. Wash and slice apples; leave peeling on apples. Dice apples. Slice bananas. Wash and cut grapes in half. Mix all together. Nuts or other fruit may be added.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (30,'Summer Chicken','1 package chicken cutlets. 1/2 cup oil. 1/3 cup red vinegar. 2 tablespoon oreganumber
2 tablespoon garlic salt','Double recipe for more chicken.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (31,'Cherry Pizza','2 cans cherry pie mix. 1 box deluxe white cake mix. 1 stick butter. 1 cup ground nuts','Grease a 9 x 12-inch cake pan. Spread cherry pie mix. Sift cake mix and spread it dry over the cherries. Top with ground nuts. Melt butter and pour over top. Bake 45 minutes in a 350° oven.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (32,'Potato And Cheese Pie','3 eggs. 1 teaspoon salt. 1/4 teaspoon pepper. 2 cup half and half. 3 cup potatoes, shredded coarse. 1 cup cheddar cheese, coarsely shredded. 1/3 cup green onions','Beat eggs, salt and pepper until well blended. Stir in half and half, potatoes and onions. Pour into well-greased 8-inch baking dish. Bake in a 400° oven for 35 to 40 minutes, or until knife inserted in center comes out clean and potatoes are tender. Cool on rack 5 minutes; cut into squares. Makes 4 large servings.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (33,'Tuna Macaroni Casserole','1 box macaroni and cheese. 1 can tuna, drained. 1 small jar pimentos. 1 medium onion, chopped','Prepare macaroni and cheese as directed. Add drained tuna, pimento and onion. Mix. Serve hot or cold.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (34,'Artichoke Dip','2 cans or jars artichoke hearts. 1 cup mayonnaise. 1 cup parmesan cheese','Drain artichokes and chop. Mix with mayonnaise and Parmesan cheese. After well mixed, bake, uncovered, for 20 to 30 minutes at 350°. Serve with crackers.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (35,'Broccoli Dip For Crackers','16 ounce sour cream. 1 package dry vegetable soup mix. 10 ounce package frozen chopped broccoli, thawed and drained. 4 to 6 ounce cheddar cheese, grated','Mix together sour cream, soup mix, broccoli and half of cheese. Sprinkle remaining cheese on top. Bake at 350° for 30 minutes, uncovered. Serve hot with vegetable crackers.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (36,'Summer Spaghetti','1 pound very thin spaghetti. 1/2 bottle mccormick salad supremeseasoning. 1 bottle zesty italian dressing','Prepare spaghetti per package. Drain. Melt a little butter through it. Marinate overnight in Salad Supreme and Zesty Italian dressing. Just before serving, add cucumbers, tomatoes, green peppers, mushrooms, olives or whatever your taste may want.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (37,'Pear-Lime Salad','16 ounce can pear halves, undrained. 3 ounce package lime gelatin. 8 ounce package cream cheese, softened. 8 ounce carton lemon yogurt','Drain pears, reserving juice. Bring juice to a boil, stirring constantly. Remove from heat. Add gelatin, stirring until dissolved. Let cool slightly. Coarsely chop pear halves. Combine cream cheese and yogurt; beat at medium speed of electric mixer until smooth. Add gelatin and beat well. Stir in pears. Pour into an oiled 4-cup mold or Pyrex dish. Chill.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (38,'Watermelon Rind Pickles','7 pound watermelon rind. 7 cup sugar. 2 cup apple vinegar. 1/2 teaspoon oil of cloves. 1/2 teaspoon oil of cinnamon','Trim off green and pink parts of watermelon rind; cut to 1-inch cubes. Parboil until tender, but not soft. Drain. Combine sugar, vinegar, oil of cloves and oil of cinnamon; bring to boiling and pour over rind. Let stand overnight. In the morning, drain off syrup. Heat and put over rind. The third morning, heat rind and syrup; seal in hot, sterilized jars. Makes 8 pints. (Oil of cinnamon and clove keeps rind clear and transparent.)');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (39,'Chicken Stew','3 pound chicken, boiled. 4 medium potatoes, diced. 2 medium onions, chopped. 16 ounce can creamed corn. 16 ounce can english peas. 16 ounce can field peas. 16 ounce can butter beans. 16 ounce can tomatoes. 46 ounce can tomato juice. 1 small box macaroni. 1 tablespoon black pepper. 1 tablespoon salt. 1 tablespoon sugar','Remove chicken from bone. Use the broth. Mix the vegetables and macaroni. Add sugar, salt and black pepper. Cook until all vegetables are tender over medium heat.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (40,'Quick Coffee Cake(6 Servings)  ','3 tablespoon softened butter or margarine. 1/2 cup granulated sugar. 1 egg. 1 cup flour. 1 1/4 teaspoon baking powder. 1/4 teaspoon salt. 1/3 cup milk. 1/4 teaspoon vanilla. 1/3 cup brown sugar, packed. 1/2 teaspoon cinnamon. 2 tablespoon butter or margarine','Mix 3 tablespoons fat with granulated sugar. Add egg and beat until creamy. Mix flour, baking powder and salt thoroughly. Add to sugar mixture alternately with milk. Add vanilla. Spread batter evenly in a greased 8-inch square baking pan. Mix brown sugar and cinnamon and sprinkle over batter. Dot with 2 tablespoons fat. Bake at 350° (moderate oven) for 25 to 30 minutes.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (41,'Angel Biscuits','5 cup flour. 3 tablespoon sugar. 4 teaspoon baking powder. 1 1/2 package dry yeast. 2 cup buttermilk. 1 teaspoon soda. 1 1/2 sticks margarine. 1/2 cup warm water','Mix flour, sugar, baking powder, soda and salt together. Cut in margarine, dissolve yeast in warm water. Stir into buttermilk and add to dry mixture. Cover and chill.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (42,'Quick Peppermint Puffs','8 marshmallows. 2 tablespoon margarine, melted. 1/4 cup crushed peppermint candy. 1 can crescent rolls','Dip marshmallows in melted margarine; roll in candy. Wrap a crescent triangle around each marshmallow, completely covering the marshmallow and square edges of dough tightly to seal. Dip in margarine and place in a greased muffin tin. Bake at 375° for 10 to 15 minutes; remove from pan.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (43,'Fruit Pizza','1 box yellow cake mix. 1/4 cup water. 1/4 cup brown sugar. 1/2 cup soft butter. 2 eggs. 1/2 cup chopped nuts','Mix ingredients and spread into 2 greased pizza pans. Bake at 350° for 15-20 minutes.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (44,'Chocolate Mint Bars','1 cup flour. 1 cup sugar. 1/2 cup oleo, softened. 4 eggs. 1 can chocolate syrup','Mix together and bake in 9 x 13-inch pan at 350° for 25 to 30 minutes. Top should spring back when touched lightly; do not overbake. Cool completely, then spread with mint layer.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (45,'Beer Bread','3 cup self rising flour. 1 - 12 ounce can beer. 1 tablespoon sugar','Stir the ingredients together and put in a greased and floured loaf pan. Bake at 425 degrees for 50 minutes. Drizzle melted butter on top.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (46,'Chicken Divan','1/4 cup margarine. 1/4 cup chopped onionor as much as you want. chopped celery to taste. 1/4 cup flour. 1/8 teaspoon curry powder. 1 can sliced mushroomssave juice. 1 can cream of celery soup. 1 package chopped broccoli. 1 cubed chicken. shredded monterey jack cheese','Melt margarine in skillet; saute onions and celery. Remove from heat. Stir in flour and curry powder. Drain mushrooms and keep juice. Add water to juice to make 1/2 cup liquid. Stir liquid and soup into flour mixture; add mushrooms. Cook until thick. Arrange broccoli and cubed chicken in a large baking dish. Spoon sauce over chicken. Top with grated cheese. Bake in a 350° oven for about 20 minutes or in microwave until cheese is melted.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (47,'Mexican Cookie Rings','1 1/2 cup sifted flour. 1/2 teaspoon baking powder. 1/2 teaspoon salt. 1/2 cup butter. 2/3 cup sugar. 3 egg yolks. 1 teaspoon vanilla. multi-colored candies','Sift flour, baking powder and salt together. Cream together butter and sugar. Add egg yolks and vanilla. Beat until light and fluffy. Mix in sifted dry ingredients. Shape into 1-inch balls. Push wooden spoon handle through center (twist). Shape into rings. Dip each cookie into candies. Place on lightly greased baking sheets. Bake in 375° oven for 10 to 12 minutes or until golden brown. Cool on racks. Serves 2 dozen.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (48,'Vegetable-Burger Soup','1/2 pound ground beef. 2 cup water. 1 teaspoon sugar. 1 package cup-a-soup onion soup mixdry. 1 pound can stewed tomatoes. 8 ounce can tomato sauce. 10 ounce package frozen mixed vegetables','Lightly brown beef in soup pot. Drain off excess fat. Stir in tomatoes, tomato sauce, water, frozen vegetables, soup mix and sugar. Bring to a boil. Reduce heat and simmer for 20 minutes. Serve.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (49,'Chicken Ole','4 chicken breasts, cooked. 1 can cream of chicken soup. 1 can cream of mushroom soup. 1 can green chili salsa sauce. 1 can green chilies. 1 cup milk. 1 grated onion. 1 package corn tortilla in pieces','Dice chicken. Mix all ingredients together. Let sit overnight. Bake 1 1/2 hours at 375°.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (50,'Creamy Coleslaw(Better Homes And Gardens)  ','4 cup shredded cabbage. 1/2 cup shredded carrots. 1/4 cup finely chopped green pepper. 2 tablespoon finely chopped onion. 1/2 cup mayonnaise. 1 tablespoon vinegar. 2 teaspoon sugar. 1 teaspoon celery seed. 1/4 teaspoon salt','In a large bowl, combine cabbage, carrot, green pepper and onion or can use package of slaw mix purchased from store.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (51,'Creole Flounder','2 pound flounder or pollack fillets. 1 1/2 cup chopped tomatoes. 1/2 cup chopped green pepper. 1/3 cup lemon juice. 1 tablespoon salad oil. 2 teaspoon salt. 2 teaspoon minced onion. 1 teaspoon basil leaves. 1/4 teaspoon coarsely ground black pepper. 4 drops red pepper sauce. green pepper rings','Heat oven to 500°. Place fillets in single layer in baking dish, 13 1/2 x 9 x 2-inch. Stir together remaining ingredients except pepper rings. Spoon over fillets. Bake 5 to 8 minutes or until fish flakes easily with fork. Remove fillets to warm platter. Garnish with green pepper rings. Makes 4 to 6 servings.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (52,'Three Bean Salad','1 can green beans, wash and drain. 1 can yellow beans, wash and drain. 1 can kidney beans, wash and drain. 1 cup sugar. 1/2 cup salad oil. 2/3 cup vinegar. 1/3 cup water','Mix together all of sugar, salad oil, vinegar and water until sugar is dissolved. Pour over beans and let stand overnight.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (53,'Dave''S Corn Casserole','16 1/2 ounce can whole kernel corn, drained. 16 1/2 ounce can cream-style corn. 8 ounce sour cream. 8 1/2 ounce package jiffy corn bread mix. 1 stick margarine','In a bowl, mix corns, sour cream, corn bread mix and melted margarine. Pour into a greased 8 x 8 x 2-inch pan. Bake at 350° for 50 minutes.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (54,'Casserole Italiano','1 pound ground beef. 1/3 cup chopped onion. 1 can tomato soup. 2 cup cooked wide noodles. 1/2 teaspoon oreganumber
1/2 teaspoon salt. 1/3 cup water. 1 cup cheese','Brown beef with onion and seasonings and combine in a 1 1/2-quart casserole with soup, water and noodles. Place cheese around edges. Bake at 350° for 30 minutes.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (55,'Corned Beef And Cabbage Casserole','1 small cabbage, shredded. 1 teaspoon dry mustard. 1 can corned beef, flaked. 1 can cream of celery soup. 1 medium chopped onion','Combine all ingredients and cook uncovered over low heat until cabbage is crisp-tender, about 20 minutes.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (56,'Crab Cakes','1 tablespoon worcestershire sauce. 2 or 3 shakes old bay. 1 teaspoon dry mustard. 2 tablespoon mayonnaise. 1 egg','Mix together and carefully add 1 pound lump crab meat. Mix ahead of time and refrigerate so they will hold together better.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (57,'Taco Dip','8 ounce package cream cheese, softened. 1/2 cup mayonnaise or salad dressing. 8 ounce mild taco sauce. 2 to 4 thinly sliced green onions. 1/2 green pepper, chopped. 1 tomato, chopped. 1 cup mozzarella cheese. 1 cup cheddar cheese. 1/2 cup black olivesoptional. tortilla chips','Mix together cream cheese and mayonnaise. Spread on to a large platter or two dinner plates. Freeze for 15 minutes. Spread taco sauce evenly on top. Layer remaining ingredients in the written order. Serve with tortilla chips.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (58,'Bonbon Cookies','1/2 pound soft butter. 1/2 cup peanut butter. 1/2 pound graham cracker crumbs. 2 cup coconut. 1/2 cup nut meatsoptional. dash of vanilla','Cream together the butter and peanut butter. Add the remaining ingredients. Mix and form into balls (best to mix with your hands) and chill several hours, even a day.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (59,'Forever Amber','1 pound orange sliced candy, chopped. 2 cans angel flake coconut. 2 cup chopped pecans. 2 cans condensed milk. 1 teaspoon vanilla. 1 teaspoon orange flavoring','Mix together. Spread in a buttered pan. Bake for 30 minutes at 275°. While still hot, sift 1 box of powdered sugar into it. Drop by teaspoons on waxed paper. Let dry. If it seems set on bottom, turn over and let it continue to dry.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (60,'Gooey Coffee Cake','1 yellow cake mix. 2 eggs. 1 stick oleo, melted. 1 cup chopped nuts. 2 eggs. 8 ounce softened cream cheese. 1 pound powdered sugar','Mix together cake mix, 2 eggs and melted oleo. Put in greased 9 x 13-inch pan. Put chopped nuts on top of mixture. Mix together 2 eggs, cream cheese and powdered sugar. Add on top of first mixture. Bake 15 minutes at 325°, then bake 20 minutes at 350°.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (61,'Phylis'' Pineapple-Banana Salad','1 large can chunk pineapple. 4 to 5 bananas','Drain pineapple and reserve juice. Cut bananas in chunks like pineapple.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (62,'Chicken Casserole','1 can cream of mushroom soup. 1 can cream of chicken soup. 1 can cream of celery soup. 1 cut up chicken. 1/2 cup melted butter or margarine. 1 1/2 cup uncooked rice','Mix all ingredients together in baking dish. Cover and bake at 350° for 2 1/2 hours. Bake the last 45 minutes, uncovered, to brown top of chicken.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (63,'Pineapple Nut Pie','8 ounce package cream cheese. 1 can sweetened condensed milk. 1/2 cup crushed pineapple. 1/3 cup chopped nuts. 1/3 cup lemon juice','Cream the cream cheese; add the milk and beat smooth. Add lemon juice, pineapple and nuts. Beat well. Pour into graham cracker crust and chill. Slice in small servings (very rich) and top with dollop of Cool Whip.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (64,'Annie''S Diabetic Candy','8 ounce. 8 ounce philadelphia light cream cheese. 2 tablespoon butter. 2 tablespoon peanut butter or more if you would like','Mix all ingredients, form in small balls and roll in chopped peanuts. Keep refrigerated.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (65,'Frozen Peach Mousse','4 medium peaches, peeled and chopped. 1 to 1 1/4 cup sugar. 1 1/4 cup sour creamuse light. 1/4 cup lemon juice. 3/4 to 1 teaspoon vanilla','Puree peaches in a blender. Add remaining ingredients. Blend and pour in container and freeze.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (66,'Strawberry Pie','16 ounce cool whip. 2 package frozen strawberries *. 9-inch deep pan pie crusts. 1 3/4 cup sugar. 12 ounce cream cheese','*Can also use blueberries or cherries.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (67,'Blueberry Surprise','1 stick margarine. 1 1/2 cup graham cracker crumbs. 1/4 cup granulated sugar','Mix ingredients and press 2/3 mixture in bottom of square baking dish. (A bowl that has the same diameter top and bottom may be used, 1 1/2 to 2-quart size.)');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (68,'Moist Devil''S Food Cake','2 cup sifted flour. 1 1/2 teaspoon baking soda. 1/4 teaspoon salt. 1/2 cup shortening. 1 1/2 cup sugar. 2 eggs, separated. 1/2 cup cocoa. water. 1 teaspoon vanilla. 1 cup milk','Sift together the flour, soda and salt; set aside. Combine shortening and sugar in a bowl. Beat until creamy. Add egg yolks; beat well. Combine cocoa, water and vanilla to make 1 cup; mix well. Add to batter. Add flour mixture alternately with milk. Beat well after each addition; set aside. Beat egg whites until stiff peaks form when beater is lifted. Fold into batter. Bake in two 9-inch greased cake pans at 375° for 30 minutes.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (69,'Dot''S Civil War Cake','3 medium apples, chopped. 2 cup raisins. 1 cup brown sugar. 1 cup granulated sugar. 2 tablespoon shortening. 2 cup cold water. 3 cup flour. 2 teaspoon soda. 1 teaspoon cinnamon. 1 teaspoon nutmeg. 1 teaspoon cloves. 1 teaspoon salt. 1 cup nuts','Combine and cook first 6 ingredients. Bring to boil and boil 5 minutes; cool. Add sifted, dry ingredients to apple mixture. Stir and blend only. Add nuts. Pour into greased and floured tube pan. Bake 1 hour at 350°. Serves 16.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (70,'Potato Casserole','6 cup diced potatoes. 1/2 cup chopped onion. 3/4 cup melted butter. 1 can cream of chicken soup. 8 ounce sour cream. 1 cup grated cheddar cheese. 2 cup crushed cornflakes','Peel and dice potatoes; place in bowl of cold, salted water. Drain potatoes and dry on paper towels. Mix 1/2 cup butter, onions, soup, sour cream and cheese; stir well. Add potatoes to mixture and pour into a 2 1/2-quart casserole dish. Crush cornflakes, mix with remaining butter. Sprinkle cornflakes and butter on top of potato mixture. Bake at 350° for 50 minutes.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (71,'Dream Pie','vanilla wafers. butter','Mix vanilla wafer crumbs with butter.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (72,'Divinity Fudge','2 2/3 cup sugar. 2/3 cup white corn syrupkaro. 2/3 cup cold water. 2 egg whites. 1 teaspoon vanilla. 1 cup chopped nuts','Stir well together the sugar, syrup and water. Allow to boil without stirring until it forms a hard ball in cold water. Pour this over stiffly beaten egg whites, beating constantly. Cool; add vanilla and nuts. Beat until cool and thick enough to set. Pour into a buttered platter or drop by teaspoons on waxed paper.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (73,'Apple Crisp','apples. 1/2 cup sugar. 1 teaspoon cinnamon. 1/4 cup sugar. 1 cup flour. dash of salt. 1/2 cup corn flake crumbs. 1 stick oleo','Mix 1/2 cup of sugar and cinnamon. Spread on apples. Mix 1/4 cup sugar, flour, salt, cornflake crumbs and oleo. Spread mixture on apples.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (74,'Sausage Balls','2 cup bisquick. 1 pound sausage. 8 ounce package cheddar cheese, grated','Mix sausage and cheese together. Add Bisquick and mix thoroughly. Roll into medium size balls. Bake at 350° for 15 minutes or until golden brown.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (75,'Consomme Chicken','chicken parts. 1 can cream of chicken soup. 1 can consomme. 2 cup rice. salt to taste. pepper to taste','Add enough liquid to chicken soup and consomme to make 4 cups of water. Season with salt and pepper. Cook at 350° for 1 hour.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (76,'Spanish Hamburgers','1/2 cup celery. 2 chopped onions. 2 tablespoon butter. 1 pound ground beef. 2 tablespoon vinegar. 2 tablespoon lemon juice. 2 tablespoon brown sugar. 1 1/2 tablespoon mustard. 1 teaspoon salt. 1 1/2 teaspoon pepper. 1 cup catsup. 1 cup water','Brown celery, onions and ground beef in butter. Add vinegar, lemon juice, brown sugar, mustard, salt, pepper catsup and water. Simmer for 30 minutes.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (77,'Egg Drop Soup','13 3/4 ounce cans chicken broth. 1 tablespoon cornstarch. 1 well beaten egg. 2 tablespoon sliced1/4-inch green onion','In saucepan slowly stir the chicken broth into cornstarch. Cook, stirring constantly, until slightly thickened. Slowly pour in the well beaten egg; stir once gently. Remove from heat. Garnish with sliced green onion. Makes 4 servings.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (78,'Mulled Cider','1/2 gallon apple juice. 1 teaspoon allspice. 1 teaspoon whole cloves. 1 cinnamon stick. 1 cup brown sugar','Simmer all of the ingredients. Strain into warmed mugs and top with a dash of nutmeg. This recipe can be doubled many times, according to the number of guests present.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (79,'Sesame Ginger Chicken','1 tablespoon sesame seed, toasted. 2 teaspoon grated ginger. 2 tablespoon honey. 2 tablespoon reduced-sodium soy sauce. 4 ounce skinned chicken breast halves. vegetable cooking spray. thin green onion strips','Combine first 4 ingredients in a small bowl, stir well and set aside. Place chicken between 2 sheets of waxed paper or heavy duty plastic wrap, and flatten to 1/4-inch thickness, using meat mallet or rolling pin. Coat grill rack with cooking spray; place on grill over coals. Place chicken on rack and cook 4 minutes on each side, basting frequently with soy sauce mixture. Transfer chicken to a serving platter and garnish with green onion, if desired. Yields 4 servings, about 200 calories.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (80,'Egg Casserole','1 vidalia onion, chopped. 16 ounce package fresh mushrooms. 2 green peppers. 1 clove garlicup
olive oil. 6 pieces breadbuttered with either butter or margarine. 6 eggs. milkas much as you would like; to fluff eggs','Saute together first 5	ingredients. In a separate 9 x 12-inch pan, mix bread, eggs and milk. Put pieces of bread into pan; add your vegetables, then your eggs. Place	in refrigerator overnight (at least 8 hours). Add Cheddar cheese before cooking. Bake at 350° for 1 hour.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (81,'Cranberry-Apple-Orange Salad','12 ounce. 1 cup sugar. 1 medium apple, peeled, cored and cut into wedges. 1 orange, peeled, seeded and broken in wedges. 3 ounce package orange gelatin. 1/2 cup nutsoptional','In food processor or blender, grind cranberries, apple and orange. Mix with sugar and set aside. Prepare gelatin according to package directions, using 1/4 cup less of cold water. Chill until it begins to thicken. Add cranberry mixture and nuts. Mix well. Pour into a mold, if desired, or leave in a bowl and stir before serving. Chill until set. Can even be made a day ahead. Keeps well in refrigerator for a few days.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (82,'Brown Rice','1 cup raw rice. 1 can beef consomme. 1 can french onion soup. 4 ounce can mushrooms. 1/2 stick margarine, cut up','Put in a covered 1 1/2-quart dish. Bake 1 hour at 350°.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (83,'Cranberry Salad','3 ounce package softened cream cheese. 2 tablespoon margarine. 2 tablespoon sugar. 16 ounce can whole berry cranberry sauce. 3/4 cup crushed pineapple, drained. 1/2 cup chopped walnuts. 1 cup whipping cream','Mix cream cheese, margarine and sugar. Add fruit and walnuts. Whip cream and fold into fruit and cream cheese mixture. Pour into round mold. Freeze 6 hours. Remove from mold shortly before serving. Makes 12 servings.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (84,'Cheese Dip','2 pound velveeta cheese. 15 ounce can italian tomatoes. 2 small cans green chili peppers. 1/2 medium onion, minced. 3 cloves garlicup
1/2 teaspoon salt','Dice tomatoes and peppers. Combine all ingredients in top of double boiler for 30 minutes. Serve hot over corn chips.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (85,'Funnel Cake','1 1/3 cup flour. 1 1/4 teaspoon salt. 1/2 teaspoon soda. 2 tablespoon sugar. 3/4 tablespoon baking powder. 1 egg, beaten. 2/3 cup milkmore if batter is too thick. oilfor frying. powdered sugar','Sift first 5 ingredients together in a bowl. Mix egg and milk together; add to dry ingredients. Beat until smooth. Hold finger over bottom of a funnel; pour in some batter. Remove finger to let batter drop. Drop batter in a spiral motion into pan filled with 1 inch of hot oil (375°). Fry until golden brown, turning once. Remove from pan; drain on a paper towel. Sprinkle with powdered sugar and serve hot.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (86,'Fast Real Good Fudge','4 pound confectioners sugar. 1 cup cocoa. 1 cup chopped nuts. 1 pound margarinenot whipped. 1 pound velveeta. 1 tablespoon vanilla','In large bowl, put confectioners sugar, cocoa and chopped nuts. In saucepan, put margarine and Velveeta. Melt and add vanilla. Pour hot mixture over sugar mixture. Mix quickly and pour into buttered cookie sheet. Cool and cut into squares.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (87,'Squash Casserole','3 pound squash. 3 onions. 1 pint sour cream. 3 carrots, grated. 2 cans chicken or mushroom soup. 1 package pepperidge farm stuffing mix. 1 stick butter. salt and pepper to taste','Cook squash, onions and carrots until tender. Mash. Melt butter in pan; stir in stuffing until all is coated. Drain all water from squash. Stir in sour cream and soup. Place in a greased baking dish a layer of squash and a layer of stuffing. Bake at 350° for 35 minutes.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (88,'Cheese Ball','2 package cream cheese. 2 cup shredded cheddar cheese8 ounce. 1 tablespoon chopped pimento. 1 tablespoon chopped green pepper. 1 tablespoon chopped onion. 1 teaspoon lemon juice. 2 teaspoon worcestershire sauce. dash of tabasco sauce. dash of salt','Combine softened cream and Cheddar cheeses. Add chopped up items. Mix and add liquids last. Mix well. Roll into ball and cover with chopped nuts.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (89,'*Apricot Salad','1 large package apricot jello6 ounce. 2/3 cup sugar. 8 ounce package cream cheese. 2 jars junior baby food apricots. number 2. 1 tall can evaporated milk, chilled and whipped. 2/3 cup water','Dissolve jello in boiling water; add sugar. Blend in the cream cheese with a fork. Add can of crushed pineapple and apricot baby food. Refrigerate. Chill can of milk. When jello starts to set, take milk out of the refrigerator and beat until stiff. Fold partially set jello into cream. Chopped nuts can be used for garnish. This is a large salad; could fill a 2-quart mold or 2 (1-quart) molds. Serves about 12.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (90,'Pound Cake','3 cup plain flourcake flour may be substituted for plain flour. 3 cup sugar. 1/2 teaspoon baking powder. 3 dashes of salt. 5 eggs. 2 sticks margarine. 1/2 cup butter flavor crisco. 1 cup sweet milk. 1 to 2 tablespoon flavoringlemon, vanilla or almond or a combination of the 3','Have all ingredients at room temperature. Hand stir all dry ingredients together. Add eggs and stir. Add butter and Crisco and stir. Add milk and stir. Put batter in mixer and beat at high speed until well blended. Add 1 to 2 teaspoons of your favorite flavoring and mix well. Pour batter into greased and floured tube pan. Place in cold oven. Bake at 325° for 1 hour and 20 to 30 minutes.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (91,'Monkey Bread','2 loaves frozen bread, softened. 1/2 cup margarine. 1 cup brown sugar. 1 large box vanilla puddingnot instant. 2 tablespoon milk. cinnamon to taste','Use greased 9 x 13-inch pan or Bundt pan. Melt butter; add brown sugar, pudding, milk and cinnamon. Break up 1 loaf into round balls; place in pan. Pour mixture over and break second loaf over this. Rise 2 1/2 to 3 hours. Bake 30 minutes at 350°; turn out immediately to cool.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (92,'Chicken Roll-Ups','8 ounce can crescent rolls. 1 1/2 cup grated medium or sharp cheese. 1 hen, cooked and diced. 1 can cream of chicken soup. 1 1/2 cup milk','Unroll crescent rolls; add cooked chicken and grated cheese. Wrap roll over chicken and cheese; pinch sides together.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (93,'Beef And Spanish Rice Casserole','1 can spanish rice. 1 can corned beef. 1 diced onion. 1/2 cup grated cheddar cheese','Spray a 1-quart casserole dish with Pam. Layer rice and meat, diced onion and grated cheese. Bake at 350° for 25 to 30 minutes.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (94,'Baked Beans','1 pound cans pork and beans. 1/2 cup bell pepper, chopped. 1/2 cup onions, chopped. 3/4 cup catsup. 1/3 cup brown sugar, packed hard. 1 teaspoon salt. 1/3 teaspoon black pepper. 1 pound ground beef. 1 tablespoon oil','Cook onions and bell pepper in oil until onions are transparent. Add beef and cook until brown. Mix all ingredients together. Bake in 350° oven for 45 minutes, or after mixing together, pour in crock-pot and cook 6 to 10 hours on low.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (95,'Sweet-N-Sour Chicken','2 cup diced cooked chicken. 2 tablespoon shortening. 1/2 cup onionlarge chunks. 2 cup carrot chunks. 1 1/4 cup water. 3 chicken bouillon cubes. 1/4 cup packed brown sugar. 2 tablespoon cornstarch. 1/4 teaspoon ginger. 1/4 cup catsup. 2 tablespoon vinegar. 1 tablespoon soy sauce. 1 cup green pepperlarge chunks. 8 ounce pineapple chunks','Saute onion in 2 tablespoons shortening. Add carrots, water and bouillon cubes. Simmer 5 minutes. Combine next 6 ingredients. Add to vegetable mixture and cook until clear. Add pepper, pineapple and chicken. Cover and simmer 5 minutes or until heated through. Serve with rice or angel hair noodles. Serves 6 people.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (96,'Ambrosia','8 to 10 juicy oranges, peeled and diced. 1 cup moist coconut. 1/2 cup pecans, chopped. 1/2 cup cherries, halved. 1/4 cup sugar. 1 cup orange juice','Combine all ingredients. Chill overnight. Yields 4 to 6 servings.');
INSERT INTO recipes (id, titolo, ingredienti_nstr, preparazione_nstr) VALUES (97,'Crazy Peanut Butter Cookies','1 cup creamy peanut butter. 1 cup sugar. 1 egg','Mix together and roll into balls; flatten with fork. Bake on ungreased cookie sheet. Makes 2 dozen. Quick, easy and good.');
