
DROP TABLE IF EXISTS actions;
CREATE TABLE actions(
id SERIAL PRIMARY KEY,
name VARCHAR NOT NULL
);
INSERT INTO actions VALUES (0,'mix');
INSERT INTO actions VALUES (1,'stir over');
INSERT INTO actions VALUES (2,'stir');
INSERT INTO actions VALUES (3,'take off');
INSERT INTO actions VALUES (4,'drop');
INSERT INTO actions VALUES (5,'let');
INSERT INTO actions VALUES (6,'place');
INSERT INTO actions VALUES (7,'pour');
INSERT INTO actions VALUES (8,'bake');
INSERT INTO actions VALUES (9,'combine');
INSERT INTO actions VALUES (10,'cover');
INSERT INTO actions VALUES (11,'yields');
INSERT INTO actions VALUES (12,'debone');
INSERT INTO actions VALUES (13,'put');
INSERT INTO actions VALUES (14,'level');
INSERT INTO actions VALUES (15,'make');
INSERT INTO actions VALUES (16,'sprinkle');
INSERT INTO actions VALUES (17,'spread');
INSERT INTO actions VALUES (18,'refrigerate');
INSERT INTO actions VALUES (19,'keep');
INSERT INTO actions VALUES (20,'wash');
INSERT INTO actions VALUES (21,'prick');
INSERT INTO actions VALUES (22,'microwave');
INSERT INTO actions VALUES (23,'eat');
INSERT INTO actions VALUES (24,'cut in');
INSERT INTO actions VALUES (25,'scoop out');
INSERT INTO actions VALUES (26,'discard');
INSERT INTO actions VALUES (27,'brown');
INSERT INTO actions VALUES (28,'drain');
INSERT INTO actions VALUES (29,'set');
INSERT INTO actions VALUES (30,'melt');
INSERT INTO actions VALUES (31,'add');
INSERT INTO actions VALUES (32,'cook');
INSERT INTO actions VALUES (33,'boil');
INSERT INTO actions VALUES (34,'cream');
INSERT INTO actions VALUES (35,'dot');
INSERT INTO actions VALUES (36,'roll');
INSERT INTO actions VALUES (37,'salt');
INSERT INTO actions VALUES (38,'simmer');
INSERT INTO actions VALUES (39,'uncover');
INSERT INTO actions VALUES (40,'serve');
INSERT INTO actions VALUES (41,'empty');
INSERT INTO actions VALUES (42,'remove');
INSERT INTO actions VALUES (43,'chop');
INSERT INTO actions VALUES (44,'use');
INSERT INTO actions VALUES (45,'chill');
INSERT INTO actions VALUES (46,'makes');
INSERT INTO actions VALUES (47,'cut');
INSERT INTO actions VALUES (48,'dissolve');
INSERT INTO actions VALUES (49,'fold in');
INSERT INTO actions VALUES (50,'spoon');
INSERT INTO actions VALUES (51,'unmold');
INSERT INTO actions VALUES (52,'paraffin');
INSERT INTO actions VALUES (53,'clean');
INSERT INTO actions VALUES (54,'flour');
INSERT INTO actions VALUES (55,'drain off');
INSERT INTO actions VALUES (56,'layer');
INSERT INTO actions VALUES (57,'top');
INSERT INTO actions VALUES (58,'freeze');
INSERT INTO actions VALUES (59,'allow');
INSERT INTO actions VALUES (60,'continue');
INSERT INTO actions VALUES (61,'trim off');
INSERT INTO actions VALUES (62,'sift');
INSERT INTO actions VALUES (63,'put in');
INSERT INTO actions VALUES (64,'scrape');
INSERT INTO actions VALUES (65,'buy');
INSERT INTO actions VALUES (66,'marinates');
INSERT INTO actions VALUES (67,'press');
INSERT INTO actions VALUES (68,'says');
INSERT INTO actions VALUES (69,'knows');
INSERT INTO actions VALUES (70,'are');
INSERT INTO actions VALUES (71,'pour off');
INSERT INTO actions VALUES (72,'butter');
INSERT INTO actions VALUES (73,'heat');
INSERT INTO actions VALUES (74,'reduce');
INSERT INTO actions VALUES (75,'batter');
INSERT INTO actions VALUES (76,'roll out');
INSERT INTO actions VALUES (77,'fold over');
INSERT INTO actions VALUES (78,'rolls');
INSERT INTO actions VALUES (79,'yield');
INSERT INTO actions VALUES (80,'punch');
INSERT INTO actions VALUES (81,'slice');
INSERT INTO actions VALUES (82,'leave');
INSERT INTO actions VALUES (83,'dice');
INSERT INTO actions VALUES (84,'nuts');
INSERT INTO actions VALUES (85,'double');
INSERT INTO actions VALUES (86,'grease');
INSERT INTO actions VALUES (87,'beat');
INSERT INTO actions VALUES (88,'comes out');
INSERT INTO actions VALUES (89,'cool');
INSERT INTO actions VALUES (90,'prepare');
INSERT INTO actions VALUES (91,'well');
INSERT INTO actions VALUES (92,'marinate');
INSERT INTO actions VALUES (93,'parboil');
INSERT INTO actions VALUES (94,'pour over');
INSERT INTO actions VALUES (95,'seal in');
INSERT INTO actions VALUES (96,'keeps');
INSERT INTO actions VALUES (97,'sprinkle over');
INSERT INTO actions VALUES (98,'dip');
INSERT INTO actions VALUES (99,'wrap');
INSERT INTO actions VALUES (100,'overbake');
INSERT INTO actions VALUES (101,'drizzle');
INSERT INTO actions VALUES (102,'saute');
INSERT INTO actions VALUES (103,'arrange');
INSERT INTO actions VALUES (104,'shape');
INSERT INTO actions VALUES (105,'push');
INSERT INTO actions VALUES (106,'serves');
INSERT INTO actions VALUES (107,'spoon over');
INSERT INTO actions VALUES (108,'garnish');
INSERT INTO actions VALUES (109,'bowl');
INSERT INTO actions VALUES (110,'combine in');
INSERT INTO actions VALUES (111,'spread on');
INSERT INTO actions VALUES (112,'written');
INSERT INTO actions VALUES (113,'seems');
INSERT INTO actions VALUES (114,'puree');
INSERT INTO actions VALUES (115,'blend');
INSERT INTO actions VALUES (116,'has');
INSERT INTO actions VALUES (117,'fold');
INSERT INTO actions VALUES (118,'peel');
INSERT INTO actions VALUES (119,'mix crush');
INSERT INTO actions VALUES (120,'season');
INSERT INTO actions VALUES (121,'strain');
INSERT INTO actions VALUES (122,'can');
INSERT INTO actions VALUES (123,'coat');
INSERT INTO actions VALUES (124,'transfer');
INSERT INTO actions VALUES (125,'grind');
INSERT INTO actions VALUES (126,'begins');
INSERT INTO actions VALUES (127,'made');
INSERT INTO actions VALUES (128,'hold');
INSERT INTO actions VALUES (129,'pour in');
INSERT INTO actions VALUES (130,'fry');
INSERT INTO actions VALUES (131,'mash');
INSERT INTO actions VALUES (132,'starts');
INSERT INTO actions VALUES (133,'is');
INSERT INTO actions VALUES (134,'fill');
INSERT INTO actions VALUES (135,'have');
INSERT INTO actions VALUES (136,'break up');
INSERT INTO actions VALUES (137,'rise');
INSERT INTO actions VALUES (138,'turn out');
INSERT INTO actions VALUES (139,'roll wrap');
INSERT INTO actions VALUES (140,'pinch');
INSERT INTO actions VALUES (141,'spray');
INSERT INTO actions VALUES (142,'flatten');
INSERT INTO actions VALUES (143,'turn over');
INSERT INTO actions VALUES (144,'preheat');
INSERT INTO actions VALUES (145,'water boiling');
INSERT INTO actions VALUES (146,'turn');
INSERT INTO actions VALUES (147,'get out');
INSERT INTO actions VALUES (148,'put on');
INSERT INTO actions VALUES (149,'cut out');
INSERT INTO actions VALUES (150,'want');
INSERT INTO actions VALUES (151,'squeeze');
INSERT INTO actions VALUES (152,'taste');
INSERT INTO actions VALUES (153,'prefer');
INSERT INTO actions VALUES (154,'freezes');
INSERT INTO actions VALUES (155,'reserve');
INSERT INTO actions VALUES (156,'form');
INSERT INTO actions VALUES (157,'rinse');
INSERT INTO actions VALUES (158,'microcook');
INSERT INTO actions VALUES (159,'stir in');
INSERT INTO actions VALUES (160,'sits');
INSERT INTO actions VALUES (161,'roll in');
INSERT INTO actions VALUES (162,'pat');
INSERT INTO actions VALUES (163,'look');
INSERT INTO actions VALUES (164,'whip');
INSERT INTO actions VALUES (165,'store');
INSERT INTO actions VALUES (166,'eggs');
INSERT INTO actions VALUES (167,'insert');
INSERT INTO actions VALUES (168,'cake');
INSERT INTO actions VALUES (169,'watch');
INSERT INTO actions VALUES (170,'like');
INSERT INTO actions VALUES (171,'changes');
INSERT INTO actions VALUES (172,'oil');
INSERT INTO actions VALUES (173,'press down');
INSERT INTO actions VALUES (174,'reaches');
INSERT INTO actions VALUES (175,'smooth');
INSERT INTO actions VALUES (176,'cup');
INSERT INTO actions VALUES (177,'box');
INSERT INTO actions VALUES (178,'spread out');
INSERT INTO actions VALUES (179,'sounds');
INSERT INTO actions VALUES (180,'size');
INSERT INTO actions VALUES (181,'lower');
INSERT INTO actions VALUES (182,'watch out');
INSERT INTO actions VALUES (183,'lay');
INSERT INTO actions VALUES (184,'roll up');
INSERT INTO actions VALUES (185,'frozen');
INSERT INTO actions VALUES (186,'lunch');
INSERT INTO actions VALUES (187,'knead');
INSERT INTO actions VALUES (188,'smother');
INSERT INTO actions VALUES (189,'dish baking');
INSERT INTO actions VALUES (190,'toss');
INSERT INTO actions VALUES (191,'turn off');
INSERT INTO actions VALUES (192,'puff up');
INSERT INTO actions VALUES (193,'line');
INSERT INTO actions VALUES (194,'brush');
INSERT INTO actions VALUES (195,'halves place bread');
INSERT INTO actions VALUES (196,'cut up');
INSERT INTO actions VALUES (197,'roast');
INSERT INTO actions VALUES (198,'baste');
INSERT INTO actions VALUES (199,'moderate');
INSERT INTO actions VALUES (200,'whisk');
INSERT INTO actions VALUES (201,'finish');
INSERT INTO actions VALUES (202,'spread over');
INSERT INTO actions VALUES (203,'love');
INSERT INTO actions VALUES (204,'frost');
INSERT INTO actions VALUES (205,'find');
INSERT INTO actions VALUES (206,'eaten');
INSERT INTO actions VALUES (207,'goes');
INSERT INTO actions VALUES (208,'spoon in');
INSERT INTO actions VALUES (209,'separate');
INSERT INTO actions VALUES (210,'repeat');
INSERT INTO actions VALUES (211,'time preparation');
INSERT INTO actions VALUES (212,'take');
INSERT INTO actions VALUES (213,'soften');
INSERT INTO actions VALUES (214,'point boiling');
INSERT INTO actions VALUES (215,'sugar');
INSERT INTO actions VALUES (216,'alternate');
INSERT INTO actions VALUES (217,'poke');
INSERT INTO actions VALUES (218,'crush');
INSERT INTO actions VALUES (219,'crack');
INSERT INTO actions VALUES (220,'inch');
INSERT INTO actions VALUES (221,'spices');
INSERT INTO actions VALUES (222,'consider');
INSERT INTO actions VALUES (223,'clean up');
INSERT INTO actions VALUES (224,'bottom');
INSERT INTO actions VALUES (225,'crumble');
INSERT INTO actions VALUES (226,'press out');
INSERT INTO actions VALUES (227,'mine');
INSERT INTO actions VALUES (228,'divide');
INSERT INTO actions VALUES (229,'beat on');
INSERT INTO actions VALUES (230,'enjoy');
INSERT INTO actions VALUES (231,'takes');
INSERT INTO actions VALUES (232,'broil');
INSERT INTO actions VALUES (233,'sprinkle on');
INSERT INTO actions VALUES (234,'pan');
INSERT INTO actions VALUES (235,'handle');
INSERT INTO actions VALUES (236,'turn on');
INSERT INTO actions VALUES (237,'bubbles');
INSERT INTO actions VALUES (238,'add 2');
INSERT INTO actions VALUES (239,'scald');
INSERT INTO actions VALUES (240,'rolls out');
INSERT INTO actions VALUES (241,'process');
INSERT INTO actions VALUES (242,'return');
INSERT INTO actions VALUES (243,'cook over');
INSERT INTO actions VALUES (244,'make out');
INSERT INTO actions VALUES (245,'check');
INSERT INTO actions VALUES (246,'smooth out');
INSERT INTO actions VALUES (247,'stand');
INSERT INTO actions VALUES (248,'thicken');
INSERT INTO actions VALUES (249,'ladle');
INSERT INTO actions VALUES (250,'seal');
INSERT INTO actions VALUES (251,'open');
INSERT INTO actions VALUES (252,'slip');
INSERT INTO actions VALUES (253,'iron');
INSERT INTO actions VALUES (254,'leaves');
INSERT INTO actions VALUES (255,'soak');
INSERT INTO actions VALUES (256,'drop over');
INSERT INTO actions VALUES (257,'test');
INSERT INTO actions VALUES (258,'break');
INSERT INTO actions VALUES (259,'shake');
INSERT INTO actions VALUES (260,'better');
INSERT INTO actions VALUES (261,'measure out');
INSERT INTO actions VALUES (262,'strip');
INSERT INTO actions VALUES (263,'decorate');
INSERT INTO actions VALUES (264,'press up');
INSERT INTO actions VALUES (265,'glass');
INSERT INTO actions VALUES (266,'parties');
INSERT INTO actions VALUES (267,'stack');
INSERT INTO actions VALUES (268,'note');
INSERT INTO actions VALUES (269,'mix together');
INSERT INTO actions VALUES (270,'measure');
INSERT INTO actions VALUES (271,'out');
INSERT INTO actions VALUES (272,'toast');
INSERT INTO actions VALUES (273,'start');
INSERT INTO actions VALUES (274,'rises');
INSERT INTO actions VALUES (275,'pack');
INSERT INTO actions VALUES (276,'follow');
INSERT INTO actions VALUES (277,'sear');
INSERT INTO actions VALUES (278,'blot');
INSERT INTO actions VALUES (279,'do');
INSERT INTO actions VALUES (280,'batches');
INSERT INTO actions VALUES (281,'milk');
INSERT INTO actions VALUES (282,'sprinkle in');
INSERT INTO actions VALUES (283,'skin');
INSERT INTO actions VALUES (284,'fat');
INSERT INTO actions VALUES (285,'poke down');
INSERT INTO actions VALUES (286,'beat in');
INSERT INTO actions VALUES (287,'begin');
INSERT INTO actions VALUES (288,'harden');
INSERT INTO actions VALUES (289,'spray cooking');
INSERT INTO actions VALUES (290,'fit');
INSERT INTO actions VALUES (291,'shown');
INSERT INTO actions VALUES (292,'sheet cookie');
INSERT INTO actions VALUES (293,'room');
INSERT INTO actions VALUES (294,'leave out');
INSERT INTO actions VALUES (295,'round');
INSERT INTO actions VALUES (296,'still');
INSERT INTO actions VALUES (297,'wait');
INSERT INTO actions VALUES (298,'work');
INSERT INTO actions VALUES (299,'explode');
INSERT INTO actions VALUES (300,'improvise');
INSERT INTO actions VALUES (301,'experiment');
INSERT INTO actions VALUES (302,'keep up');
INSERT INTO actions VALUES (303,'broccoli cook');
INSERT INTO actions VALUES (304,'float');
INSERT INTO actions VALUES (305,'create');
INSERT INTO actions VALUES (306,'save');
INSERT INTO actions VALUES (307,'overcook');
INSERT INTO actions VALUES (308,'lift');
INSERT INTO actions VALUES (309,'sit');
INSERT INTO actions VALUES (310,'please');
INSERT INTO actions VALUES (311,'broken up');
INSERT INTO actions VALUES (312,'grate');
INSERT INTO actions VALUES (313,'beaten');
INSERT INTO actions VALUES (314,'will');
INSERT INTO actions VALUES (315,'run down');
INSERT INTO actions VALUES (316,'broccoli boil');
INSERT INTO actions VALUES (317,'cube');
INSERT INTO actions VALUES (318,'best');
INSERT INTO actions VALUES (319,'stick');
INSERT INTO actions VALUES (320,'tear');
INSERT INTO actions VALUES (321,'cool down');
INSERT INTO actions VALUES (322,'take out');
INSERT INTO actions VALUES (323,'skim');
INSERT INTO actions VALUES (324,'crusts');
INSERT INTO actions VALUES (325,'stir fry');
INSERT INTO actions VALUES (326,'broken');
INSERT INTO actions VALUES (327,'stems');
INSERT INTO actions VALUES (328,'be');
INSERT INTO actions VALUES (329,'foil');
INSERT INTO actions VALUES (330,'invert');
INSERT INTO actions VALUES (331,'serve over');
INSERT INTO actions VALUES (332,'rotate');
INSERT INTO actions VALUES (333,'shallow');
INSERT INTO actions VALUES (334,'get');
INSERT INTO actions VALUES (335,'advance');
INSERT INTO actions VALUES (336,'breast chicken');
INSERT INTO actions VALUES (337,'boils');
INSERT INTO actions VALUES (338,'ice');
INSERT INTO actions VALUES (339,'back');
INSERT INTO actions VALUES (340,'crumbles');
INSERT INTO actions VALUES (341,'ham');
INSERT INTO actions VALUES (342,'nut');
INSERT INTO actions VALUES (343,'prevent');
INSERT INTO actions VALUES (344,'remember');
INSERT INTO actions VALUES (345,'dust');
INSERT INTO actions VALUES (346,'rest');
INSERT INTO actions VALUES (347,'layers christmas');
INSERT INTO actions VALUES (348,'time');
INSERT INTO actions VALUES (349,'fork');
INSERT INTO actions VALUES (350,'muffins');
INSERT INTO actions VALUES (351,'contains');
INSERT INTO actions VALUES (352,'ready');
INSERT INTO actions VALUES (353,'thickens');
INSERT INTO actions VALUES (354,'heat through');
INSERT INTO actions VALUES (355,'rub');
INSERT INTO actions VALUES (356,'crepes leftover');
INSERT INTO actions VALUES (357,'onions');
INSERT INTO actions VALUES (358,'tie');
INSERT INTO actions VALUES (359,'cuts');
INSERT INTO actions VALUES (360,'slit');
INSERT INTO actions VALUES (361,'throw in');
INSERT INTO actions VALUES (362,'cut along');
INSERT INTO actions VALUES (363,'clear');
INSERT INTO actions VALUES (364,'needs');
INSERT INTO actions VALUES (365,'moisten');
INSERT INTO actions VALUES (366,'stick cinnamon');
INSERT INTO actions VALUES (367,'diet');
INSERT INTO actions VALUES (368,'fat gm');
INSERT INTO actions VALUES (369,'pineapple');
INSERT INTO actions VALUES (370,'logs');
INSERT INTO actions VALUES (371,'plain');
INSERT INTO actions VALUES (372,'thaw');
INSERT INTO actions VALUES (373,'dish quart casserole');
INSERT INTO actions VALUES (374,'party cocktail');
INSERT INTO actions VALUES (375,'pour out');
INSERT INTO actions VALUES (376,'second');
INSERT INTO actions VALUES (377,'leave on');
INSERT INTO actions VALUES (378,'secure');
INSERT INTO actions VALUES (379,'draw');
INSERT INTO actions VALUES (380,'lime');
INSERT INTO actions VALUES (381,'try');
INSERT INTO actions VALUES (382,'cans coffee');
INSERT INTO actions VALUES (383,'spread across');
INSERT INTO actions VALUES (384,'pound');
INSERT INTO actions VALUES (385,'rolls chicken');
INSERT INTO actions VALUES (386,'stir down');
INSERT INTO actions VALUES (387,'balls');
INSERT INTO actions VALUES (388,'dredge');
INSERT INTO actions VALUES (389,'carve');
INSERT INTO actions VALUES (390,'disappears');
INSERT INTO actions VALUES (391,'directs recipe');
INSERT INTO actions VALUES (392,'toss in');
INSERT INTO actions VALUES (393,'crabmeat');
INSERT INTO actions VALUES (394,'total');
INSERT INTO actions VALUES (395,'enhances');
INSERT INTO actions VALUES (396,'sauce');
INSERT INTO actions VALUES (397,'gets');
INSERT INTO actions VALUES (398,'whoop');
INSERT INTO actions VALUES (399,'loosen');
INSERT INTO actions VALUES (400,'adjust');
INSERT INTO actions VALUES (401,'time baking');
INSERT INTO actions VALUES (402,'open 2');
INSERT INTO actions VALUES (403,'pot');
INSERT INTO actions VALUES (404,'kiss');
INSERT INTO actions VALUES (405,'cookies');
INSERT INTO actions VALUES (406,'layer first');
INSERT INTO actions VALUES (407,'sheet');
INSERT INTO actions VALUES (408,'fish out');
INSERT INTO actions VALUES (409,'pat down');
INSERT INTO actions VALUES (410,'arrange down');
INSERT INTO actions VALUES (411,'tells');
INSERT INTO actions VALUES (412,'stew');
INSERT INTO actions VALUES (413,'drop out');
INSERT INTO actions VALUES (414,'light');
INSERT INTO actions VALUES (415,'cover over');
INSERT INTO actions VALUES (416,'feels');
INSERT INTO actions VALUES (417,'house');
INSERT INTO actions VALUES (418,'drink');
INSERT INTO actions VALUES (419,'soup');
INSERT INTO actions VALUES (420,'cut outside');
INSERT INTO actions VALUES (421,'ends');
INSERT INTO actions VALUES (422,'expand');
INSERT INTO actions VALUES (423,'firms up');
INSERT INTO actions VALUES (424,'low');
INSERT INTO actions VALUES (425,'servings');
INSERT INTO actions VALUES (426,'pour up');
INSERT INTO actions VALUES (427,'wish');
INSERT INTO actions VALUES (428,'dates');
INSERT INTO actions VALUES (429,'squash');
INSERT INTO actions VALUES (430,'spoon off');
INSERT INTO actions VALUES (431,'dish casserole');
INSERT INTO actions VALUES (432,'pepper');
INSERT INTO actions VALUES (433,'equals');
INSERT INTO actions VALUES (434,'water');
INSERT INTO actions VALUES (435,'play');
INSERT INTO actions VALUES (436,'burn');
INSERT INTO actions VALUES (437,'crimp');
INSERT INTO actions VALUES (438,'dough');
INSERT INTO actions VALUES (439,'strips');
INSERT INTO actions VALUES (440,'fix');
INSERT INTO actions VALUES (441,'dish');
INSERT INTO actions VALUES (442,'flip');
INSERT INTO actions VALUES (443,'pop');
INSERT INTO actions VALUES (444,'strain out');
INSERT INTO actions VALUES (445,'drops');
INSERT INTO actions VALUES (446,'fall');
INSERT INTO actions VALUES (447,'glaze');
INSERT INTO actions VALUES (448,'stuck');
INSERT INTO actions VALUES (449,'had');
INSERT INTO actions VALUES (450,'remains');
INSERT INTO actions VALUES (451,'brunch');
INSERT INTO actions VALUES (452,'helps');
INSERT INTO actions VALUES (453,'rack');
INSERT INTO actions VALUES (454,'peel off');
INSERT INTO actions VALUES (455,'twist');
INSERT INTO actions VALUES (456,'tamales drain');
INSERT INTO actions VALUES (457,'avoid');
INSERT INTO actions VALUES (458,'turns');
INSERT INTO actions VALUES (459,'run');
INSERT INTO actions VALUES (460,'hands');
INSERT INTO actions VALUES (461,'oleo');
INSERT INTO actions VALUES (462,'coats');
INSERT INTO actions VALUES (463,'trim');
INSERT INTO actions VALUES (464,'reshape');
INSERT INTO actions VALUES (465,'leak');
INSERT INTO actions VALUES (466,'sets');
INSERT INTO actions VALUES (467,'time cooking');
INSERT INTO actions VALUES (468,'done');
INSERT INTO actions VALUES (469,'anchor');
INSERT INTO actions VALUES (470,'unroll');
INSERT INTO actions VALUES (471,'brought');
INSERT INTO actions VALUES (472,'course');
INSERT INTO actions VALUES (473,'cooks');
INSERT INTO actions VALUES (474,'leave in');
INSERT INTO actions VALUES (475,'ranch');
INSERT INTO actions VALUES (476,'pull');
INSERT INTO actions VALUES (477,'crust');
INSERT INTO actions VALUES (478,'gather');
INSERT INTO actions VALUES (479,'gone');
INSERT INTO actions VALUES (480,'halves bagel');
INSERT INTO actions VALUES (481,'lukewarm');
INSERT INTO actions VALUES (482,'break off');
INSERT INTO actions VALUES (483,'leak out');
INSERT INTO actions VALUES (484,'spins');
INSERT INTO actions VALUES (485,'distribute');
INSERT INTO actions VALUES (486,'stuff');
INSERT INTO actions VALUES (487,'meat');
INSERT INTO actions VALUES (488,'release');
INSERT INTO actions VALUES (489,'scoop up');
INSERT INTO actions VALUES (490,'does');
INSERT INTO actions VALUES (491,'left');
INSERT INTO actions VALUES (492,'edges');
INSERT INTO actions VALUES (493,'kitten feed');
INSERT INTO actions VALUES (494,'dash');
INSERT INTO actions VALUES (495,'fasten');
INSERT INTO actions VALUES (496,'comes');
INSERT INTO actions VALUES (497,'hand');
INSERT INTO actions VALUES (498,'raisins');
INSERT INTO actions VALUES (499,'grill');
INSERT INTO actions VALUES (500,'mold');
INSERT INTO actions VALUES (501,'tastes');
INSERT INTO actions VALUES (502,'spoon out');
INSERT INTO actions VALUES (503,'swirl');
INSERT INTO actions VALUES (504,'ends off');
INSERT INTO actions VALUES (505,'gives');
INSERT INTO actions VALUES (506,'overbeat');
INSERT INTO actions VALUES (507,'scramble');
INSERT INTO actions VALUES (508,'quarter');
INSERT INTO actions VALUES (509,'looks');
INSERT INTO actions VALUES (510,'touch');
INSERT INTO actions VALUES (511,'sauce cook');
INSERT INTO actions VALUES (512,'rinse off');
INSERT INTO actions VALUES (513,'bit');
INSERT INTO actions VALUES (514,'close');
INSERT INTO actions VALUES (515,'tear up');
INSERT INTO actions VALUES (516,'score');
INSERT INTO actions VALUES (517,'tie up');
INSERT INTO actions VALUES (518,'come out');
INSERT INTO actions VALUES (519,'omit');
INSERT INTO actions VALUES (520,'increase');
INSERT INTO actions VALUES (521,'perk');
INSERT INTO actions VALUES (522,'punch out');
INSERT INTO actions VALUES (523,'buzz');
INSERT INTO actions VALUES (524,'feeds');
INSERT INTO actions VALUES (525,'overmix');
INSERT INTO actions VALUES (526,'hurry');
INSERT INTO actions VALUES (527,'pipe');
INSERT INTO actions VALUES (528,'assemble');
INSERT INTO actions VALUES (529,'seem');
INSERT INTO actions VALUES (530,'fill in');
INSERT INTO actions VALUES (531,'congeal');
INSERT INTO actions VALUES (532,'avocado');
INSERT INTO actions VALUES (533,'see');
INSERT INTO actions VALUES (534,'end');
INSERT INTO actions VALUES (535,'dunk');
INSERT INTO actions VALUES (536,'turn shrimp');
INSERT INTO actions VALUES (537,'firm');
INSERT INTO actions VALUES (538,'go on');
INSERT INTO actions VALUES (539,'blanch');
INSERT INTO actions VALUES (540,'refresh');
INSERT INTO actions VALUES (541,'simmer on');
INSERT INTO actions VALUES (542,'dry out');
INSERT INTO actions VALUES (543,'pass');
INSERT INTO actions VALUES (544,'corn');
