
DROP TABLE IF EXISTS contains;
CREATE TABLE contains(
id SERIAL PRIMARY KEY,
misura VARCHAR,
quantita FLOAT,
proprieta VARCHAR,
recipeID INT NOT NULL,
ingredientID INT NOT NULL,
FOREIGN KEY (recipeID) REFERENCES recipes(id),
FOREIGN KEY (ingredientID) REFERENCES ingredients(id)
);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'',0, 2);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',16.0,'frozen',1, 4);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package ounce',8.0,'',1, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1,'cubed',1, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.5,'',1, 7);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.5,'',1, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.25,'',1, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',10.5,'',2, 11);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can ounce',10.5,'',2, 2);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',6.0,'',2, 12);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',4.0,'shredded',2, 13);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',3, 14);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.75,'crumbs',3, 15);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'melted',3, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.5,'powdered',3, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',1.0,'large',3, 17);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.6666666666666666,'',4, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',6.0,'',4, 20);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.75,'',4, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.5,'',4, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',1.5,'divided, shredded',4, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.5,'',5, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',5, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',5, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'',5, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.5,'',5, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',5, 28);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',5, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',5, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'whole',6, 31);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'drained',7, 33);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.75,'',7, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',7, 35);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.5,'',7, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'',7, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'crushed',8, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'condensed',8, 20);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',8, 42);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can ounce',17.0,'dark, pitted',9, 44);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',9, 45);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package ounce',6.0,'',9, 46);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'',9, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.125,'',9, 47);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'miniature',9, 48);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',8.0,'soft',10, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',8.0,'',10, 14);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',12.0,'',10, 17);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',8.0,'',12, 52);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',8.0,'',12, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',8.0,'',12, 53);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',1.0,'',12, 0);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',1.0,'',12, 54);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'crushed',13, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'sweetened, condensed',13, 20);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',8.0,'whipped, thawed',13, 60);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',13, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('quart',1.0,'cleaned',14, 63);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.5,'',14, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',4.0,'',14, 64);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',14, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.125,'',14, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',4.0,'',14, 65);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',0.5,'',15, 66);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',0.5,'',15, 67);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'',15, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',2.5,'pound, broccoliabout, large',16, 68);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',5.25,'red, chopped',16, 70);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',16, 71);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',16, 72);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',16, 73);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'',16, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',1.0,'frozen',17, 74);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'crushed',17, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'chopped',17, 42);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',1.0,'large',17, 76);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.5,'',17, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pint',1.0,'',17, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.75,'',18, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.5,'',18, 77);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',3.0,'',18, 28);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'sifted',18, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',18, 71);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',18, 79);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',19, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',19, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',2.0,'',19, 28);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'',19, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'',19, 79);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',1.0,'',20, 80);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',1.0,'',20, 81);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',8.0,'',20, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.75,'',20, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',20, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',6.0,'chopped',20, 83);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',21, 85);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',22, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.5,'minced',22, 88);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.5,'',22, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',22, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'',22, 90);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon tablespoon',3.0,'italian',22, 91);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',1.5,'',23, 0);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',23, 92);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.75,'',23, 93);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'chopped',23, 57);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.25,'',23, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.5,'',23, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',2.0,'',24, 94);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.5,'black',24, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',24, 95);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',24, 85);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',24, 97);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',2.0,'',24, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'red',24, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',2.5,'sliced, thickor, thick',25, 94);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',25, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',1.0,'',25, 100);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1,'',25, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',25, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'prepared',25, 101);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'',25, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can ounce',14.0,'sweetened, condensed',26, 20);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package ounce',12.0,'',26, 102);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',26, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',1.0,'',27, 0);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',1.0,'',27, 54);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',28, 20);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',28, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',1.0,'dry',28, 107);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'',28, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',3.0,'',28, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'diced',29, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('quart',1.0,'fresh',29, 63);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',1.0,'',29, 112);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',1.0,'purple',29, 113);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',1.0,'',30, 114);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',30, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1,'red',30, 73);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon tablespoon',4.0,'',30, 115);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',31, 79);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',32, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.25,'',32, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'',32, 119);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',3.0,'coarse, shredded',32, 18);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'shredded',32, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1,'',32, 70);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'',33, 121);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',34, 72);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',34, 124);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',16.0,'',35, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',1.0,'dry',35, 125);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package ounce',10.0,'thawed, chopped, frozen',35, 126);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',10.0,'',35, 106);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package ounce',3.0,'',37, 130);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package ounce',8.0,'softened',37, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',8.0,'',37, 131);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',7.0,'',38, 132);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',7.0,'',38, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'',38, 133);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.5,'',38, 134);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.5,'',38, 135);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',3.0,'',39, 10);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can ounce',16.0,'creamed',39, 31);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can ounce',16.0,'',39, 136);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can ounce',16.0,'field',39, 137);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can ounce',16.0,'',39, 138);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can ounce',16.0,'',39, 33);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can ounce',46.0,'',39, 92);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'black',39, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'',39, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'',39, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',3.0,'softened',40, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'granulated',40, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',40, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.25,'',40, 139);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.25,'',40, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1,'',40, 20);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.25,'',40, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1,'packed',40, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.5,'',40, 140);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',40, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',5.0,'',41, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',3.0,'',41, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',4.0,'',41, 139);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',1.5,'dry',41, 107);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'',41, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',41, 28);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'warm',41, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'crushed',42, 142);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'',42, 143);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'',43, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'brown',43, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',44, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',44, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'chocolate',44, 146);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',3.0,'rising',45, 147);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'',45, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'',46, 148);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'',46, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.125,'',46, 149);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'sliced',46, 150);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'',46, 151);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',1.0,'chopped',46, 126);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.5,'sifted',47, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.5,'',47, 139);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.5,'',47, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',47, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.6666666666666666,'',47, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',47, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',0.5,'',48, 0);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'',48, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',48, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',1.0,'mixdry',48, 155);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can pound',1.0,'stewed',48, 33);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can ounce',8.0,'',48, 100);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package ounce',10.0,'frozen, mixed',48, 156);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'',49, 2);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'',49, 158);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',49, 20);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',1.0,'',49, 159);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',4.0,'shredded',50, 160);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'shredded',50, 161);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'chopped',50, 58);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'chopped',50, 57);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',50, 72);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'',50, 73);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',2.0,'',50, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',50, 162);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.25,'',50, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',2.0,'',51, 163);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'chopped',51, 58);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1,'',51, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'',51, 165);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',2.0,'',51, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',2.0,'minced',51, 57);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',51, 166);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.25,'black, ground',51, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'',52, 169);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'yellow',52, 103);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'',52, 103);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',52, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',52, 165);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.6666666666666666,'',52, 73);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1,'',52, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',16.5,'',53, 170);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',8.0,'',53, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package ounce',8.5,'',53, 171);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',1.0,'',54, 0);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1,'chopped',54, 57);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'',54, 173);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'cooked, wide',54, 174);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon teaspoon',0.5,'',54, 175);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1,'',54, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',54, 13);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'dry',55, 101);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'flaked, corned',55, 0);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'',55, 151);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'',56, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'dry',56, 101);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',56, 72);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package ounce',8.0,'softened',57, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',57, 177);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',57, 179);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',57, 106);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'black',57, 180);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',0.5,'soft',58, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',58, 14);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',0.5,'crumbs',58, 15);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'',58, 182);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',58, 183);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',1.0,'sliced',59, 185);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'chopped',59, 42);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',59, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',59, 186);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',8.0,'softened',60, 53);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',1.0,'powdered',60, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'chunk',61, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'',62, 2);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'',62, 151);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'melted',62, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package ounce',8.0,'',63, 53);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'sweetened, condensed',63, 20);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'crushed',63, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1,'chopped',63, 79);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1,'',63, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',64, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',64, 14);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.25,'',65, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.25,'',65, 190);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'',65, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.75,'',65, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',16.0,'cool',66, 39);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.75,'',66, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',12.0,'',66, 53);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.5,'crumbs',67, 15);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'granulated',67, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'sifted',68, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.5,'',68, 28);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.25,'',68, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.5,'',68, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',68, 193);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',68, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',68, 20);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'',69, 71);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'brown',69, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'granulated',69, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',3.0,'',69, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',2.0,'',69, 28);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',69, 140);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',69, 195);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',69, 196);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',69, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',69, 79);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',6.0,'diced',70, 18);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'chopped',70, 57);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.75,'melted',70, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',8.0,'',70, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.6666666666666665,'',72, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',72, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',73, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',73, 140);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'',73, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',73, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',73, 202);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'',74, 204);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',1.0,'',74, 205);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package ounce',8.0,'',74, 106);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'',75, 207);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'',75, 208);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',76, 99);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',76, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',1.0,'',76, 0);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',76, 73);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',76, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',76, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.5,'',76, 101);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',76, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.5,'',76, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',76, 209);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',76, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',13.75,'',77, 210);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'',77, 64);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',77, 23);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('gallon',0.5,'',78, 211);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',78, 212);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'whole',78, 196);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',78, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'',79, 214);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',2.0,'grated',79, 215);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',79, 216);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'reduced',79, 217);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',4.0,'skinned',79, 218);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',16.0,'fresh',80, 221);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',81, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package ounce',3.0,'',81, 227);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',81, 228);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'',82, 229);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'french',82, 230);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can ounce',4.0,'',82, 231);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package ounce',3.0,'softened',83, 53);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',83, 148);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',83, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can ounce',16.0,'',83, 232);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.75,'drained, crushed',83, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'chopped',83, 233);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',2.0,'',84, 235);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',15.0,'can, italian',84, 33);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',3.5,'',84, 237);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.3333333333333333,'',85, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.25,'',85, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.5,'',85, 28);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',85, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',0.75,'',85, 139);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.6666666666666666,'',85, 238);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',4.0,'',86, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',86, 193);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',1.0,'',86, 239);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'',86, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',3.0,'',87, 240);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pint',1.0,'',87, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',1.0,'',87, 242);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',2.0,'',88, 53);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',2.0,'shredded',88, 243);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'chopped',88, 244);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'chopped',88, 58);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'chopped',88, 57);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',88, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',2.0,'',88, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package',1.0,'large',89, 246);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.6666666666666666,'',89, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('package ounce',8.0,'',89, 53);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'evaporated',89, 20);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.6666666666666666,'',89, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',3.0,'substituted, plain, flourcake, plain',90, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',3.0,'',90, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.5,'',90, 139);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',90, 250);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',6.0,'',90, 252);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',91, 148);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'brown',91, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',91, 20);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can ounce',8.0,'',92, 255);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.5,'medium, grated',92, 13);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.5,'',92, 20);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('can',1.0,'corned',93, 0);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'grated',93, 106);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',1.0,'',94, 257);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'chopped',94, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'chopped',94, 35);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.75,'',94, 209);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1,'',94, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1.0,'',94, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',1,'black',94, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('pound',1.0,'',94, 0);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'',94, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'diced, cooked',95, 10);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',95, 258);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',2.0,'',95, 259);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.25,'',95, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'brown, packed',95, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',95, 64);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('teaspoon',0.25,'',95, 215);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'',95, 209);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',2.0,'',95, 73);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('tablespoon',1.0,'',95, 217);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',95, 261);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('ounce',8.0,'',95, 262);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'moist',96, 182);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',96, 42);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.5,'',96, 264);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',0.25,'',96, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',96, 265);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'creamy',97, 14);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('cup',1.0,'',97, 16);
