
USE recipe_analysis;
DROP TABLE IF EXISTS instruments;
CREATE TABLE instruments(
id INT PRIMARY KEY,
name VARCHAR(100) NOT NULL
);
INSERT INTO ingredients VALUES (0,"bottom");
INSERT INTO ingredients VALUES (1,"baking dish");
INSERT INTO ingredients VALUES (2,"low");
INSERT INTO ingredients VALUES (3,"casserole dish");
INSERT INTO ingredients VALUES (4,"box");
INSERT INTO ingredients VALUES (5,"ungreased pan");
INSERT INTO ingredients VALUES (6,"refrigerator");
INSERT INTO ingredients VALUES (7,"fork");
INSERT INTO ingredients VALUES (8,"paper towel");
INSERT INTO ingredients VALUES (9,"kettle");
INSERT INTO ingredients VALUES (10,"ground");
INSERT INTO ingredients VALUES (11,"mixture");
INSERT INTO ingredients VALUES (12,"teaspoons");
INSERT INTO ingredients VALUES (13,"place");
INSERT INTO ingredients VALUES (14,"skillet");
INSERT INTO ingredients VALUES (15,"bowl");
INSERT INTO ingredients VALUES (16,"crust");
INSERT INTO ingredients VALUES (17,"mold");
INSERT INTO ingredients VALUES (18,"balls");
INSERT INTO ingredients VALUES (19,"cookie sheet");
INSERT INTO ingredients VALUES (20,"freezer");
INSERT INTO ingredients VALUES (21,"boiler");
INSERT INTO ingredients VALUES (22,"way");
INSERT INTO ingredients VALUES (23,"chip");
INSERT INTO ingredients VALUES (24,"microwave bowl");
INSERT INTO ingredients VALUES (25,"pizza pan");
INSERT INTO ingredients VALUES (26,"13-inch pan");
INSERT INTO ingredients VALUES (27,"saucepan");
INSERT INTO ingredients VALUES (28,"stalks");
INSERT INTO ingredients VALUES (29,"bite size");
INSERT INTO ingredients VALUES (30,"pan");
INSERT INTO ingredients VALUES (31,"loaf pan");
INSERT INTO ingredients VALUES (32,"hand");
INSERT INTO ingredients VALUES (33,"processor");
INSERT INTO ingredients VALUES (34,"ingredients");
INSERT INTO ingredients VALUES (35,"seal");
INSERT INTO ingredients VALUES (36,"oven");
INSERT INTO ingredients VALUES (37,"game");
INSERT INTO ingredients VALUES (38,"world");
INSERT INTO ingredients VALUES (39,"liquid");
INSERT INTO ingredients VALUES (40,"kidney");
INSERT INTO ingredients VALUES (41,"board");
INSERT INTO ingredients VALUES (42,"biscuit cutter");
INSERT INTO ingredients VALUES (43,"fruit");
INSERT INTO ingredients VALUES (44,"center");
INSERT INTO ingredients VALUES (45,"rack");
INSERT INTO ingredients VALUES (46,"squares");
INSERT INTO ingredients VALUES (47,"mixer");
INSERT INTO ingredients VALUES (48,"pears");
INSERT INTO ingredients VALUES (49,"dish");
INSERT INTO ingredients VALUES (50,"baking pan");
INSERT INTO ingredients VALUES (51,"tablespoons");
INSERT INTO ingredients VALUES (52,"dough");
INSERT INTO ingredients VALUES (53,"muffin tin");
INSERT INTO ingredients VALUES (54,"pizza pans");
INSERT INTO ingredients VALUES (55,"mint layer");
INSERT INTO ingredients VALUES (56,"microwave");
INSERT INTO ingredients VALUES (57,"baking sheets");
INSERT INTO ingredients VALUES (58,"racks");
INSERT INTO ingredients VALUES (59,"pot");
INSERT INTO ingredients VALUES (60,"store");
INSERT INTO ingredients VALUES (61,"layer");
INSERT INTO ingredients VALUES (62,"seasonings");
INSERT INTO ingredients VALUES (63,"casserole");
INSERT INTO ingredients VALUES (64,"time");
INSERT INTO ingredients VALUES (65,"order");
INSERT INTO ingredients VALUES (66,"hands");
INSERT INTO ingredients VALUES (67,"buttered pan");
INSERT INTO ingredients VALUES (68,"paper");
INSERT INTO ingredients VALUES (69,"chill");
INSERT INTO ingredients VALUES (70,"servings");
INSERT INTO ingredients VALUES (71,"dollop");
INSERT INTO ingredients VALUES (72,"peanuts");
INSERT INTO ingredients VALUES (73,"blender");
INSERT INTO ingredients VALUES (74,"container");
INSERT INTO ingredients VALUES (75,"blueberries");
INSERT INTO ingredients VALUES (76,"batter");
INSERT INTO ingredients VALUES (77,"pans");
INSERT INTO ingredients VALUES (78,"tube pan");
INSERT INTO ingredients VALUES (79,"paper towels");
INSERT INTO ingredients VALUES (80,"buttered platter");
INSERT INTO ingredients VALUES (81,"size balls");
INSERT INTO ingredients VALUES (82,"mugs");
INSERT INTO ingredients VALUES (83,"guests");
INSERT INTO ingredients VALUES (84,"pin");
INSERT INTO ingredients VALUES (85,"grill");
INSERT INTO ingredients VALUES (86,"side");
INSERT INTO ingredients VALUES (87,"funnel");
INSERT INTO ingredients VALUES (88,"motion");
INSERT INTO ingredients VALUES (89,"inch");
INSERT INTO ingredients VALUES (90,"ball");
INSERT INTO ingredients VALUES (91,"baby");
INSERT INTO ingredients VALUES (92,"crock pot");
INSERT INTO ingredients VALUES (93,"hair");
