
DROP TABLE IF EXISTS actions;
CREATE TABLE actions(
id SERIAL PRIMARY KEY,
name VARCHAR NOT NULL
);
INSERT INTO actions VALUES (0,'mix');
INSERT INTO actions VALUES (1,'stir');
INSERT INTO actions VALUES (2,'boil');
INSERT INTO actions VALUES (3,'take off');
INSERT INTO actions VALUES (4,'shape');
INSERT INTO actions VALUES (5,'let');
INSERT INTO actions VALUES (6,'place');
INSERT INTO actions VALUES (7,'pour');
INSERT INTO actions VALUES (8,'bake');
INSERT INTO actions VALUES (9,'combine');
INSERT INTO actions VALUES (10,'cover');
INSERT INTO actions VALUES (11,'yields');
INSERT INTO actions VALUES (12,'put');
INSERT INTO actions VALUES (13,'level');
INSERT INTO actions VALUES (14,'make');
INSERT INTO actions VALUES (15,'sprinkle');
INSERT INTO actions VALUES (16,'spread');
INSERT INTO actions VALUES (17,'refrigerate');
INSERT INTO actions VALUES (18,'keep');
INSERT INTO actions VALUES (19,'wash');
INSERT INTO actions VALUES (20,'prick');
INSERT INTO actions VALUES (21,'microwave');
INSERT INTO actions VALUES (22,'should');
INSERT INTO actions VALUES (23,'cut');
INSERT INTO actions VALUES (24,'scoop out');
INSERT INTO actions VALUES (25,'discard');
INSERT INTO actions VALUES (26,'brown');
INSERT INTO actions VALUES (27,'drain');
INSERT INTO actions VALUES (28,'set');
INSERT INTO actions VALUES (29,'melt');
INSERT INTO actions VALUES (30,'add');
INSERT INTO actions VALUES (31,'cook');
INSERT INTO actions VALUES (32,'cream');
INSERT INTO actions VALUES (33,'dot');
INSERT INTO actions VALUES (34,'roll');
INSERT INTO actions VALUES (35,'salt');
INSERT INTO actions VALUES (36,'uncover');
INSERT INTO actions VALUES (37,'serve over');
INSERT INTO actions VALUES (38,'empty');
INSERT INTO actions VALUES (39,'squeeze');
INSERT INTO actions VALUES (40,'chop');
INSERT INTO actions VALUES (41,'use');
INSERT INTO actions VALUES (42,'chill');
INSERT INTO actions VALUES (43,'makes');
INSERT INTO actions VALUES (44,'dissolve');
INSERT INTO actions VALUES (45,'fold');
INSERT INTO actions VALUES (46,'spoon');
INSERT INTO actions VALUES (47,'paraffin');
INSERT INTO actions VALUES (48,'clean');
INSERT INTO actions VALUES (49,'fry');
INSERT INTO actions VALUES (50,'drain off');
INSERT INTO actions VALUES (51,'layer');
INSERT INTO actions VALUES (52,'top');
INSERT INTO actions VALUES (53,'serve');
INSERT INTO actions VALUES (54,'freeze');
INSERT INTO actions VALUES (55,'allow');
INSERT INTO actions VALUES (56,'remove');
INSERT INTO actions VALUES (57,'continue');
INSERT INTO actions VALUES (58,'trim off');
INSERT INTO actions VALUES (59,'put in');
INSERT INTO actions VALUES (60,'scrape');
INSERT INTO actions VALUES (61,'last');
INSERT INTO actions VALUES (62,'buy');
INSERT INTO actions VALUES (63,'marinates');
INSERT INTO actions VALUES (64,'press');
INSERT INTO actions VALUES (65,'says');
INSERT INTO actions VALUES (66,'knows');
INSERT INTO actions VALUES (67,'are');
INSERT INTO actions VALUES (68,'pour off');
INSERT INTO actions VALUES (69,'butter');
INSERT INTO actions VALUES (70,'heat');
INSERT INTO actions VALUES (71,'reduce');
INSERT INTO actions VALUES (72,'batter');
INSERT INTO actions VALUES (73,'roll out');
INSERT INTO actions VALUES (74,'brush');
INSERT INTO actions VALUES (75,'rolls');
INSERT INTO actions VALUES (76,'yield');
INSERT INTO actions VALUES (77,'punch');
INSERT INTO actions VALUES (78,'slice');
INSERT INTO actions VALUES (79,'leave');
INSERT INTO actions VALUES (80,'dice');
INSERT INTO actions VALUES (81,'may');
INSERT INTO actions VALUES (82,'double');
INSERT INTO actions VALUES (83,'grease');
INSERT INTO actions VALUES (84,'pour over');
INSERT INTO actions VALUES (85,'beat');
INSERT INTO actions VALUES (86,'cool');
INSERT INTO actions VALUES (87,'prepare');
INSERT INTO actions VALUES (88,'well');
INSERT INTO actions VALUES (89,'marinate');
INSERT INTO actions VALUES (90,'parboil');
INSERT INTO actions VALUES (91,'seal');
INSERT INTO actions VALUES (92,'keeps');
INSERT INTO actions VALUES (93,'dip');
INSERT INTO actions VALUES (94,'wrap');
INSERT INTO actions VALUES (95,'overbake');
INSERT INTO actions VALUES (96,'drizzle');
INSERT INTO actions VALUES (97,'saute');
INSERT INTO actions VALUES (98,'arrange');
INSERT INTO actions VALUES (99,'sift');
INSERT INTO actions VALUES (100,'push');
INSERT INTO actions VALUES (101,'serves');
INSERT INTO actions VALUES (102,'oven heat');
INSERT INTO actions VALUES (103,'garnish');
INSERT INTO actions VALUES (104,'bowl');
INSERT INTO actions VALUES (105,'spread on');
INSERT INTO actions VALUES (106,'still');
INSERT INTO actions VALUES (107,'drop');
INSERT INTO actions VALUES (108,'seems');
INSERT INTO actions VALUES (109,'puree');
INSERT INTO actions VALUES (110,'blend');
INSERT INTO actions VALUES (111,'can');
INSERT INTO actions VALUES (112,'peel');
INSERT INTO actions VALUES (113,'dry');
INSERT INTO actions VALUES (114,'season');
INSERT INTO actions VALUES (115,'simmer');
INSERT INTO actions VALUES (116,'strain');
INSERT INTO actions VALUES (117,'flatten');
INSERT INTO actions VALUES (118,'coat');
INSERT INTO actions VALUES (119,'transfer');
INSERT INTO actions VALUES (120,'separate');
INSERT INTO actions VALUES (121,'grind');
INSERT INTO actions VALUES (122,'hold');
INSERT INTO actions VALUES (123,'mash');
INSERT INTO actions VALUES (124,'starts');
INSERT INTO actions VALUES (125,'is');
INSERT INTO actions VALUES (126,'could');
INSERT INTO actions VALUES (127,'have');
INSERT INTO actions VALUES (128,'break up');
INSERT INTO actions VALUES (129,'rise');
INSERT INTO actions VALUES (130,'turn out');
INSERT INTO actions VALUES (131,'pinch');
INSERT INTO actions VALUES (132,'spray');
INSERT INTO actions VALUES (133,'oven');
INSERT INTO actions VALUES (134,'turn');
INSERT INTO actions VALUES (135,'winter');
INSERT INTO actions VALUES (136,'put on');
INSERT INTO actions VALUES (137,'cut out');
INSERT INTO actions VALUES (138,'frost');
INSERT INTO actions VALUES (139,'taste');
INSERT INTO actions VALUES (140,'prefer');
INSERT INTO actions VALUES (141,'become');
INSERT INTO actions VALUES (142,'triples recipe');
INSERT INTO actions VALUES (143,'reserve');
INSERT INTO actions VALUES (144,'form');
INSERT INTO actions VALUES (145,'rinse');
INSERT INTO actions VALUES (146,'given');
INSERT INTO actions VALUES (147,'noodles cook');
INSERT INTO actions VALUES (148,'sits');
INSERT INTO actions VALUES (149,'fill');
INSERT INTO actions VALUES (150,'pat');
INSERT INTO actions VALUES (151,'look');
INSERT INTO actions VALUES (152,'whip');
INSERT INTO actions VALUES (153,'store');
INSERT INTO actions VALUES (154,'eggs');
INSERT INTO actions VALUES (155,'insert');
INSERT INTO actions VALUES (156,'cake');
INSERT INTO actions VALUES (157,'watch');
INSERT INTO actions VALUES (158,'like');
INSERT INTO actions VALUES (159,'oil');
INSERT INTO actions VALUES (160,'press down');
INSERT INTO actions VALUES (161,'sugar');
INSERT INTO actions VALUES (162,'might');
INSERT INTO actions VALUES (163,'peel off');
INSERT INTO actions VALUES (164,'spread out');
INSERT INTO actions VALUES (165,'sounds');
INSERT INTO actions VALUES (166,'size');
INSERT INTO actions VALUES (167,'lower');
INSERT INTO actions VALUES (168,'watch out');
INSERT INTO actions VALUES (169,'lay');
INSERT INTO actions VALUES (170,'roll up');
INSERT INTO actions VALUES (171,'frozen');
INSERT INTO actions VALUES (172,'lunch');
INSERT INTO actions VALUES (173,'knead');
INSERT INTO actions VALUES (174,'brown skillet');
INSERT INTO actions VALUES (175,'smother');
INSERT INTO actions VALUES (176,'dish greased baking');
INSERT INTO actions VALUES (177,'toss');
INSERT INTO actions VALUES (178,'turn off');
INSERT INTO actions VALUES (179,'puff up');
INSERT INTO actions VALUES (180,'line');
INSERT INTO actions VALUES (181,'fold in');
INSERT INTO actions VALUES (182,'cut up');
INSERT INTO actions VALUES (183,'roast');
INSERT INTO actions VALUES (184,'distribute');
INSERT INTO actions VALUES (185,'baste');
INSERT INTO actions VALUES (186,'will');
INSERT INTO actions VALUES (187,'oven preheat');
INSERT INTO actions VALUES (188,'whisk');
INSERT INTO actions VALUES (189,'finish');
INSERT INTO actions VALUES (190,'love');
INSERT INTO actions VALUES (191,'eaten');
INSERT INTO actions VALUES (192,'made');
INSERT INTO actions VALUES (193,'goes');
INSERT INTO actions VALUES (194,'repeat');
INSERT INTO actions VALUES (195,'time preparation');
INSERT INTO actions VALUES (196,'take');
INSERT INTO actions VALUES (197,'soften');
INSERT INTO actions VALUES (198,'point boiling');
INSERT INTO actions VALUES (199,'alternate');
INSERT INTO actions VALUES (200,'poke');
INSERT INTO actions VALUES (201,'sprinkle over');
INSERT INTO actions VALUES (202,'inch');
INSERT INTO actions VALUES (203,'consider');
INSERT INTO actions VALUES (204,'clean up');
INSERT INTO actions VALUES (205,'bottom');
INSERT INTO actions VALUES (206,'crumble');
INSERT INTO actions VALUES (207,'retain');
INSERT INTO actions VALUES (208,'press out');
INSERT INTO actions VALUES (209,'substitute');
INSERT INTO actions VALUES (210,'mine');
INSERT INTO actions VALUES (211,'package');
INSERT INTO actions VALUES (212,'divide');
INSERT INTO actions VALUES (213,'beat on');
INSERT INTO actions VALUES (214,'enjoy');
INSERT INTO actions VALUES (215,'takes');
INSERT INTO actions VALUES (216,'grill');
INSERT INTO actions VALUES (217,'pan');
INSERT INTO actions VALUES (218,'handle');
INSERT INTO actions VALUES (219,'scald');
INSERT INTO actions VALUES (220,'melts chocolate');
INSERT INTO actions VALUES (221,'rolls out');
INSERT INTO actions VALUES (222,'preheat');
INSERT INTO actions VALUES (223,'process');
INSERT INTO actions VALUES (224,'return');
INSERT INTO actions VALUES (225,'cook over');
INSERT INTO actions VALUES (226,'make out');
INSERT INTO actions VALUES (227,'check');
INSERT INTO actions VALUES (228,'smooth out');
INSERT INTO actions VALUES (229,'stand');
INSERT INTO actions VALUES (230,'thicken');
INSERT INTO actions VALUES (231,'ladle');
INSERT INTO actions VALUES (232,'freezes');
INSERT INTO actions VALUES (233,'mix together');
INSERT INTO actions VALUES (234,'open');
INSERT INTO actions VALUES (235,'slip');
INSERT INTO actions VALUES (236,'iron');
INSERT INTO actions VALUES (237,'wilt');
INSERT INTO actions VALUES (238,'broil');
INSERT INTO actions VALUES (239,'soak');
INSERT INTO actions VALUES (240,'crack');
INSERT INTO actions VALUES (241,'test');
INSERT INTO actions VALUES (242,'break');
INSERT INTO actions VALUES (243,'shake');
INSERT INTO actions VALUES (244,'better');
INSERT INTO actions VALUES (245,'measure out');
INSERT INTO actions VALUES (246,'gone');
INSERT INTO actions VALUES (247,'lack');
INSERT INTO actions VALUES (248,'sprinkle atop');
INSERT INTO actions VALUES (249,'decorate');
INSERT INTO actions VALUES (250,'range');
INSERT INTO actions VALUES (251,'press up');
INSERT INTO actions VALUES (252,'parties');
INSERT INTO actions VALUES (253,'stack');
INSERT INTO actions VALUES (254,'note');
INSERT INTO actions VALUES (255,'do');
INSERT INTO actions VALUES (256,'thaw');
INSERT INTO actions VALUES (257,'pound');
INSERT INTO actions VALUES (258,'toast');
INSERT INTO actions VALUES (259,'start');
INSERT INTO actions VALUES (260,'rises');
INSERT INTO actions VALUES (261,'pack');
INSERT INTO actions VALUES (262,'mix in');
INSERT INTO actions VALUES (263,'follow');
INSERT INTO actions VALUES (264,'sear');
INSERT INTO actions VALUES (265,'measure');
INSERT INTO actions VALUES (266,'crush');
INSERT INTO actions VALUES (267,'blot');
INSERT INTO actions VALUES (268,'saucepan');
INSERT INTO actions VALUES (269,'skin');
INSERT INTO actions VALUES (270,'fat');
INSERT INTO actions VALUES (271,'poke down');
INSERT INTO actions VALUES (272,'beat in');
INSERT INTO actions VALUES (273,'fork');
INSERT INTO actions VALUES (274,'begin');
INSERT INTO actions VALUES (275,'spread over');
INSERT INTO actions VALUES (276,'pan frying');
INSERT INTO actions VALUES (277,'spray nonstick cooking');
INSERT INTO actions VALUES (278,'fit');
INSERT INTO actions VALUES (279,'room');
INSERT INTO actions VALUES (280,'leave out');
INSERT INTO actions VALUES (281,'round');
INSERT INTO actions VALUES (282,'wait');
INSERT INTO actions VALUES (283,'work');
INSERT INTO actions VALUES (284,'improvise');
INSERT INTO actions VALUES (285,'eat');
INSERT INTO actions VALUES (286,'save');
INSERT INTO actions VALUES (287,'add over');
INSERT INTO actions VALUES (288,'overcook');
INSERT INTO actions VALUES (289,'lift');
INSERT INTO actions VALUES (290,'sit');
INSERT INTO actions VALUES (291,'please');
INSERT INTO actions VALUES (292,'broken up');
INSERT INTO actions VALUES (293,'grate');
INSERT INTO actions VALUES (294,'cube');
INSERT INTO actions VALUES (295,'cook on');
INSERT INTO actions VALUES (296,'best');
INSERT INTO actions VALUES (297,'tear');
INSERT INTO actions VALUES (298,'dip out');
INSERT INTO actions VALUES (299,'cool down');
INSERT INTO actions VALUES (300,'take out');
INSERT INTO actions VALUES (301,'skim off');
INSERT INTO actions VALUES (302,'broken');
INSERT INTO actions VALUES (303,'mound');
INSERT INTO actions VALUES (304,'be');
INSERT INTO actions VALUES (305,'must');
INSERT INTO actions VALUES (306,'rotate');
INSERT INTO actions VALUES (307,'shallow');
INSERT INTO actions VALUES (308,'invert');
INSERT INTO actions VALUES (309,'get');
INSERT INTO actions VALUES (310,'ice');
INSERT INTO actions VALUES (311,'back');
INSERT INTO actions VALUES (312,'crumbles');
INSERT INTO actions VALUES (313,'ham');
INSERT INTO actions VALUES (314,'remember');
INSERT INTO actions VALUES (315,'dust');
INSERT INTO actions VALUES (316,'rest');
INSERT INTO actions VALUES (317,'layers christmas');
INSERT INTO actions VALUES (318,'time');
INSERT INTO actions VALUES (319,'contains');
INSERT INTO actions VALUES (320,'ready');
INSERT INTO actions VALUES (321,'rub');
INSERT INTO actions VALUES (322,'vegetables dice');
INSERT INTO actions VALUES (323,'tie');
INSERT INTO actions VALUES (324,'cuts');
INSERT INTO actions VALUES (325,'throw in');
INSERT INTO actions VALUES (326,'resift');
INSERT INTO actions VALUES (327,'clear');
INSERT INTO actions VALUES (328,'needs');
INSERT INTO actions VALUES (329,'moisten');
INSERT INTO actions VALUES (330,'diet');
INSERT INTO actions VALUES (331,'fat gm');
INSERT INTO actions VALUES (332,'refrigerate over');
INSERT INTO actions VALUES (333,'cup');
INSERT INTO actions VALUES (334,'tastes');
INSERT INTO actions VALUES (335,'plain');
INSERT INTO actions VALUES (336,'dish casserole');
INSERT INTO actions VALUES (337,'party cocktail');
INSERT INTO actions VALUES (338,'thickens');
INSERT INTO actions VALUES (339,'pour out');
INSERT INTO actions VALUES (340,'low');
INSERT INTO actions VALUES (341,'secure');
INSERT INTO actions VALUES (342,'draw');
INSERT INTO actions VALUES (343,'julienne');
INSERT INTO actions VALUES (344,'lime');
INSERT INTO actions VALUES (345,'try');
INSERT INTO actions VALUES (346,'cans coffee');
INSERT INTO actions VALUES (347,'stir in');
INSERT INTO actions VALUES (348,'strips');
INSERT INTO actions VALUES (349,'stir down');
INSERT INTO actions VALUES (350,'balls');
INSERT INTO actions VALUES (351,'dredge');
INSERT INTO actions VALUES (352,'carve');
INSERT INTO actions VALUES (353,'disappears');
INSERT INTO actions VALUES (354,'directs recipe');
INSERT INTO actions VALUES (355,'thin');
INSERT INTO actions VALUES (356,'comes out');
INSERT INTO actions VALUES (357,'enhances');
INSERT INTO actions VALUES (358,'gets');
INSERT INTO actions VALUES (359,'see');
INSERT INTO actions VALUES (360,'loosen');
INSERT INTO actions VALUES (361,'steam');
INSERT INTO actions VALUES (362,'adjust');
INSERT INTO actions VALUES (363,'turn over');
INSERT INTO actions VALUES (364,'time baking');
INSERT INTO actions VALUES (365,'set on');
INSERT INTO actions VALUES (366,'pot');
INSERT INTO actions VALUES (367,'exclude');
INSERT INTO actions VALUES (368,'crumbs graham cracker');
INSERT INTO actions VALUES (369,'sheet');
INSERT INTO actions VALUES (370,'arrange down');
INSERT INTO actions VALUES (371,'tells');
INSERT INTO actions VALUES (372,'stew');
INSERT INTO actions VALUES (373,'stuff');
INSERT INTO actions VALUES (374,'drop out');
INSERT INTO actions VALUES (375,'spread coconut');
INSERT INTO actions VALUES (376,'light');
INSERT INTO actions VALUES (377,'cover over');
INSERT INTO actions VALUES (378,'house');
INSERT INTO actions VALUES (379,'drink');
INSERT INTO actions VALUES (380,'soup');
INSERT INTO actions VALUES (381,'want');
INSERT INTO actions VALUES (382,'keeps in');
INSERT INTO actions VALUES (383,'ends');
INSERT INTO actions VALUES (384,'expand');
INSERT INTO actions VALUES (385,'firms up');
INSERT INTO actions VALUES (386,'servings');
INSERT INTO actions VALUES (387,'wish');
INSERT INTO actions VALUES (388,'hands buttered');
INSERT INTO actions VALUES (389,'spoon off');
INSERT INTO actions VALUES (390,'pepper');
INSERT INTO actions VALUES (391,'butter micromelt');
INSERT INTO actions VALUES (392,'equals');
INSERT INTO actions VALUES (393,'water');
INSERT INTO actions VALUES (394,'flour');
INSERT INTO actions VALUES (395,'burn');
INSERT INTO actions VALUES (396,'fold over');
INSERT INTO actions VALUES (397,'crimp');
INSERT INTO actions VALUES (398,'bake in');
INSERT INTO actions VALUES (399,'harden');
INSERT INTO actions VALUES (400,'fix');
INSERT INTO actions VALUES (401,'dish');
INSERT INTO actions VALUES (402,'flip');
INSERT INTO actions VALUES (403,'pop');
INSERT INTO actions VALUES (404,'strain out');
INSERT INTO actions VALUES (405,'drops');
INSERT INTO actions VALUES (406,'fall');
INSERT INTO actions VALUES (407,'glaze');
INSERT INTO actions VALUES (408,'bake on');
INSERT INTO actions VALUES (409,'had');
INSERT INTO actions VALUES (410,'brunch');
INSERT INTO actions VALUES (411,'boil over');
INSERT INTO actions VALUES (412,'keep in');
INSERT INTO actions VALUES (413,'helps');
INSERT INTO actions VALUES (414,'twist');
INSERT INTO actions VALUES (415,'reaches');
INSERT INTO actions VALUES (416,'avoid');
INSERT INTO actions VALUES (417,'run');
INSERT INTO actions VALUES (418,'hands');
INSERT INTO actions VALUES (419,'trim');
INSERT INTO actions VALUES (420,'reshape');
INSERT INTO actions VALUES (421,'sets');
INSERT INTO actions VALUES (422,'done');
INSERT INTO actions VALUES (423,'anchor');
INSERT INTO actions VALUES (424,'cut down');
INSERT INTO actions VALUES (425,'unroll');
INSERT INTO actions VALUES (426,'halfway up');
INSERT INTO actions VALUES (427,'has');
INSERT INTO actions VALUES (428,'brought');
INSERT INTO actions VALUES (429,'course');
INSERT INTO actions VALUES (430,'cooks');
INSERT INTO actions VALUES (431,'leave in');
INSERT INTO actions VALUES (432,'pull');
INSERT INTO actions VALUES (433,'crust');
INSERT INTO actions VALUES (434,'gather');
INSERT INTO actions VALUES (435,'lukewarm');
INSERT INTO actions VALUES (436,'spray pam');
INSERT INTO actions VALUES (437,'break off');
INSERT INTO actions VALUES (438,'leak out');
INSERT INTO actions VALUES (439,'beaten');
INSERT INTO actions VALUES (440,'spins');
INSERT INTO actions VALUES (441,'shake on');
INSERT INTO actions VALUES (442,'pan 13-inch');
INSERT INTO actions VALUES (443,'release');
INSERT INTO actions VALUES (444,'scoop up');
INSERT INTO actions VALUES (445,'does');
INSERT INTO actions VALUES (446,'left');
INSERT INTO actions VALUES (447,'smooth');
INSERT INTO actions VALUES (448,'arrange over');
INSERT INTO actions VALUES (449,'shake off');
INSERT INTO actions VALUES (450,'slit');
INSERT INTO actions VALUES (451,'edges flute');
INSERT INTO actions VALUES (452,'kitten feed');
INSERT INTO actions VALUES (453,'dash');
INSERT INTO actions VALUES (454,'fasten');
INSERT INTO actions VALUES (455,'comes');
INSERT INTO actions VALUES (456,'out');
INSERT INTO actions VALUES (457,'hand');
INSERT INTO actions VALUES (458,'edges under');
INSERT INTO actions VALUES (459,'prick over');
INSERT INTO actions VALUES (460,'mold');
INSERT INTO actions VALUES (461,'spoon out');
INSERT INTO actions VALUES (462,'swirl');
INSERT INTO actions VALUES (463,'bottle');
INSERT INTO actions VALUES (464,'gives');
INSERT INTO actions VALUES (465,'time cooking');
INSERT INTO actions VALUES (466,'overbeat');
INSERT INTO actions VALUES (467,'sheet cookie');
INSERT INTO actions VALUES (468,'scramble');
INSERT INTO actions VALUES (469,'end');
INSERT INTO actions VALUES (470,'quarter');
INSERT INTO actions VALUES (471,'looks');
INSERT INTO actions VALUES (472,'nuts');
INSERT INTO actions VALUES (473,'would');
INSERT INTO actions VALUES (474,'bit');
INSERT INTO actions VALUES (475,'close');
INSERT INTO actions VALUES (476,'tear up');
INSERT INTO actions VALUES (477,'warm');
INSERT INTO actions VALUES (478,'rolls press');
INSERT INTO actions VALUES (479,'score');
INSERT INTO actions VALUES (480,'tie up');
INSERT INTO actions VALUES (481,'come out');
INSERT INTO actions VALUES (482,'omit');
INSERT INTO actions VALUES (483,'sprinkle on');
INSERT INTO actions VALUES (484,'increase');
INSERT INTO actions VALUES (485,'perk');
INSERT INTO actions VALUES (486,'punch out');
INSERT INTO actions VALUES (487,'stems onion');
INSERT INTO actions VALUES (488,'buzz');
INSERT INTO actions VALUES (489,'feeds');
INSERT INTO actions VALUES (490,'overmix');
INSERT INTO actions VALUES (491,'sauce');
INSERT INTO actions VALUES (492,'hurry');
INSERT INTO actions VALUES (493,'begins');
INSERT INTO actions VALUES (494,'rosettes');
INSERT INTO actions VALUES (495,'preserves');
INSERT INTO actions VALUES (496,'assemble');
INSERT INTO actions VALUES (497,'seem');
INSERT INTO actions VALUES (498,'lay up');
INSERT INTO actions VALUES (499,'fill in');
INSERT INTO actions VALUES (500,'congeal');
INSERT INTO actions VALUES (501,'firm');
INSERT INTO actions VALUES (502,'go on');
INSERT INTO actions VALUES (503,'dates');
INSERT INTO actions VALUES (504,'blanch');
INSERT INTO actions VALUES (505,'pan greased');
INSERT INTO actions VALUES (506,'pass');
INSERT INTO actions VALUES (507,'pan baking');
INSERT INTO actions VALUES (508,'corn');
