
USE recipe_analysis;
DROP TABLE IF EXISTS contains;
CREATE TABLE contains(
id INT NOT NULL AUTO_INCREMENT,
misura VARCHAR(50),
quantita FLOAT,
proprieta VARCHAR(100),
recipeID int NOT NULL,
ingredientID int NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (recipeID) REFERENCES recipes(id),
FOREIGN KEY (ingredientID) REFERENCES ingredients(id)
);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'cut, chipped, small',0, 0);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',4.0,'boned',0, 1);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',0, 2);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',0, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',16.0,'frozen',1, 4);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',8.0,'cubed',1, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1,'cubed',1, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.5,'',1, 7);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.5,'',1, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.25,'',1, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'whole, large',2, 10);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',10.5,'',2, 11);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',10.5,'',2, 2);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',6.0,'',2, 12);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',4.0,'shredded',2, 13);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',3, 14);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.75,'',3, 15);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'melted',3, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.5,'powdered',3, 17);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',1.0,'large',3, 18);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',6.0,'',4, 19);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'lean, extra',4, 20);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.6666666666666666,'',4, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',6.0,'',4, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.75,'',4, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.5,'',4, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',1.5,'shredded',4, 22);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',12.0,'cooked, sliced',4, 23);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',4.0,'',4, 24);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',8.0,'',4, 25);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.5,'',5, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',5, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',5, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',5, 28);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'',5, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.5,'',5, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',5, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',5, 28);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'',5, 31);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',5, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',6, 33);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'kernel, whole',6, 4);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',10.0,'',6, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',6, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',6.0,'',6, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'drained, liquid, upsave',7, 35);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.75,'',7, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',7, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.5,'',7, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'',7, 39);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'',7, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'cool, large',8, 41);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'crushed, large',8, 42);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'condensed',8, 43);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',3.0,'',8, 44);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',8, 45);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'crusts',8, 46);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',17.0,'dark, pitted',9, 47);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',9, 48);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',6.0,'o',9, 49);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'',9, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.125,'',9, 50);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'miniature',9, 51);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'powdered',10, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',8.0,'soft',10, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',8.0,'',10, 14);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',10, 52);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',12.0,'',10, 18);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',11, 53);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',11, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',11, 54);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',8.0,'',12, 55);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',8.0,'',12, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',8.0,'',12, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.0,'',12, 56);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',1.0,'',12, 57);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'shredded',12, 58);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'diced, large',12, 59);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'diced, medium',12, 60);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'diced, large',12, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'shredded',12, 62);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',13, 63);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'crushed',13, 42);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'sweetened, condensed',13, 43);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',8.0,'whipped, thawed',13, 64);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',13, 65);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'baked',14, 66);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' quart',1.0,'cleaned',14, 67);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.5,'',14, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',4.0,'',14, 68);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',14, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.125,'',14, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',4.0,'',14, 69);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',0.5,'jiffy',15, 70);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',0.5,'jiffy',15, 71);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'',15, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',2.5,'large',16, 72);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',10.0,'',16, 23);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',5.25,'chopped, red',16, 24);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',16, 73);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',16, 74);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',16, 75);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'',16, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.0,'frozen',17, 76);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'crushed',17, 42);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',3.0,'ripe',17, 77);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'chopped',17, 78);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',1.0,'large',17, 79);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.5,'',17, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pint',1.0,'',17, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.75,'',18, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.5,'',18, 80);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',3.0,'',18, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'each',18, 81);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'sifted',18, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',18, 73);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'nuts',18, 82);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',19, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',19, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',2.0,'',19, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'',19, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'',19, 83);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'ripe',19, 84);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',1.0,'',20, 85);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',1.0,'',20, 86);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',8.0,'',20, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.75,'',20, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',20, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',4.0,'',20, 87);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',6.0,'chopped',20, 88);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',9.0,'up',21, 82);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',21, 89);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',21, 90);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',21, 91);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',0.5,'',22, 92);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',22, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.5,'minced',22, 93);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'hot',22, 94);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.5,'',22, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',22, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'',22, 95);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',3.0,'italian',22, 96);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.5,'',23, 56);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',23, 97);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',23, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'chopped',23, 98);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.25,'',23, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.5,'',23, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',2.0,'',24, 99);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.5,'black',24, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',24, 100);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',24, 89);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',24, 101);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',2.0,'',24, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'red',24, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',24, 102);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',3.0,'',24, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'chopped',24, 103);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',3.375,'thick',25, 104);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',25, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',1.0,'',25, 105);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1,'',25, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'brown',25, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'prepared',25, 106);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'',25, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'sized, medium',25, 60);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',14.0,'sweetened, condensed',26, 43);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',12.0,'-, semi',26, 107);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',26, 25);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',26, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.0,'',27, 56);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',1.0,'',27, 57);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',27, 108);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',27, 109);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',4.0,'',27, 39);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',27, 59);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',0.5,'',27, 22);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',0.5,'',27, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',28, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',28, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',1.0,'dry',28, 110);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'',28, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',3.0,'',28, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'plain',28, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'sliced, large',29, 111);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'large',29, 112);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'diced, large',29, 42);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' quart',1.0,'fresh',29, 67);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'red',29, 113);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'yellow',29, 113);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',4.0,'ripe, large',29, 77);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.0,'',29, 114);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.0,'purple',29, 115);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',1.0,'',30, 116);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',30, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1,'red',30, 75);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',4.0,'',30, 117);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'cherry',31, 118);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',31, 119);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',31, 120);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',31, 83);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',3.0,'',32, 87);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',32, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.25,'',32, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'',32, 82);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',3.0,'',32, 19);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'shredded',32, 22);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1,'',32, 121);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',33, 122);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'small',33, 123);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'',34, 124);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',34, 74);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',34, 125);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',16.0,'',35, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',1.0,'dry',35, 126);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',10.0,'thawed, chopped, frozen',35, 127);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',10.0,'',35, 22);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.0,'thin',36, 128);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',0.5,'',36, 129);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'italian, zesty',36, 130);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',3.0,'',37, 131);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',8.0,'softened',37, 132);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',8.0,'',37, 133);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',7.0,'',38, 134);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',7.0,'',38, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'',38, 135);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.5,'',38, 136);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.5,'',38, 137);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',3.0,'',39, 10);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',4.0,'',39, 19);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'',39, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',16.0,'creamed',39, 138);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',16.0,'',39, 139);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',16.0,'field',39, 140);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',16.0,'butter',39, 141);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',16.0,'',39, 92);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',46.0,'',39, 142);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'small',39, 122);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'black',39, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'',39, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'',39, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',3.0,'softened',40, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'granulated',40, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',40, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',40, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.25,'baking',40, 143);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.25,'',40, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1,'',40, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.25,'',40, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1,'packed, brown',40, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.5,'',40, 144);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',40, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',5.0,'',41, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',3.0,'',41, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',4.0,'baking',41, 143);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',1.5,'dry',41, 110);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'',41, 28);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',41, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.5,'',41, 145);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'warm',41, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',8.0,'',42, 51);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'crushed',42, 146);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'yellow',43, 147);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'',43, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'brown',43, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'soft',43, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'',43, 87);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',44, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',44, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',4.0,'',44, 87);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',44, 148);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',3.0,'rising',45, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'',45, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'',46, 149);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'chopped',46, 103);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'',46, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.125,'',46, 150);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'sliced',46, 151);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',46, 152);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',1.0,'chopped',46, 127);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',46, 153);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'shredded',46, 154);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.5,'sifted',47, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.5,'baking',47, 143);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.5,'',47, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',47, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.6666666666666666,'',47, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',3.0,'',47, 155);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',47, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'colored, -, multi',47, 156);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',0.5,'',48, 56);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'',48, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',48, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',1.0,'mixdry',48, 157);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can pound',1.0,'stewed',48, 158);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',8.0,'',48, 142);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',10.0,'mixed, frozen',48, 159);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',4.0,'',49, 1);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',49, 160);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',49, 2);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',49, 161);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',49, 162);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',49, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'grated',49, 60);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',1.0,'',49, 163);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',4.0,'shredded',50, 164);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',0.5,'shredded',50, 165);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'chopped',50, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'chopped',50, 60);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',50, 74);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'',50, 75);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',2.0,'',50, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',50, 166);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.25,'',50, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',2.0,'',51, 167);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.5,'chopped',51, 158);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'chopped',51, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1,'',51, 65);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'',51, 168);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',2.0,'',51, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',2.0,'minced',51, 60);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',51, 169);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.25,'black, ground',51, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',4.0,'drops, red',51, 170);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',51, 171);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',52, 162);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'yellow',52, 108);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',52, 108);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',52, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',52, 168);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.6666666666666666,'',52, 75);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1,'',52, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',16.5,'',53, 33);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',8.0,'',53, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',8.5,'jiffy',53, 172);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',53, 173);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.0,'',54, 56);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1,'chopped',54, 98);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',54, 174);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'wide',54, 175);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon teaspoon',0.5,'oreganumber',54, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1,'',54, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',54, 13);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'small',55, 164);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'dry',55, 106);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'corned',55, 0);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',55, 152);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'chopped, medium',55, 60);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'',56, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'dry',56, 106);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',56, 74);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',56, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',8.0,'softened',57, 132);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',57, 176);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',8.0,'mild',57, 55);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',6.0,'sliced',57, 121);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',0.5,'chopped',57, 177);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',57, 59);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',57, 178);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',57, 22);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'black',57, 179);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',57, 180);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',0.5,'soft',58, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',58, 14);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',0.5,'',58, 15);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'',58, 181);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',58, 182);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',58, 183);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.0,'chopped, sliced',59, 184);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'',59, 185);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'chopped',59, 78);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'condensed',59, 43);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',59, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',59, 186);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'yellow',60, 147);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'',60, 87);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'melted',60, 187);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'',60, 87);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',8.0,'softened',60, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.0,'powdered',60, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'chunk, large',61, 42);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',9.0,'',61, 77);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',62, 2);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',62, 160);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',62, 152);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'cut',62, 188);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'melted',62, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.5,'uncooked',62, 189);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',8.0,'',63, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'sweetened, condensed',63, 43);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',0.5,'crushed',63, 190);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1,'',63, 65);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',8.0,'',64, 25);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',8.0,'',64, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',64, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',64, 14);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',4.0,'',65, 191);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.25,'',65, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.25,'',65, 192);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'',65, 65);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',65, 193);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',16.0,'cool',66, 41);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',2.0,'frozen',66, 67);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',9.0,'deep',66, 194);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.75,'',66, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',12.0,'',66, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',67, 173);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.5,'',67, 15);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'granulated',67, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'sifted',68, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.5,'baking',68, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.25,'',68, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.5,'',68, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',68, 195);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',68, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',68, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',68, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',3.0,'medium',69, 113);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'',69, 73);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'brown',69, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'granulated',69, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',69, 196);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'cold',69, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',3.0,'',69, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',2.0,'',69, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',69, 144);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',69, 197);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',69, 198);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',69, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'nuts',69, 82);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',6.0,'diced',70, 19);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'chopped',70, 98);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.75,'melted',70, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',70, 160);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',8.0,'',70, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'grated',70, 22);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',71, 199);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',71, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.6666666666666665,'',72, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.6666666666666666,'',72, 200);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.6666666666666666,'cold',72, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'',72, 201);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',72, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',73, 113);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',73, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',73, 144);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'',73, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',73, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',73, 202);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',73, 203);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',73, 204);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'',74, 205);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.0,'',74, 206);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',8.0,'',74, 22);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',75, 207);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',75, 160);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',75, 208);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'',75, 189);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',75, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',76, 209);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'chopped',76, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',76, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.0,'',76, 56);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',76, 75);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',76, 65);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'brown',76, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.5,'',76, 106);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',76, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.5,'',76, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',76, 210);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',76, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',13.75,'',77, 211);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'',77, 68);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'beaten',77, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'sliced1/4',77, 24);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' gallon',0.5,'',78, 212);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',78, 213);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'whole',78, 198);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',78, 214);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'brown',78, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'',79, 215);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',2.0,'grated',79, 216);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',79, 217);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'reduced',79, 90);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',4.0,'skinned',79, 218);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',79, 219);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'thin',79, 220);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',16.0,'fresh',80, 221);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'',80, 39);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',80, 222);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',6.0,'breadbuttered',80, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',6.0,'',80, 87);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'milkas',80, 223);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',12.0,'',81, 25);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',81, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'peeled, medium',81, 224);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',81, 225);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',3.0,'',81, 226);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',81, 227);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'raw',82, 189);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'beef',82, 228);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'french',82, 229);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',4.0,'',82, 221);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',0.5,'cut',82, 187);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',3.0,'softened',83, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',83, 149);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',83, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',16.0,'whole',83, 230);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.75,'drained, crushed',83, 42);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'chopped',83, 231);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',83, 232);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',2.0,'',84, 233);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',15.0,'italian',84, 139);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'small',84, 234);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',3.5,'garlicup',84, 235);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.3333333333333333,'',85, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.25,'',85, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.5,'',85, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',85, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',0.75,'',85, 143);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',85, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.6666666666666666,'',85, 236);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',85, 237);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'powdered',85, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',4.0,'',86, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',86, 195);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.0,'',86, 238);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.0,'',86, 239);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'',86, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',3.0,'',87, 240);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',3.0,'',87, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pint',1.0,'',87, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',3.0,'',87, 241);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'',87, 242);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',1.0,'',87, 243);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',87, 120);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',2.0,'',88, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'shredded',88, 244);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'chopped',88, 245);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'chopped',88, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'chopped',88, 60);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',88, 65);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',2.0,'',88, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',88, 246);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1,'',88, 202);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',1.0,'large',89, 247);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.6666666666666666,'',89, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',8.0,'',89, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'junior',89, 248);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'',89, 249);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'evaporated, tall',89, 43);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.6666666666666666,'',89, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',3.0,'substituted, plain, plain',90, 250);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',3.0,'',90, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.5,'baking',90, 143);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',3.0,'',90, 251);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',5.0,'',90, 87);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'',90, 145);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',90, 252);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',90, 253);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',6.0,'',90, 254);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'softened, frozen',91, 255);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',91, 149);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'brown',91, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'puddingnot, large',91, 256);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',91, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',8.0,'',92, 257);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.5,'medium',92, 258);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',92, 259);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'',92, 160);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.5,'',92, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'spanish',93, 139);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',1.0,'corned',93, 0);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'diced',93, 60);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'grated',93, 22);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.0,'',94, 260);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.75,'',94, 210);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1.0,'',94, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',1,'black',94, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',1.0,'',94, 56);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'',94, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',2.0,'cooked',95, 261);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',95, 196);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',95, 262);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',2.0,'',95, 263);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.25,'',95, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',3.0,'',95, 264);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'brown, packed',95, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',95, 68);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',0.25,'',95, 216);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'',95, 210);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',2.0,'',95, 75);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',1.0,'',95, 90);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',95, 265);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',8.0,'',95, 266);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',18.0,'juicy',96, 267);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'moist',96, 181);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',96, 45);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.5,'',96, 268);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',0.25,'',96, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',96, 269);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'creamy',97, 270);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',1.0,'',97, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',1.0,'',97, 27);
