
USE recipe_analysis;
DROP TABLE IF EXISTS ingredients;
CREATE TABLE ingredients(
id INT PRIMARY KEY,
name VARCHAR(100) NOT NULL
);
INSERT INTO ingredients VALUES (0,"beef ");
INSERT INTO ingredients VALUES (1,"chicken breasts");
INSERT INTO ingredients VALUES (2,"mushroom soup cream");
INSERT INTO ingredients VALUES (3,"sour cream");
INSERT INTO ingredients VALUES (4,"corn");
INSERT INTO ingredients VALUES (5,"cream cheese");
INSERT INTO ingredients VALUES (6,"butter");
INSERT INTO ingredients VALUES (7,"garlic powder");
INSERT INTO ingredients VALUES (8,"salt");
INSERT INTO ingredients VALUES (9,"pepper");
INSERT INTO ingredients VALUES (10,"chicken");
INSERT INTO ingredients VALUES (11,"chicken gravy cans");
INSERT INTO ingredients VALUES (12,"stuffing");
INSERT INTO ingredients VALUES (13,"cheese");
INSERT INTO ingredients VALUES (14,"peanut butter");
INSERT INTO ingredients VALUES (15,"graham cracker crumbs");
INSERT INTO ingredients VALUES (16,"butter ");
INSERT INTO ingredients VALUES (17,"sugar cup");
INSERT INTO ingredients VALUES (18,"chocolate chips");
INSERT INTO ingredients VALUES (19,"potatoes");
INSERT INTO ingredients VALUES (20,"beef pound");
INSERT INTO ingredients VALUES (21,"milk");
INSERT INTO ingredients VALUES (22,"cheddar cheese");
INSERT INTO ingredients VALUES (23,"bacon");
INSERT INTO ingredients VALUES (24,"green onion");
INSERT INTO ingredients VALUES (25,"ounce");
INSERT INTO ingredients VALUES (26,"sugar");
INSERT INTO ingredients VALUES (27,"egg");
INSERT INTO ingredients VALUES (28,"buttermilk");
INSERT INTO ingredients VALUES (29,"flour");
INSERT INTO ingredients VALUES (30,"soda");
INSERT INTO ingredients VALUES (31,"rhubarb");
INSERT INTO ingredients VALUES (32,"vanilla");
INSERT INTO ingredients VALUES (33,"cream corn");
INSERT INTO ingredients VALUES (34,"saltine crackers");
INSERT INTO ingredients VALUES (35,"cut tomatoes");
INSERT INTO ingredients VALUES (36,"water");
INSERT INTO ingredients VALUES (37,"onions");
INSERT INTO ingredients VALUES (38,"worcestershire sauce");
INSERT INTO ingredients VALUES (39,"green peppers");
INSERT INTO ingredients VALUES (40,"oil");
INSERT INTO ingredients VALUES (41,"whip");
INSERT INTO ingredients VALUES (42,"pineapple ");
INSERT INTO ingredients VALUES (43,"milk ");
INSERT INTO ingredients VALUES (44,"lemons");
INSERT INTO ingredients VALUES (45,"pecans");
INSERT INTO ingredients VALUES (46,"graham ");
INSERT INTO ingredients VALUES (47,"sweet cherries");
INSERT INTO ingredients VALUES (48,"ginger ale");
INSERT INTO ingredients VALUES (49,"cherry gelatin");
INSERT INTO ingredients VALUES (50,"almond extract");
INSERT INTO ingredients VALUES (51,"marshmallows");
INSERT INTO ingredients VALUES (52,"paraffin");
INSERT INTO ingredients VALUES (53,"chicken dinner wingsas");
INSERT INTO ingredients VALUES (54,"choice");
INSERT INTO ingredients VALUES (55,"taco sauce");
INSERT INTO ingredients VALUES (56,"beef");
INSERT INTO ingredients VALUES (57,"taco seasoning");
INSERT INTO ingredients VALUES (58,"lettuce");
INSERT INTO ingredients VALUES (59,"tomato");
INSERT INTO ingredients VALUES (60,"onion");
INSERT INTO ingredients VALUES (61,"green pepper");
INSERT INTO ingredients VALUES (62,"cheddar colby");
INSERT INTO ingredients VALUES (63,"pie fillingcherry");
INSERT INTO ingredients VALUES (64,"topping");
INSERT INTO ingredients VALUES (65,"lemon juice");
INSERT INTO ingredients VALUES (66,"pie shell");
INSERT INTO ingredients VALUES (67,"strawberries");
INSERT INTO ingredients VALUES (68,"cornstarch");
INSERT INTO ingredients VALUES (69,"strawberry jello");
INSERT INTO ingredients VALUES (70,"chocolate fudge cake pudding mix");
INSERT INTO ingredients VALUES (71,"white cake pudding mix");
INSERT INTO ingredients VALUES (72,"broccoliabout");
INSERT INTO ingredients VALUES (73,"raisins");
INSERT INTO ingredients VALUES (74,"mayonnaise");
INSERT INTO ingredients VALUES (75,"vinegar");
INSERT INTO ingredients VALUES (76,"juice strawberries");
INSERT INTO ingredients VALUES (77,"bananas");
INSERT INTO ingredients VALUES (78,"pecans ");
INSERT INTO ingredients VALUES (79,"strawberry o.");
INSERT INTO ingredients VALUES (80,"applesauce");
INSERT INTO ingredients VALUES (81,"cinnamon teaspoon");
INSERT INTO ingredients VALUES (82,"cup");
INSERT INTO ingredients VALUES (83,"nuts");
INSERT INTO ingredients VALUES (84,"bananaschopped");
INSERT INTO ingredients VALUES (85,"food cake mix");
INSERT INTO ingredients VALUES (86,"chocolate fudge pudding mixinstant");
INSERT INTO ingredients VALUES (87,"eggs");
INSERT INTO ingredients VALUES (88,"mints");
INSERT INTO ingredients VALUES (89,"vegetable oil");
INSERT INTO ingredients VALUES (90,"soy sauce");
INSERT INTO ingredients VALUES (91,"garlic salt");
INSERT INTO ingredients VALUES (92,"tomatoes");
INSERT INTO ingredients VALUES (93,"tomato paste");
INSERT INTO ingredients VALUES (94,"sweet 3");
INSERT INTO ingredients VALUES (95,"sweet basil");
INSERT INTO ingredients VALUES (96,"seasoning tablespoon");
INSERT INTO ingredients VALUES (97,"tomato juice");
INSERT INTO ingredients VALUES (98,"onion ");
INSERT INTO ingredients VALUES (99,"round steak");
INSERT INTO ingredients VALUES (100,"white pepper");
INSERT INTO ingredients VALUES (101,"beef stock");
INSERT INTO ingredients VALUES (102,"flourdredging");
INSERT INTO ingredients VALUES (103,"celery ");
INSERT INTO ingredients VALUES (104,"round thinner");
INSERT INTO ingredients VALUES (105,"tomato sauce");
INSERT INTO ingredients VALUES (106,"mustard");
INSERT INTO ingredients VALUES (107,"sweet chocolate chips");
INSERT INTO ingredients VALUES (108,"beans");
INSERT INTO ingredients VALUES (109,"salsa");
INSERT INTO ingredients VALUES (110,"yeast");
INSERT INTO ingredients VALUES (111,"peaches ");
INSERT INTO ingredients VALUES (112,"cocktail");
INSERT INTO ingredients VALUES (113,"apples");
INSERT INTO ingredients VALUES (114,"white grapes");
INSERT INTO ingredients VALUES (115,"grapes");
INSERT INTO ingredients VALUES (116,"chicken cutlets");
INSERT INTO ingredients VALUES (117,"garlic salt tablespoon");
INSERT INTO ingredients VALUES (118,"pie mix");
INSERT INTO ingredients VALUES (119,"white cake mix");
INSERT INTO ingredients VALUES (120,"stick butter");
INSERT INTO ingredients VALUES (121,"green onions");
INSERT INTO ingredients VALUES (122,"macaroni");
INSERT INTO ingredients VALUES (123,"pimentos");
INSERT INTO ingredients VALUES (124,"artichoke cans");
INSERT INTO ingredients VALUES (125,"parmesan cheese");
INSERT INTO ingredients VALUES (126,"vegetable soup mix");
INSERT INTO ingredients VALUES (127,"broccoli");
INSERT INTO ingredients VALUES (128,"spaghetti");
INSERT INTO ingredients VALUES (129,"salad supremeseasoning");
INSERT INTO ingredients VALUES (130,"dressing");
INSERT INTO ingredients VALUES (131,"lime gelatin");
INSERT INTO ingredients VALUES (132,"cream ");
INSERT INTO ingredients VALUES (133,"lemon yogurt");
INSERT INTO ingredients VALUES (134,"watermelon rind");
INSERT INTO ingredients VALUES (135,"apple vinegar");
INSERT INTO ingredients VALUES (136,"cloves oil");
INSERT INTO ingredients VALUES (137,"cinnamon oil");
INSERT INTO ingredients VALUES (138,"corn ");
INSERT INTO ingredients VALUES (139,"can");
INSERT INTO ingredients VALUES (140,"peas ");
INSERT INTO ingredients VALUES (141,"beans ");
INSERT INTO ingredients VALUES (142,"tomato can");
INSERT INTO ingredients VALUES (143,"powder");
INSERT INTO ingredients VALUES (144,"cinnamon");
INSERT INTO ingredients VALUES (145,"sticks margarine");
INSERT INTO ingredients VALUES (146,"peppermint candy");
INSERT INTO ingredients VALUES (147,"cake mix");
INSERT INTO ingredients VALUES (148,"chocolate syrup");
INSERT INTO ingredients VALUES (149,"margarine");
INSERT INTO ingredients VALUES (150,"curry powder");
INSERT INTO ingredients VALUES (151,"juice ");
INSERT INTO ingredients VALUES (152,"celery soup cream");
INSERT INTO ingredients VALUES (153,"chicken cubed");
INSERT INTO ingredients VALUES (154,"jack cheese");
INSERT INTO ingredients VALUES (155,"egg yolks");
INSERT INTO ingredients VALUES (156,"candies");
INSERT INTO ingredients VALUES (157,"soup onion soup cup");
INSERT INTO ingredients VALUES (158,"tomatoes ");
INSERT INTO ingredients VALUES (159,"vegetables");
INSERT INTO ingredients VALUES (160,"chicken soup cream");
INSERT INTO ingredients VALUES (161,"green chili salsa can");
INSERT INTO ingredients VALUES (162,"green can");
INSERT INTO ingredients VALUES (163,"corn pieces tortilla");
INSERT INTO ingredients VALUES (164,"cabbage");
INSERT INTO ingredients VALUES (165,"carrots cup");
INSERT INTO ingredients VALUES (166,"celery seed");
INSERT INTO ingredients VALUES (167,"pollack flounder");
INSERT INTO ingredients VALUES (168,"salad oil");
INSERT INTO ingredients VALUES (169,"basil leaves");
INSERT INTO ingredients VALUES (170,"pepper sauce");
INSERT INTO ingredients VALUES (171,"green pepper rings");
INSERT INTO ingredients VALUES (172,"corn bread mix");
INSERT INTO ingredients VALUES (173,"stick margarine");
INSERT INTO ingredients VALUES (174,"tomato soup");
INSERT INTO ingredients VALUES (175,"noodles cup");
INSERT INTO ingredients VALUES (176,"salad mayonnaise");
INSERT INTO ingredients VALUES (177,"green ");
INSERT INTO ingredients VALUES (178,"mozzarella cheese");
INSERT INTO ingredients VALUES (179,"olivesoptional");
INSERT INTO ingredients VALUES (180,"tortilla chips");
INSERT INTO ingredients VALUES (181,"coconut");
INSERT INTO ingredients VALUES (182,"meatsoptional");
INSERT INTO ingredients VALUES (183,"vanilla dash");
INSERT INTO ingredients VALUES (184,"orange ");
INSERT INTO ingredients VALUES (185,"coconut cans");
INSERT INTO ingredients VALUES (186,"orange flavoring");
INSERT INTO ingredients VALUES (187,"stick ");
INSERT INTO ingredients VALUES (188,"chicken ");
INSERT INTO ingredients VALUES (189,"rice");
INSERT INTO ingredients VALUES (190,"pineapple cup");
INSERT INTO ingredients VALUES (191,"peaches");
INSERT INTO ingredients VALUES (192,"sour light");
INSERT INTO ingredients VALUES (193,"vanilla 3/4");
INSERT INTO ingredients VALUES (194,"pie crusts");
INSERT INTO ingredients VALUES (195,"cocoa");
INSERT INTO ingredients VALUES (196,"shortening");
INSERT INTO ingredients VALUES (197,"nutmeg");
INSERT INTO ingredients VALUES (198,"cloves");
INSERT INTO ingredients VALUES (199,"vanilla wafers");
INSERT INTO ingredients VALUES (200,"white corn syrupkaro");
INSERT INTO ingredients VALUES (201,"egg whites");
INSERT INTO ingredients VALUES (202,"salt dash");
INSERT INTO ingredients VALUES (203,"corn crumbs");
INSERT INTO ingredients VALUES (204,"stick oleo");
INSERT INTO ingredients VALUES (205,"bisquick");
INSERT INTO ingredients VALUES (206,"sausage");
INSERT INTO ingredients VALUES (207,"chicken parts");
INSERT INTO ingredients VALUES (208,"consomme");
INSERT INTO ingredients VALUES (209,"celery");
INSERT INTO ingredients VALUES (210,"catsup");
INSERT INTO ingredients VALUES (211,"chicken broth cans");
INSERT INTO ingredients VALUES (212,"apple juice");
INSERT INTO ingredients VALUES (213,"allspice");
INSERT INTO ingredients VALUES (214,"cinnamon stick");
INSERT INTO ingredients VALUES (215,"seed");
INSERT INTO ingredients VALUES (216,"ginger");
INSERT INTO ingredients VALUES (217,"honey");
INSERT INTO ingredients VALUES (218,"chicken breast halves");
INSERT INTO ingredients VALUES (219,"vegetable spray");
INSERT INTO ingredients VALUES (220,"green onion strips");
INSERT INTO ingredients VALUES (221,"mushrooms");
INSERT INTO ingredients VALUES (222,"clove olive oil garlicup");
INSERT INTO ingredients VALUES (223,"eggs ");
INSERT INTO ingredients VALUES (224,"wedges ");
INSERT INTO ingredients VALUES (225,"wedges orange");
INSERT INTO ingredients VALUES (226,"orange gelatin");
INSERT INTO ingredients VALUES (227,"nutsoptional");
INSERT INTO ingredients VALUES (228,"consomme ");
INSERT INTO ingredients VALUES (229,"onion soup");
INSERT INTO ingredients VALUES (230,"berry cranberry sauce");
INSERT INTO ingredients VALUES (231,"walnuts ");
INSERT INTO ingredients VALUES (232,"cream cup");
INSERT INTO ingredients VALUES (233,"velveeta cheese");
INSERT INTO ingredients VALUES (234,"green chili peppers cans");
INSERT INTO ingredients VALUES (235,"salt ");
INSERT INTO ingredients VALUES (236,"milkmore");
INSERT INTO ingredients VALUES (237,"frying");
INSERT INTO ingredients VALUES (238,"margarinenot");
INSERT INTO ingredients VALUES (239,"velveeta");
INSERT INTO ingredients VALUES (240,"squash");
INSERT INTO ingredients VALUES (241,"carrots");
INSERT INTO ingredients VALUES (242,"soup cans");
INSERT INTO ingredients VALUES (243,"stuffing mix");
INSERT INTO ingredients VALUES (244,"cheddar ounce");
INSERT INTO ingredients VALUES (245,"pimento ");
INSERT INTO ingredients VALUES (246,"tabasco sauce dash");
INSERT INTO ingredients VALUES (247,"apricot ounce");
INSERT INTO ingredients VALUES (248,"food apricots");
INSERT INTO ingredients VALUES (249,"number");
INSERT INTO ingredients VALUES (250,"flour ");
INSERT INTO ingredients VALUES (251,"salt dashes");
INSERT INTO ingredients VALUES (252,"butter crisco");
INSERT INTO ingredients VALUES (253,"sweet milk");
INSERT INTO ingredients VALUES (254,"flavoringlemon");
INSERT INTO ingredients VALUES (255,"bread ");
INSERT INTO ingredients VALUES (256,"instant");
INSERT INTO ingredients VALUES (257,"rolls");
INSERT INTO ingredients VALUES (258,"cheese cup");
INSERT INTO ingredients VALUES (259,"hen");
INSERT INTO ingredients VALUES (260,"pork");
INSERT INTO ingredients VALUES (261,"chicken cup");
INSERT INTO ingredients VALUES (262,"chunks");
INSERT INTO ingredients VALUES (263,"carrot chunks");
INSERT INTO ingredients VALUES (264,"chicken bouillon cubes");
INSERT INTO ingredients VALUES (265,"green chunks");
INSERT INTO ingredients VALUES (266,"pineapple chunks");
INSERT INTO ingredients VALUES (267,"oranges");
INSERT INTO ingredients VALUES (268,"cherries");
INSERT INTO ingredients VALUES (269,"orange juice");
INSERT INTO ingredients VALUES (270,"peanut butter cup");
