
USE recipe_analysis;
DROP TABLE IF EXISTS contains;
CREATE TABLE contains(
id INT NOT NULL AUTO_INCREMENT,
misura VARCHAR(50),
quantita VARCHAR(50),
proprieta VARCHAR(100),
recipeID int NOT NULL,
ingredientID int NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (recipeID) REFERENCES recipes(id),
FOREIGN KEY (ingredientID) REFERENCES ingredients(id)
);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','cut, chipped, small',0, 0);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 4','boned',0, 1);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',0, 2);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',0, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 16','frozen',1, 4);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 8','cubed',1, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup','','cubed',1, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2','',1, 7);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2','',1, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/4','',1, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','whole, large',2, 10);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 1/2 10','',2, 11);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',' 1/2 10','',2, 2);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 6','',2, 12);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 4','shredded',2, 13);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',3, 14);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 3/4','',3, 15);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','melted',3, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1/2 1','powdered',3, 17);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1','large',3, 18);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 6','',4, 19);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','lean, extra',4, 20);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2/3','',4, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 6','',4, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 3/4','',4, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2','',4, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 1/2 1','shredded',4, 22);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 12','cooked, sliced',4, 23);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 4','',4, 24);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 8','',4, 25);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2 1','',5, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',5, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',5, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',5, 28);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','',5, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2','',5, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',5, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',5, 28);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','',5, 31);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',5, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',6, 33);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','kernel, whole',6, 4);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 20 1/2','',6, 34);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',6, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 6','',6, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','drained, liquid, upsave',7, 36);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 3/4 1','',7, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',7, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1/2 1','',7, 39);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','',7, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','',7, 41);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','cool, large',8, 42);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','crushed, large',8, 43);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','condensed',8, 44);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 3','',8, 45);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',8, 46);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','crusts',8, 47);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',' 17','dark, pitted',9, 48);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',9, 49);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 6','o',9, 50);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','',9, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/8','',9, 51);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','miniature',9, 52);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','powdered',10, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 8','soft',10, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 8','',10, 14);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',10, 53);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 12','',10, 18);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',11, 54);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',11, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',11, 55);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 8','',12, 56);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 8','',12, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 8','',12, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1','',12, 57);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1','',12, 58);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','shredded',12, 59);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','diced, large',12, 60);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','diced, medium',12, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','diced, large',12, 62);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','shredded',12, 63);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',13, 64);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','crushed',13, 43);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','sweetened, condensed',13, 44);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 8','whipped, thawed',13, 65);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',13, 66);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','baked',14, 67);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' quart',' 1','cleaned',14, 68);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2 1','',14, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 4','',14, 69);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',14, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/8','',14, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 4','',14, 70);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1 1/2','jiffy',15, 71);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1 1/2','jiffy',15, 72);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','',15, 41);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1/2 1 1','large',16, 73);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 10','',16, 23);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4 5','chopped, red',16, 74);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',16, 75);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',16, 76);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',16, 77);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','',16, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1','frozen',17, 78);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','crushed',17, 43);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 3','ripe',17, 79);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','chopped',17, 80);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1','large',17, 81);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2 1','',17, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pint',' 1','',17, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 3/4','',18, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2 1','',18, 82);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 3','',18, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','each',18, 83);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','sifted',18, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',18, 75);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','nuts',18, 84);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',19, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',19, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 2','',19, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','',19, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','',19, 85);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','ripe',19, 86);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1','',20, 87);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1','',20, 88);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 8','',20, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 3/4','',20, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',20, 41);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 4','',20, 89);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 6','chopped',20, 90);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 7 2','up',21, 84);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',21, 91);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',21, 92);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',21, 93);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1/2','',22, 94);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',22, 41);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 6 1/4','minced',22, 95);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','hot',22, 96);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2 1','',22, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',22, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','',22, 97);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1 2','italian',22, 98);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1/2 1','',23, 57);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',23, 99);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',23, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','chopped',23, 100);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/4','',23, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2 1','',23, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 2','',24, 101);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2','black',24, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',24, 102);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',24, 91);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',24, 103);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 2','',24, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','red',24, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',24, 104);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 3','',24, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','chopped',24, 105);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1/8 3/4 1/2 2','thick',25, 106);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',25, 41);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' can15 1','',25, 107);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup','','',25, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','brown',25, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','prepared',25, 108);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','',25, 39);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','sized, medium',25, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',' 14','sweetened, condensed',26, 44);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 12','-, semi',26, 109);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',26, 25);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',26, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1','',27, 57);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1','',27, 58);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',27, 110);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' c 1','',27, 111);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 4','',27, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',27, 60);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' c 1/2','',27, 22);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' c 1/2','',27, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',28, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',28, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1','dry',28, 112);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','',28, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 3','',28, 41);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','plain',28, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','sliced, large',29, 113);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','large',29, 114);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','diced, large',29, 43);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' quart',' 1','fresh',29, 68);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','red',29, 115);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','yellow',29, 115);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 4','ripe, large',29, 79);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1','',29, 116);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1','purple',29, 117);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1','',30, 118);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',30, 41);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup','','red',30, 77);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2 2','',30, 119);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','cherry',31, 120);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',31, 121);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',31, 122);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',31, 85);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 3','',32, 89);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',32, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/4','',32, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','',32, 84);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 3','',32, 19);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','shredded',32, 22);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup','','',32, 123);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',33, 124);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','small',33, 125);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','',34, 126);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',34, 76);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',34, 127);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 16','',35, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1','dry',35, 128);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 10','thawed, chopped, frozen',35, 129);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 6 4','',35, 22);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1','thin',36, 130);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1/2','',36, 131);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','italian, zesty',36, 132);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 3','',37, 133);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 8','softened',37, 134);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 8','',37, 135);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 7','',38, 136);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 7','',38, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','',38, 137);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2','',38, 138);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2','',38, 139);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 3','',39, 10);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 4','',39, 19);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','',39, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',' 16','creamed',39, 140);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 16','',39, 141);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',' 16','field',39, 142);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',' 16','butter',39, 143);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',' 16','',39, 94);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 46','',39, 144);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','small',39, 124);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','black',39, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','',39, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','',39, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 3','softened',40, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','granulated',40, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',40, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',40, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/4 1','baking',40, 145);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/4','',40, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup','','',40, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/4','',40, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup','','packed, brown',40, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2','',40, 146);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',40, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 5','',41, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 3','',41, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 4','baking',41, 145);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1/2 1','dry',41, 112);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','',41, 28);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',41, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1/2 1','',41, 147);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','warm',41, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 8','',42, 52);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','crushed',42, 148);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','yellow',43, 149);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','',43, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','brown',43, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','soft',43, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','',43, 89);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',44, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',44, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 4','',44, 89);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',44, 150);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 3','rising',45, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','',45, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','',46, 151);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','chopped',46, 105);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','',46, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/8','',46, 152);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','sliced',46, 153);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',46, 154);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1','chopped',46, 129);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',46, 155);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','shredded',46, 156);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2 1','sifted',47, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2','baking',47, 145);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2','',47, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',47, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2/3','',47, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 3','',47, 157);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',47, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','colored, -, multi',47, 158);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1/2','',48, 57);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','',48, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',48, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1','mixdry',48, 159);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can pound',' 1','stewed',48, 160);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 8','',48, 144);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 10','mixed, frozen',48, 161);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 4','',49, 1);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',49, 162);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',49, 2);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',49, 163);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',49, 164);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',49, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','grated',49, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1','',49, 165);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 4','shredded',50, 166);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1/2','shredded',50, 167);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','chopped',50, 62);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','chopped',50, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',50, 76);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','',50, 77);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 2','',50, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',50, 168);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/4','',50, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 2','',51, 169);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2 1','chopped',51, 160);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','chopped',51, 170);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup','','',51, 66);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','',51, 171);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 2','',51, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 2','minced',51, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',51, 172);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/4','black, ground',51, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 4','drops, red',51, 173);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',51, 174);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',52, 164);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','yellow',52, 110);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',52, 110);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',52, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',52, 171);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2/3','',52, 77);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup','','',52, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',' 1/2 16','',53, 33);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 8','',53, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 1/2 8','jiffy',53, 175);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',53, 176);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1','',54, 57);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup','','chopped',54, 100);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',54, 177);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','wide',54, 178);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon teaspoon',' 1/2 1/2','oreganumber',54, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup','','',54, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',54, 13);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','small',55, 166);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','dry',55, 108);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','corned',55, 0);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',55, 154);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','chopped, medium',55, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','',56, 39);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','dry',56, 108);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',56, 76);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',56, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 8','softened',57, 134);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',57, 179);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 8','mild',57, 56);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 4 2','sliced',57, 123);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1/2','chopped',57, 180);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',57, 60);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',57, 181);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',57, 22);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','black',57, 182);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',57, 183);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1/2','soft',58, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',58, 14);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1/2','',58, 15);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','',58, 184);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',58, 185);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',58, 186);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1','chopped, sliced',59, 187);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','',59, 188);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','chopped',59, 80);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','condensed',59, 44);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',59, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',59, 189);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','yellow',60, 149);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','',60, 89);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','melted',60, 190);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','',60, 89);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 8','softened',60, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1','powdered',60, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','chunk, large',61, 43);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 5 4','',61, 79);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',62, 2);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',62, 162);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',62, 154);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','cut',62, 191);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','melted',62, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2 1','uncooked',62, 192);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 8','',63, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','sweetened, condensed',63, 44);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1/2','crushed',63, 193);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup','','',63, 66);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 8','',64, 25);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 8','',64, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',64, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',64, 14);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 4','',65, 194);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4 1 1','',65, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4 1','',65, 195);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','',65, 66);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',65, 196);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 16','cool',66, 42);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 2','frozen',66, 68);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 9','deep',66, 197);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 3/4 1','',66, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 12','',66, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',67, 176);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2 1','',67, 15);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','granulated',67, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','sifted',68, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2 1','baking',68, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/4','',68, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2 1','',68, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',68, 198);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',68, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',68, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',68, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 3','medium',69, 115);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','',69, 75);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','brown',69, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','granulated',69, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',69, 199);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','cold',69, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 3','',69, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 2','',69, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',69, 146);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',69, 200);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',69, 201);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',69, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','nuts',69, 84);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 6','diced',70, 19);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','chopped',70, 100);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 3/4','melted',70, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',70, 162);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 8','',70, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','grated',70, 202);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',71, 203);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',71, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2/3 2','',72, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2/3','',72, 204);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2/3','cold',72, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','',72, 205);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',72, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',73, 115);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',73, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',73, 146);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','',73, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',73, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',73, 206);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',73, 207);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',73, 208);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','',74, 209);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1','',74, 210);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 8','',74, 22);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',75, 211);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',75, 162);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',75, 212);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','',75, 192);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',75, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',76, 213);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','chopped',76, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',76, 6);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1','',76, 57);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',76, 77);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',76, 66);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','brown',76, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1/2 1','',76, 108);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',76, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2 1','',76, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',76, 214);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',76, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 3/4 13','',77, 215);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','',77, 69);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','beaten',77, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','sliced1/4',77, 24);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' gallon',' 1/2','',78, 216);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',78, 217);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','whole',78, 201);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',78, 218);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','brown',78, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','',79, 219);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 2','grated',79, 220);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',79, 221);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','reduced',79, 92);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 4','skinned',79, 222);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',79, 223);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','thin',79, 224);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 16','fresh',80, 225);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','',80, 40);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',80, 226);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 6','breadbuttered',80, 16);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 6','',80, 89);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','milkas',80, 227);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 12','',81, 25);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',81, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','peeled, medium',81, 228);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',81, 229);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 3','',81, 230);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',81, 231);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','raw',82, 192);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','beef',82, 232);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','french',82, 233);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',' 4','',82, 225);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1/2','cut',82, 190);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 3','softened',83, 234);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',83, 151);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',83, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',' 16','whole',83, 235);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 3/4','drained, crushed',83, 43);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','chopped',83, 236);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',83, 237);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 2','',84, 238);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 15','italian',84, 141);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','small',84, 239);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2 3','garlicup',84, 240);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/3 1','',85, 29);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/4 1','',85, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2','',85, 30);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',85, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 3/4','',85, 145);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',85, 27);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2/3','',85, 241);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',85, 242);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','powdered',85, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 4','',86, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',86, 198);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1','',86, 243);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1','',86, 244);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','',86, 32);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 3','',87, 245);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 3','',87, 38);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pint',' 1','',87, 3);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 3','',87, 246);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','',87, 247);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1','',87, 248);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',87, 122);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 2','',88, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','shredded',88, 249);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','chopped',88, 250);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','chopped',88, 170);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','chopped',88, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',88, 66);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 2','',88, 39);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',88, 251);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('','','',88, 206);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package',' 1','large',89, 252);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2/3','',89, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' package ounce',' 8','',89, 5);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','junior',89, 253);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','',89, 254);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','evaporated, tall',89, 44);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2/3','',89, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 3','substituted, plain, plain',90, 255);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 3','',90, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/2','baking',90, 145);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 3','',90, 256);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 5','',90, 89);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','',90, 147);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',90, 257);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',90, 258);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 3 2 1','',90, 259);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','softened, frozen',91, 260);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',91, 151);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','brown',91, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','puddingnot, large',91, 261);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',91, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can ounce',' 8','',92, 262);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1/2 1','medium',92, 263);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',92, 264);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','',92, 162);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2 1','',92, 21);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','spanish',93, 141);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' can',' 1','corned',93, 0);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','diced',93, 61);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','grated',93, 202);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1','',94, 265);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 3/4','',94, 214);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1','',94, 8);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon','','black',94, 9);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' pound',' 1','',94, 57);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','',94, 41);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 2','cooked',95, 266);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',95, 199);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',95, 267);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 2','',95, 268);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4 1','',95, 37);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 3','',95, 269);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','brown, packed',95, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',95, 69);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' teaspoon',' 1/4','',95, 220);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','',95, 214);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 2','',95, 77);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' tablespoon',' 1','',95, 92);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',95, 270);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' ounce',' 8','',95, 271);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 10 8','juicy',96, 272);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','moist',96, 184);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',96, 46);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/2','',96, 273);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1/4','',96, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',96, 274);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','creamy',97, 275);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES (' cup',' 1','',97, 26);
INSERT INTO contains (misura, quantita, proprieta, recipeID, ingredientID) VALUES ('',' 1','',97, 27);
