
USE recipe_analysis;
DROP TABLE IF EXISTS instruments;
CREATE TABLE instruments(
id INT PRIMARY KEY,
name VARCHAR(100) NOT NULL
);
INSERT INTO instruments VALUES (0,"bottom");
INSERT INTO instruments VALUES (1,"baking dish");
INSERT INTO instruments VALUES (2,"low");
INSERT INTO instruments VALUES (3,"casserole dish");
INSERT INTO instruments VALUES (4,"box");
INSERT INTO instruments VALUES (5,"ungreased pan");
INSERT INTO instruments VALUES (6,"refrigerator");
INSERT INTO instruments VALUES (7,"fork");
INSERT INTO instruments VALUES (8,"paper towel");
INSERT INTO instruments VALUES (9,"kettle");
INSERT INTO instruments VALUES (10,"ground");
INSERT INTO instruments VALUES (11,"mixture");
INSERT INTO instruments VALUES (12,"teaspoons");
INSERT INTO instruments VALUES (13,"place");
INSERT INTO instruments VALUES (14,"skillet");
INSERT INTO instruments VALUES (15,"bowl");
INSERT INTO instruments VALUES (16,"crust");
INSERT INTO instruments VALUES (17,"mold");
INSERT INTO instruments VALUES (18,"balls");
INSERT INTO instruments VALUES (19,"cookie sheet");
INSERT INTO instruments VALUES (20,"freezer");
INSERT INTO instruments VALUES (21,"boiler");
INSERT INTO instruments VALUES (22,"way");
INSERT INTO instruments VALUES (23,"chip");
INSERT INTO instruments VALUES (24,"microwave bowl");
INSERT INTO instruments VALUES (25,"pizza pan");
INSERT INTO instruments VALUES (26,"13-inch pan");
INSERT INTO instruments VALUES (27,"saucepan");
INSERT INTO instruments VALUES (28,"stalks");
INSERT INTO instruments VALUES (29,"bite size");
INSERT INTO instruments VALUES (30,"pan");
INSERT INTO instruments VALUES (31,"loaf pan");
INSERT INTO instruments VALUES (32,"hand");
INSERT INTO instruments VALUES (33,"processor");
INSERT INTO instruments VALUES (34,"ingredients");
INSERT INTO instruments VALUES (35,"seal");
INSERT INTO instruments VALUES (36,"oven");
INSERT INTO instruments VALUES (37,"game");
INSERT INTO instruments VALUES (38,"world");
INSERT INTO instruments VALUES (39,"liquid");
INSERT INTO instruments VALUES (40,"kidney");
INSERT INTO instruments VALUES (41,"board");
INSERT INTO instruments VALUES (42,"biscuit cutter");
INSERT INTO instruments VALUES (43,"fruit");
INSERT INTO instruments VALUES (44,"center");
INSERT INTO instruments VALUES (45,"rack");
INSERT INTO instruments VALUES (46,"squares");
INSERT INTO instruments VALUES (47,"mixer");
INSERT INTO instruments VALUES (48,"pears");
INSERT INTO instruments VALUES (49,"dish");
INSERT INTO instruments VALUES (50,"baking pan");
INSERT INTO instruments VALUES (51,"tablespoons");
INSERT INTO instruments VALUES (52,"dough");
INSERT INTO instruments VALUES (53,"muffin tin");
INSERT INTO instruments VALUES (54,"pizza pans");
INSERT INTO instruments VALUES (55,"mint layer");
INSERT INTO instruments VALUES (56,"microwave");
INSERT INTO instruments VALUES (57,"baking sheets");
INSERT INTO instruments VALUES (58,"racks");
INSERT INTO instruments VALUES (59,"pot");
INSERT INTO instruments VALUES (60,"store");
INSERT INTO instruments VALUES (61,"layer");
INSERT INTO instruments VALUES (62,"seasonings");
INSERT INTO instruments VALUES (63,"casserole");
INSERT INTO instruments VALUES (64,"time");
INSERT INTO instruments VALUES (65,"order");
INSERT INTO instruments VALUES (66,"hands");
INSERT INTO instruments VALUES (67,"buttered pan");
INSERT INTO instruments VALUES (68,"paper");
INSERT INTO instruments VALUES (69,"chill");
INSERT INTO instruments VALUES (70,"servings");
INSERT INTO instruments VALUES (71,"dollop");
INSERT INTO instruments VALUES (72,"peanuts");
INSERT INTO instruments VALUES (73,"blender");
INSERT INTO instruments VALUES (74,"container");
INSERT INTO instruments VALUES (75,"blueberries");
INSERT INTO instruments VALUES (76,"batter");
INSERT INTO instruments VALUES (77,"pans");
INSERT INTO instruments VALUES (78,"tube pan");
INSERT INTO instruments VALUES (79,"paper towels");
INSERT INTO instruments VALUES (80,"buttered platter");
INSERT INTO instruments VALUES (81,"size balls");
INSERT INTO instruments VALUES (82,"mugs");
INSERT INTO instruments VALUES (83,"guests");
INSERT INTO instruments VALUES (84,"pin");
INSERT INTO instruments VALUES (85,"grill");
INSERT INTO instruments VALUES (86,"side");
INSERT INTO instruments VALUES (87,"funnel");
INSERT INTO instruments VALUES (88,"motion");
INSERT INTO instruments VALUES (89,"inch");
INSERT INTO instruments VALUES (90,"ball");
INSERT INTO instruments VALUES (91,"baby");
INSERT INTO instruments VALUES (92,"crock pot");
INSERT INTO instruments VALUES (93,"hair");
