
USE recipe_analysis;
DROP TABLE IF EXISTS ingredients;
CREATE TABLE ingredients(
id INT PRIMARY KEY,
name VARCHAR(100) NOT NULL
);
INSERT INTO ingredients VALUES (0,"beef");
INSERT INTO ingredients VALUES (1,"chicken breasts");
INSERT INTO ingredients VALUES (2,"mushroom soup cream");
INSERT INTO ingredients VALUES (3,"sour cream");
INSERT INTO ingredients VALUES (4,"corn package");
INSERT INTO ingredients VALUES (5,"cream cubed");
INSERT INTO ingredients VALUES (6,"butter");
INSERT INTO ingredients VALUES (7,"garlic powder");
INSERT INTO ingredients VALUES (8,"salt");
INSERT INTO ingredients VALUES (9,"pepper");
INSERT INTO ingredients VALUES (10,"chicken");
INSERT INTO ingredients VALUES (11,"chicken gravy");
INSERT INTO ingredients VALUES (12,"stuffing");
INSERT INTO ingredients VALUES (13,"cheese");
INSERT INTO ingredients VALUES (14,"peanut butter");
INSERT INTO ingredients VALUES (15,"graham cracker");
INSERT INTO ingredients VALUES (16,"sugar");
INSERT INTO ingredients VALUES (17,"chocolate chips");
INSERT INTO ingredients VALUES (18,"potatoes");
INSERT INTO ingredients VALUES (19,"beef pound");
INSERT INTO ingredients VALUES (20,"milk");
INSERT INTO ingredients VALUES (21,"cheddar");
INSERT INTO ingredients VALUES (22,"bacon");
INSERT INTO ingredients VALUES (23,"green onion");
INSERT INTO ingredients VALUES (24,"ounce");
INSERT INTO ingredients VALUES (25,"egg");
INSERT INTO ingredients VALUES (26,"buttermilk");
INSERT INTO ingredients VALUES (27,"flour");
INSERT INTO ingredients VALUES (28,"soda");
INSERT INTO ingredients VALUES (29,"vanilla");
INSERT INTO ingredients VALUES (30,"cream");
INSERT INTO ingredients VALUES (31,"corn");
INSERT INTO ingredients VALUES (32,"saltine crackers");
INSERT INTO ingredients VALUES (33,"tomatoes");
INSERT INTO ingredients VALUES (34,"water");
INSERT INTO ingredients VALUES (35,"onions");
INSERT INTO ingredients VALUES (36,"worcestershire sauce");
INSERT INTO ingredients VALUES (37,"green");
INSERT INTO ingredients VALUES (38,"oil");
INSERT INTO ingredients VALUES (39,"whip");
INSERT INTO ingredients VALUES (40,"pineapple");
INSERT INTO ingredients VALUES (41,"lemons");
INSERT INTO ingredients VALUES (42,"pecans");
INSERT INTO ingredients VALUES (43,"graham cracker crusts");
INSERT INTO ingredients VALUES (44,"sweet cherries");
INSERT INTO ingredients VALUES (45,"ginger ale");
INSERT INTO ingredients VALUES (46,"cherry gelatin");
INSERT INTO ingredients VALUES (47,"almond extract");
INSERT INTO ingredients VALUES (48,"marshmallows");
INSERT INTO ingredients VALUES (49,"paraffin");
INSERT INTO ingredients VALUES (50,"chicken dinner wingsas");
INSERT INTO ingredients VALUES (51,"barbecue choice");
INSERT INTO ingredients VALUES (52,"taco sauce");
INSERT INTO ingredients VALUES (53,"cream cheese");
INSERT INTO ingredients VALUES (54,"taco seasoning");
INSERT INTO ingredients VALUES (55,"lettuce");
INSERT INTO ingredients VALUES (56,"tomato");
INSERT INTO ingredients VALUES (57,"onion");
INSERT INTO ingredients VALUES (58,"green pepper");
INSERT INTO ingredients VALUES (59,"cheddar colby");
INSERT INTO ingredients VALUES (60,"topping");
INSERT INTO ingredients VALUES (61,"lemon juice");
INSERT INTO ingredients VALUES (62,"pie shell");
INSERT INTO ingredients VALUES (63,"strawberries");
INSERT INTO ingredients VALUES (64,"cornstarch");
INSERT INTO ingredients VALUES (65,"strawberry jello");
INSERT INTO ingredients VALUES (66,"chocolate fudge cake pudding mix");
INSERT INTO ingredients VALUES (67,"white cake pudding mix");
INSERT INTO ingredients VALUES (68,"head");
INSERT INTO ingredients VALUES (69,"bacon slices");
INSERT INTO ingredients VALUES (70,"green onions");
INSERT INTO ingredients VALUES (71,"raisins");
INSERT INTO ingredients VALUES (72,"mayonnaise");
INSERT INTO ingredients VALUES (73,"vinegar");
INSERT INTO ingredients VALUES (74,"juice strawberries");
INSERT INTO ingredients VALUES (75,"bananas");
INSERT INTO ingredients VALUES (76,"strawberry o");
INSERT INTO ingredients VALUES (77,"applesauce");
INSERT INTO ingredients VALUES (78,"cinnamon teaspoon");
INSERT INTO ingredients VALUES (79,"nuts");
INSERT INTO ingredients VALUES (80,"food cake mix");
INSERT INTO ingredients VALUES (81,"chocolate fudge pudding mixinstant");
INSERT INTO ingredients VALUES (82,"eggs");
INSERT INTO ingredients VALUES (83,"mints");
INSERT INTO ingredients VALUES (84,"cup");
INSERT INTO ingredients VALUES (85,"vegetable oil");
INSERT INTO ingredients VALUES (86,"soy sauce cup");
INSERT INTO ingredients VALUES (87,"garlic salt");
INSERT INTO ingredients VALUES (88,"tomato paste garlicup");
INSERT INTO ingredients VALUES (89,"sweet");
INSERT INTO ingredients VALUES (90,"sweet basil");
INSERT INTO ingredients VALUES (91,"seasoning oreganumber");
INSERT INTO ingredients VALUES (92,"tomato juice");
INSERT INTO ingredients VALUES (93,"oatsuncooked");
INSERT INTO ingredients VALUES (94,"round steak");
INSERT INTO ingredients VALUES (95,"white pepper");
INSERT INTO ingredients VALUES (96,"peppers");
INSERT INTO ingredients VALUES (97,"beef stock");
INSERT INTO ingredients VALUES (98,"flourdredging");
INSERT INTO ingredients VALUES (99,"celery");
INSERT INTO ingredients VALUES (100,"tomato sauce");
INSERT INTO ingredients VALUES (101,"mustard");
INSERT INTO ingredients VALUES (102,"sweet chocolate chips");
INSERT INTO ingredients VALUES (103,"beans");
INSERT INTO ingredients VALUES (104,"salsa");
INSERT INTO ingredients VALUES (105,"green peppers");
INSERT INTO ingredients VALUES (106,"cheddar cheese");
INSERT INTO ingredients VALUES (107,"yeast");
INSERT INTO ingredients VALUES (108,"flour cup");
INSERT INTO ingredients VALUES (109,"peaches");
INSERT INTO ingredients VALUES (110,"cocktail");
INSERT INTO ingredients VALUES (111,"apples");
INSERT INTO ingredients VALUES (112,"white grapes");
INSERT INTO ingredients VALUES (113,"grapes");
INSERT INTO ingredients VALUES (114,"chicken cutlets");
INSERT INTO ingredients VALUES (115,"garlic salt oreganumber");
INSERT INTO ingredients VALUES (116,"cherry pie mix");
INSERT INTO ingredients VALUES (117,"white cake mix");
INSERT INTO ingredients VALUES (118,"stick butter");
INSERT INTO ingredients VALUES (119,"half");
INSERT INTO ingredients VALUES (120,"macaroni");
INSERT INTO ingredients VALUES (121,"tuna");
INSERT INTO ingredients VALUES (122,"pimentos");
INSERT INTO ingredients VALUES (123,"artichoke cans");
INSERT INTO ingredients VALUES (124,"parmesan cheese");
INSERT INTO ingredients VALUES (125,"vegetable soup mix");
INSERT INTO ingredients VALUES (126,"broccoli");
INSERT INTO ingredients VALUES (127,"spaghetti pound");
INSERT INTO ingredients VALUES (128,"salad");
INSERT INTO ingredients VALUES (129,"dressing");
INSERT INTO ingredients VALUES (130,"lime gelatin");
INSERT INTO ingredients VALUES (131,"lemon yogurt");
INSERT INTO ingredients VALUES (132,"watermelon rind");
INSERT INTO ingredients VALUES (133,"apple vinegar");
INSERT INTO ingredients VALUES (134,"cloves oil");
INSERT INTO ingredients VALUES (135,"cinnamon oil");
INSERT INTO ingredients VALUES (136,"peas english");
INSERT INTO ingredients VALUES (137,"peas");
INSERT INTO ingredients VALUES (138,"beans butter");
INSERT INTO ingredients VALUES (139,"powder");
INSERT INTO ingredients VALUES (140,"cinnamon");
INSERT INTO ingredients VALUES (141,"sticks margarine");
INSERT INTO ingredients VALUES (142,"peppermint candy");
INSERT INTO ingredients VALUES (143,"rolls");
INSERT INTO ingredients VALUES (144,"cake mix");
INSERT INTO ingredients VALUES (145,"butter cup");
INSERT INTO ingredients VALUES (146,"syrup");
INSERT INTO ingredients VALUES (147,"flour self");
INSERT INTO ingredients VALUES (148,"margarine");
INSERT INTO ingredients VALUES (149,"curry powder");
INSERT INTO ingredients VALUES (150,"juice");
INSERT INTO ingredients VALUES (151,"celery soup cream");
INSERT INTO ingredients VALUES (152,"jack cheese");
INSERT INTO ingredients VALUES (153,"egg yolks");
INSERT INTO ingredients VALUES (154,"candies");
INSERT INTO ingredients VALUES (155,"soup onion soup cup");
INSERT INTO ingredients VALUES (156,"vegetables");
INSERT INTO ingredients VALUES (157,"chicken soup cream");
INSERT INTO ingredients VALUES (158,"green chili salsa sauce");
INSERT INTO ingredients VALUES (159,"corn pieces tortilla");
INSERT INTO ingredients VALUES (160,"cabbage");
INSERT INTO ingredients VALUES (161,"carrots");
INSERT INTO ingredients VALUES (162,"celery seed");
INSERT INTO ingredients VALUES (163,"pollack flounder");
INSERT INTO ingredients VALUES (164,"tomatoes cup");
INSERT INTO ingredients VALUES (165,"salad oil");
INSERT INTO ingredients VALUES (166,"basil leaves");
INSERT INTO ingredients VALUES (167,"pepper sauce");
INSERT INTO ingredients VALUES (168,"green pepper rings");
INSERT INTO ingredients VALUES (169,"green beans");
INSERT INTO ingredients VALUES (170,"cream corn ounce");
INSERT INTO ingredients VALUES (171,"bread mix corn");
INSERT INTO ingredients VALUES (172,"stick margarine");
INSERT INTO ingredients VALUES (173,"tomato soup");
INSERT INTO ingredients VALUES (174,"noodles");
INSERT INTO ingredients VALUES (175,"salt oreganumber");
INSERT INTO ingredients VALUES (176,"shakes");
INSERT INTO ingredients VALUES (177,"salad mayonnaise");
INSERT INTO ingredients VALUES (178,"taco sauce ounce");
INSERT INTO ingredients VALUES (179,"mozzarella cheese");
INSERT INTO ingredients VALUES (180,"olivesoptional");
INSERT INTO ingredients VALUES (181,"tortilla chips");
INSERT INTO ingredients VALUES (182,"coconut");
INSERT INTO ingredients VALUES (183,"meatsoptional");
INSERT INTO ingredients VALUES (184,"vanilla dash");
INSERT INTO ingredients VALUES (185,"candy");
INSERT INTO ingredients VALUES (186,"orange flavoring");
INSERT INTO ingredients VALUES (187,"stick");
INSERT INTO ingredients VALUES (188,"rice cup");
INSERT INTO ingredients VALUES (189,"cream cheese ounce");
INSERT INTO ingredients VALUES (190,"sour light");
INSERT INTO ingredients VALUES (191,"strawberries package");
INSERT INTO ingredients VALUES (192,"pie crusts");
INSERT INTO ingredients VALUES (193,"cocoa");
INSERT INTO ingredients VALUES (194,"water cup");
INSERT INTO ingredients VALUES (195,"nutmeg");
INSERT INTO ingredients VALUES (196,"cloves");
INSERT INTO ingredients VALUES (197,"cheddar cheese cup");
INSERT INTO ingredients VALUES (198,"vanilla wafers");
INSERT INTO ingredients VALUES (199,"white corn cup");
INSERT INTO ingredients VALUES (200,"egg whites");
INSERT INTO ingredients VALUES (201,"salt dash");
INSERT INTO ingredients VALUES (202,"corn crumbs");
INSERT INTO ingredients VALUES (203,"stick oleo");
INSERT INTO ingredients VALUES (204,"bisquick");
INSERT INTO ingredients VALUES (205,"sausage");
INSERT INTO ingredients VALUES (206,"chicken parts");
INSERT INTO ingredients VALUES (207,"consomme");
INSERT INTO ingredients VALUES (208,"rice");
INSERT INTO ingredients VALUES (209,"catsup");
INSERT INTO ingredients VALUES (210,"chicken broth cans");
INSERT INTO ingredients VALUES (211,"apple juice");
INSERT INTO ingredients VALUES (212,"allspice");
INSERT INTO ingredients VALUES (213,"cinnamon stick");
INSERT INTO ingredients VALUES (214,"toasted");
INSERT INTO ingredients VALUES (215,"ginger");
INSERT INTO ingredients VALUES (216,"honey");
INSERT INTO ingredients VALUES (217,"soy sauce");
INSERT INTO ingredients VALUES (218,"chicken breast");
INSERT INTO ingredients VALUES (219,"vegetable spray");
INSERT INTO ingredients VALUES (220,"green onion strips");
INSERT INTO ingredients VALUES (221,"mushrooms package");
INSERT INTO ingredients VALUES (222,"clove olive oil garlicup");
INSERT INTO ingredients VALUES (223,"butter pieces");
INSERT INTO ingredients VALUES (224,"eggs milkas");
INSERT INTO ingredients VALUES (225,"wedges");
INSERT INTO ingredients VALUES (226,"wedges orange");
INSERT INTO ingredients VALUES (227,"orange gelatin");
INSERT INTO ingredients VALUES (228,"nutsoptional");
INSERT INTO ingredients VALUES (229,"beef consomme");
INSERT INTO ingredients VALUES (230,"onion soup");
INSERT INTO ingredients VALUES (231,"mushrooms");
INSERT INTO ingredients VALUES (232,"berry cranberry sauce whole");
INSERT INTO ingredients VALUES (233,"walnuts");
INSERT INTO ingredients VALUES (234,"cream cup");
INSERT INTO ingredients VALUES (235,"velveeta cheese");
INSERT INTO ingredients VALUES (236,"green chili peppers cans");
INSERT INTO ingredients VALUES (237,"cloves garlicup");
INSERT INTO ingredients VALUES (238,"milkmore");
INSERT INTO ingredients VALUES (239,"velveeta");
INSERT INTO ingredients VALUES (240,"squash");
INSERT INTO ingredients VALUES (241,"mushroom chicken cans");
INSERT INTO ingredients VALUES (242,"stuffing mix");
INSERT INTO ingredients VALUES (243,"cheddar cup");
INSERT INTO ingredients VALUES (244,"pimento");
INSERT INTO ingredients VALUES (245,"tabasco sauce dash");
INSERT INTO ingredients VALUES (246,"apricot ounce");
INSERT INTO ingredients VALUES (247,"food apricots jars");
INSERT INTO ingredients VALUES (248,"number");
INSERT INTO ingredients VALUES (249,"salt dashes");
INSERT INTO ingredients VALUES (250,"butter crisco");
INSERT INTO ingredients VALUES (251,"sweet milk cup");
INSERT INTO ingredients VALUES (252,"flavoringlemon");
INSERT INTO ingredients VALUES (253,"bread");
INSERT INTO ingredients VALUES (254,"vanilla instant");
INSERT INTO ingredients VALUES (255,"rolls crescent");
INSERT INTO ingredients VALUES (256,"hen");
INSERT INTO ingredients VALUES (257,"pork");
INSERT INTO ingredients VALUES (258,"chunks");
INSERT INTO ingredients VALUES (259,"carrot chunks");
INSERT INTO ingredients VALUES (260,"chicken bouillon cubes");
INSERT INTO ingredients VALUES (261,"green chunks");
INSERT INTO ingredients VALUES (262,"pineapple chunks");
INSERT INTO ingredients VALUES (263,"oranges");
INSERT INTO ingredients VALUES (264,"cherries");
INSERT INTO ingredients VALUES (265,"orange juice");
